import type { Article } from "../../types";

export const article: Article = {
  slug: "defender-asr-audit-to-block",
  category: "cybersecurity-ciso",
  contentType: "how-to",
  subcategory: "Microsoft Defender",
  title: "Microsoft Defender ASR rules: from audit to block",
  seoTitle: "Microsoft Defender ASR Rules: Audit to Block",
  metaDescription: "A practical Microsoft Defender ASR rollout from audit to block with pilots, exclusions, rings, and monitoring.",
  standfirst: "ASR rules work best as a rollout, not a switch. Start with audit, learn the impact, then block in rings.",
  excerpt: "Use audit mode to learn. Fix exclusions. Move to block in small rings. Then keep watching the result.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 6,
  primaryKeyword: "Defender ASR rules deployment",
  secondaryKeywords: ["attack surface reduction", "ASR audit mode", "ASR block mode", "Defender for Endpoint"],
  tags: ["Microsoft Defender", "Endpoint Security", "Windows", "Intune", "CISO"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn guidance for Attack Surface Reduction rule deployment. The rollout stages and audit-to-block flow follow Microsoft's published deployment guide.",
  body: [
    { type: "p", text: "Attack Surface Reduction rules stop risky behavior on Windows devices. They can block actions that attackers use. They can also affect real business apps." },
    { type: "p", text: "That is why a good ASR rollout starts in audit mode. Microsoft recommends testing rules in audit mode before moving many rules to block or warn mode. " },
    { type: "h2", id: "what-asr-does", text: "What ASR does" },
    { type: "p", text: "ASR rules target risky behavior. Examples include script activity, Office child processes, and code injection. The exact rules and support vary by Windows and Defender plan." },
    { type: "h2", id: "start-with-audit", text: "Start with audit" },
    { type: "p", text: "Audit mode lets you see what a rule would affect. It does not block the action. Use this time to find real business use cases." },
    { type: "ol", items: ["Choose a small pilot group.", "Enable selected rules in audit mode.", "Collect detections and events.", "Ask app owners about real use cases.", "Add only needed exclusions."] },
    { type: "callout", variant: "note", title: "Do not turn every rule on at once", text: "A large first change makes the result hard to read. A small pilot gives you better data." },
    { type: "h2", id: "review-events", text: "Review events" },
    { type: "p", text: "An audit event is not proof that an exclusion is needed. First ask why the action happened. Check the process, user, app, device, and business task." },
    { type: "p", text: "If the action is expected, decide whether to change the app or create a narrow exclusion. Broad exclusions reduce the value of the rule." },
    { type: "h2", id: "move-to-block", text: "Move to block" },
    { type: "p", text: "When the pilot is clean, move selected rules to Block or Warn. Microsoft recommends starting with the first deployment ring. Then expand to the next ring." },
    { type: "ol", items: ["Set a small set of rules to Block or Warn.", "Watch user impact.", "Fix false positives.", "Expand to the next ring.", "Repeat until the fleet is covered."] },
    { type: "h2", id: "rings", text: "Use deployment rings" },
    { type: "p", text: "A simple ring model can use IT first, then power users, then a wider business group, then the full fleet. Keep a rollback path for each ring." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Blocking before audit data is known.", "Using one huge exclusion.", "Ignoring app owners.", "Expanding all rings at the same time.", "Stopping after deployment and not monitoring events."] },
    { type: "h2", id: "operations", text: "Keep ASR healthy" },
    { type: "p", text: "ASR is not a one time project. Windows and apps change. A rule that was quiet last month can become active after an app update." },
    { type: "p", text: "Keep an owner for ASR. Review events. Review exclusions. Use Defender reports and advanced hunting when you need more detail." },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "The safest ASR rollout is staged. Audit first. Learn the impact. Fix real issues. Then block in rings. Keep monitoring after the rollout." },
  ],
  faq: [
    { question: "Should ASR rules start in audit mode?", answer: "Microsoft recommends testing many ASR rules in audit mode before moving them to Block or Warn." },
    { question: "Should all ASR rules be blocked at once?", answer: "A staged rollout is easier to test. Microsoft documents moving the first ring to Block or Warn and then expanding to more rings." },
    { question: "What should an ASR exclusion contain?", answer: "Use the narrowest exclusion that solves a confirmed business need. Avoid broad exclusions." },
  ],
  sources: [
    { title: "ASR rules deployment guide", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/defender-endpoint/attack-surface-reduction-rules-deployment" },
    { title: "Enable your ASR rules deployment", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/defender-endpoint/attack-surface-reduction-rules-deployment-implement" },
    { title: "Plan your ASR rules deployment", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/defender-endpoint/attack-surface-reduction-rules-deployment-plan" },
  ],
};
