import type { Article } from "../../types";

export const article: Article = {
  slug: "purview-adaptive-protection-dlp",
  category: "cybersecurity-ciso",
  contentType: "explainer",
  subcategory: "Microsoft Purview",
  title: "Microsoft Purview Adaptive Protection: connect risk to DLP",
  seoTitle: "Purview Adaptive Protection: Connect Insider Risk to DLP",
  metaDescription: "How Microsoft Purview Adaptive Protection links Insider Risk Management risk levels with dynamic DLP controls.",
  standfirst: "Risk can change. Adaptive Protection lets DLP change with it.",
  excerpt: "Adaptive Protection can adjust DLP controls when a user's insider risk level changes.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 6,
  primaryKeyword: "Purview Adaptive Protection",
  secondaryKeywords: ["Purview DLP", "Insider Risk Management", "adaptive DLP", "data loss prevention"],
  tags: ["Microsoft Purview", "DLP", "Insider Risk", "Compliance", "Security"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Purview Adaptive Protection and Insider Risk Management. The article explains documented product behavior and keeps recommendations separate.",
  body: [
    { type: "p", text: "DLP rules often stay the same for every user. Risk does not. A user can move from low risk to high risk after a new signal appears." },
    { type: "p", text: "Microsoft Purview Adaptive Protection links Insider Risk Management with Data Loss Prevention. When a user gets an insider risk level, DLP can use that level to apply stronger controls. " },
    { type: "h2", id: "the-basic-model", text: "The basic model" },
    { type: "p", text: "Think of the flow as three steps: detect risk, set a risk level, adjust protection." },
    { type: "ol", items: ["Insider Risk Management evaluates signals.", "The user receives an insider risk level.", "Adaptive Protection can apply a DLP policy for that level."] },
    { type: "h2", id: "why-this-helps", text: "Why this helps" },
    { type: "p", text: "A single DLP rule may be too weak for a high risk case. A rule that blocks everyone may create too much friction." },
    { type: "p", text: "Adaptive Protection gives a middle path. Normal users can keep normal controls. Higher risk users can receive stronger DLP controls." },
    { type: "h2", id: "risk-levels", text: "Use clear risk levels" },
    { type: "p", text: "The exact risk model belongs to the organization. Keep it simple. Define what low, medium, and high risk should mean. Then map each level to a clear DLP action." },
    { type: "table", caption: "Example operating model", head: ["Risk", "Example response"], rows: [["Low", "Normal DLP policy"], ["Medium", "Warn and monitor"], ["High", "Stronger DLP controls"]] },
    { type: "p", text: "This table is an example design, not a Microsoft default. Test the user impact before enforcement." },
    { type: "h2", id: "privacy", text: "Keep privacy in the design" },
    { type: "p", text: "Insider Risk Management is sensitive. Microsoft documents privacy by design, pseudonymization by default, role based access, and audit logs." },
    { type: "p", text: "Use the least access needed for reviewers and investigators. Define who can see user level details. Keep an audit trail." },
    { type: "h2", id: "rollout", text: "Roll it out in stages" },
    { type: "ol", items: ["Define the risk model.", "Define DLP actions for each level.", "Test the rules with a pilot.", "Review false positives.", "Tune the policy.", "Move to wider use."] },
    { type: "callout", variant: "warning", title: "Do not start with maximum blocking", text: "A hard block can affect real work. Test the signal quality and user impact first." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Treating a risk score as proof of wrongdoing.", "Using one DLP action for every risk level.", "Giving too many people access to sensitive risk data.", "Skipping pilot tests.", "Forgetting to review policy impact."] },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "Adaptive Protection connects a changing risk state to a changing DLP response. That can reduce both over blocking and under protection. The key is a clear risk model, careful access control, and staged rollout." },
  ],
  faq: [
    { question: "What is Purview Adaptive Protection?", answer: "It links Microsoft Purview Insider Risk Management risk levels with DLP controls that can change as the risk level changes." },
    { question: "Does Adaptive Protection replace DLP?", answer: "No. It adds a way for DLP controls to respond to insider risk levels." },
    { question: "Does Microsoft publish one risk model for every organization?", answer: "No. Adaptive Protection is configurable, and Microsoft notes that risk levels and mitigation actions depend on the organization's needs." },
  ],
  sources: [
    { title: "Learn about Adaptive Protection in DLP", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/purview/dlp-adaptive-protection-learn" },
    { title: "Adaptive Protection configuration guide", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/purview/insider-risk-management-adaptive-protection-guide" },
  ],
};
