import type { Block } from "../../types";

export const bodyPart4: Block[] = [
    {"type": "h2", "id": "dependency-failure", "text": "The healthy cluster that still loses the app"},
    {"type": "p", "text": "Consider a service with several healthy Pods. The nodes are healthy. Ingress is healthy. The Pods report Ready."},
    {"type": "p", "text": "The database reaches its connection limit. Each Pod begins retrying failed operations. Retries increase database pressure. Requests take longer. Clients retry as well. The cluster still has healthy Pods, but the customer operation is no longer completing."},
    {"type": "p", "text": "This is why part health and service health must be measured separately. The recovery plan must include dependency behavior and retry policy, not only Pod replacement."},
    {"type": "h2", "id": "ha-vs-dr", "text": "High uptime is not disaster recovery"},
    {"type": "p", "text": "Microsoft's AKS article is explicit about its scope: app-level HA within one cluster is different from disaster recovery across clusters or regions."},
    {"type": "p", "text": "A workload can survive a Pod or zone failure and still have no answer for loss of the region. The reverse is also possible. A team can deploy a second region while each regional app still has fragile shared dependencies."},
    {"type": "p", "text": "A multiregion design introduces its own work. Traffic management, data replication, identity, secrets, setup, container images, dependencies, and failover procedures all need a design and a test. Microsoft documents active-active AKS patterns with independent clusters and global traffic management, but that is a larger design than in-cluster HA."},
    {"type": "h2", "id": "testing", "text": "Test the failure assumptions, not the diagram"},
    {"type": "p", "text": "The most useful HA test is not a screenshot of a green cluster. Test the failure that the design claims to survive."},
    {"type": "ul", "items": ["Make one app replica unhealthy.", "Remove one node.", "Test the workload's response to a zone-level loss where the environment supports that exercise.", "Make a dependency slow or unavailable.", "Return dependency errors and observe retry behavior.", "Block replacement capacity and confirm what users experience.", "Test a storage or state recovery path."]},
    {"type": "p", "text": "For each test, measure detection time, traffic isolation, recovery time, and customer impact. Record what happened. The next design decision should come from observed behavior, not an assumption about what Kubernetes ought to do."},
    {"type": "h2", "id": "review", "text": "A practical AKS uptime review"},
    {"type": "p", "text": "A review can stay simple if it follows the service path."},
    {"type": "ol", "items": ["Draw one customer operation from entry to response.", "List every part and dependency on that path.", "Mark which items can fail together.", "For each critical item, define detection, isolation, repair, and return to service.", "Find state that must survive the failure.", "Check whether capacity can absorb the event.", "Separate in-cluster HA requirements from regional disaster recovery requirements.", "Run the failures that matter most to the business."]},
    {"type": "h2", "id": "runbook", "text": "Write down what the team will do when the path breaks"},
    {"type": "p", "text": "A good HA plan is not only a set of YAML rules. It also tells the on-call team what to check first. Keep the first steps short. Start with the user path. Is the site up? Can the app take a request? Are ready Pods getting the work? Is one shared service slow or down?"},
    {"type": "p", "text": "Then split the fault. If one Pod is bad, take it out of the path and see if the rest can carry the load. If all Pods fail in the same way, stop looking at replica count and move to the shared path. Check the database, login flow, DNS, network route, or external API that all of them use."},
    {"type": "p", "text": "Write the safe action for each case. A Pod fault may need no human step at all. A bad release may need a rollback. A full database may need the team that owns the data store. A region loss may need a wider disaster plan. The runbook should say who owns each step and how the team knows the step worked."},
    {"type": "p", "text": "Also write the stop rules. More retries are not always a fix. More Pods are not always a fix. A restart can make a shared fault worse if every new Pod hits the same bad service at once. When the cause is not in the Pod, fast restarts can hide the real problem and add more load."},
    {"type": "p", "text": "After the event, keep one clear record. Note what failed, how it was seen, what users felt, what action helped, and what part of the path still had no backup. That record is more useful than a claim that the system is highly available. It shows where the next change should go."},
    {"type": "h2", "id": "conclusion", "text": "The takeaway"},
    {"type": "p", "text": "The strongest lesson in Microsoft's AKS guidance is simple: high uptime is a property of the whole service path."},
    {"type": "p", "text": "Replicas are important, but they are not the model. Start with the request. Find what every successful request shares. Look for failures that can affect those shared parts together. Then decide which failure modes the business needs the service to survive."},
    {"type": "p", "text": "Use Kubernetes for placement, health checks, replacement, and scaling. Design the database, network, identity, storage, and external dependencies with the same care. Monitor the customer path. Test recovery under real failure."},
    {"type": "p", "text": "An AKS cluster can be healthy while the app is unavailable. Good uptime design makes that gap smaller, visible, and recoverable."},
];
