import type { Article } from "../../types";

export const article: Article = {
  slug: "entra-global-secure-access-vpn",
  category: "microsoft-entra",
  contentType: "decision-framework",
  subcategory: "Global Secure Access",
  title: "Microsoft Entra Global Secure Access: a path beyond VPN",
  seoTitle: "Microsoft Entra Global Secure Access: Beyond VPN",
  metaDescription: "A clear guide to Microsoft Entra Global Secure Access, Private Access, Internet Access, and a staged VPN migration.",
  standfirst: "A VPN gives network access. Global Secure Access can make access more focused on identity and apps.",
  excerpt: "See where Global Secure Access fits, how Private Access differs from a VPN, and how to plan a safe pilot.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 6,
  primaryKeyword: "Microsoft Entra Global Secure Access",
  secondaryKeywords: ["Global Secure Access VPN", "Microsoft Entra Private Access", "Zero Trust access", "VPN replacement"],
  tags: ["Microsoft Entra", "Global Secure Access", "Zero Trust", "Networking"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Global Secure Access and Private Access. Product behavior is based on the cited Microsoft sources.",
  body: [
    { type: "p", text: "A VPN solves remote access. A user connects to the VPN. The user then reaches a private network." },
    { type: "p", text: "That model is still useful. It can also give more network access than the user needs. Global Secure Access offers a more focused model." },
    { type: "h2", id: "what-it-is", text: "What Global Secure Access is" },
    { type: "p", text: "Global Secure Access is a Microsoft Security Service Edge model. It brings Microsoft traffic, Private Access, and Internet Access into one client and policy model." },
    { type: "h2", id: "private-access", text: "Private Access" },
    { type: "p", text: "Private Access is for private resources. It can give a user access to a specific app without giving broad access to the whole network." },
    { type: "h2", id: "internet-access", text: "Internet Access" },
    { type: "p", text: "Internet Access handles other internet traffic. Microsoft documents web filtering and threat controls for this profile." },
    { type: "h2", id: "migration", text: "Do not remove the VPN first" },
    { type: "p", text: "A VPN replacement is a migration. Start with one app. Pick one user group. Keep the old path during the test." },
    { type: "ol", items: ["List VPN apps and owners.", "Pick one low risk app.", "Build Private Access for that app.", "Test with a small user group.", "Measure failures.", "Expand in rings."] },
    { type: "h2", id: "zero-trust", text: "Where Zero Trust fits" },
    { type: "p", text: "Zero Trust does not mean no network. It means access is checked with more context. Identity, device, app, and policy can all matter." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Trying to replace every VPN app at once.", "Giving a whole subnet to every user.", "Skipping device checks.", "Ignoring old VPN routes.", "Testing only one user and one device."] },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "Global Secure Access can change remote access from network reach to app reach. The safest path is staged. Start small. Prove one app. Then expand." },
  ],
  faq: [
    { question: "Is Global Secure Access the same as a VPN?", answer: "No. It can provide private app access, but its model is based on identity and policy rather than broad network access." },
    { question: "Can Private Access replace a VPN?", answer: "It can replace many private application access cases. Each app and protocol still needs testing." },
    { question: "Should the VPN be removed before the pilot?", answer: "No. Keep the old path during the pilot so you have a safe fallback." },
  ],
  sources: [
    { title: "What is Global Secure Access?", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/global-secure-access/overview-what-is-global-secure-access" },
    { title: "Quickstart: Configure per-app access to private resources", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/global-secure-access/quickstart-per-app-access" },
    { title: "Quickstart: Configure Quick Access to private resources", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/global-secure-access/quickstart-quick-access" },
  ],
};
