import type { Article } from "../../types";

export const article: Article = {
  slug: "entra-pim-just-in-time",
  category: "microsoft-entra",
  contentType: "how-to",
  subcategory: "Privileged Identity Management",
  title: "Microsoft Entra PIM: design just-in-time admin access",
  seoTitle: "Microsoft Entra PIM: Design Just-in-Time Admin Access",
  metaDescription: "A practical Microsoft Entra PIM model for eligible roles, activation, MFA, approval, time limits, and review.",
  standfirst: "Admin access should be available when needed, not active all day.",
  excerpt: "Use PIM to move privileged roles from standing access to controlled, time limited activation.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 6,
  primaryKeyword: "Microsoft Entra PIM",
  secondaryKeywords: ["just-in-time access", "eligible role", "privileged access", "PIM activation"],
  tags: ["Microsoft Entra", "PIM", "Identity Governance", "Privileged Access"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Microsoft Entra Privileged Identity Management. The article uses documented PIM capabilities and marks operating choices as recommendations.",
  body: [
    { type: "p", text: "A permanent admin role is easy to use. It is also always available." },
    { type: "p", text: "Microsoft Entra Privileged Identity Management, or PIM, can make privileged access time based and approval based. A user can be eligible for a role and activate it only when work needs it. " },
    { type: "h2", id: "eligible-vs-active", text: "Eligible versus active" },
    { type: "p", text: "An active role can be used at once. An eligible role needs activation. The user may need MFA, a reason, or approval before the role becomes active." },
    { type: "h2", id: "core-controls", text: "Core PIM controls" },
    { type: "ul", items: ["Just in time activation.", "Time limits.", "Approval.", "MFA at activation.", "Business justification.", "Activation alerts.", "Audit history.", "Access reviews."] },
    { type: "h2", id: "simple-model", text: "A simple admin model" },
    { type: "ol", items: ["Make the user eligible.", "Set a short activation window.", "Require strong authentication.", "Require approval for high risk roles.", "Require a reason.", "Review activation logs."] },
    { type: "h2", id: "role-design", text: "Do not use Global Administrator for every task" },
    { type: "p", text: "PIM does not fix an oversized role. Use the smallest role that can do the task. Then use PIM to control when that role becomes active." },
    { type: "h2", id: "pim-groups", text: "PIM for Groups" },
    { type: "p", text: "PIM can also manage just in time membership or ownership of supported groups. This can help when a group grants access to an app or resource." },
    { type: "h2", id: "approval", text: "Use approval where it adds value" },
    { type: "p", text: "Approval adds a human check. It can make sense for high impact roles. It can also slow work. Use it where the risk justifies the delay." },
    { type: "callout", variant: "tip", title: "Protect the emergency path", text: "Keep emergency access accounts outside normal activation flows and test them on a set schedule." },
    { type: "h2", id: "review", text: "Review privileged access" },
    { type: "p", text: "An eligible role can stay forever. That does not mean it should. Use access reviews to check whether people still need privileged eligibility." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Leaving old active roles in place.", "Giving every admin Global Administrator.", "Using very long activation windows.", "Skipping MFA at activation.", "Never reviewing eligible assignments."] },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "PIM changes admin access from standing permission to controlled activation. Use small roles, short windows, strong sign in checks, and regular reviews. That makes privileged access easier to control and audit." },
  ],
  faq: [
    { question: "What is PIM?", answer: "Microsoft Entra Privileged Identity Management helps manage, control, and monitor privileged access with features such as eligible roles, activation, approval, MFA, and audit history." },
    { question: "What is an eligible role?", answer: "It is a role assignment that requires the user to activate the role before using its privileges." },
    { question: "Can PIM manage groups?", answer: "Yes. PIM for Groups can manage just in time membership and ownership for supported groups." },
  ],
  sources: [
    { title: "What is Privileged Identity Management?", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-configure" },
    { title: "Start using PIM", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-getting-started" },
    { title: "Plan a PIM deployment", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-deployment-plan" },
  ],
};
