import type { Article } from "../../types";

export const article: Article = {
  slug: "entra-private-access-per-app",
  category: "microsoft-entra",
  contentType: "decision-framework",
  subcategory: "Global Secure Access",
  title: "Microsoft Entra Private Access: move from VPN to per-app access",
  seoTitle: "Microsoft Entra Private Access: From VPN to Per-App Access",
  metaDescription: "How Microsoft Entra Private Access uses per-app segments, connector groups, Conditional Access, and the Global Secure Access client.",
  standfirst: "A VPN can open a network. Private Access can open only the app a user needs.",
  excerpt: "Use Microsoft Entra Private Access to segment private apps and reduce broad network access.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 7,
  primaryKeyword: "Microsoft Entra Private Access",
  secondaryKeywords: ["Global Secure Access", "per-app access", "VPN replacement", "private network connector"],
  tags: ["Microsoft Entra", "Global Secure Access", "Zero Trust", "Networking", "VPN"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Microsoft Entra Private Access and Global Secure Access. Configuration steps and limits are based on the cited Microsoft sources.",
  body: [
    { type: "p", text: "A VPN can give a user access to a network. That is simple. It can also give the user more access than the task needs." },
    { type: "p", text: "Microsoft Entra Private Access takes a more focused path. It lets you define private apps and the network segments behind them. The Global Secure Access client then sends matching traffic through the service. " },
    { type: "h2", id: "vpn-vs-app", text: "Network access versus app access" },
    { type: "p", text: "A broad VPN model often looks like this: user, VPN, network, app. Private Access can look like this: user, policy, app, private connector." },
    { type: "p", text: "The second model can reduce the size of the trust boundary. A user can get access to one app without getting a path to every server on the subnet." },
    { type: "h2", id: "core-parts", text: "The core parts" },
    { type: "ul", items: ["A private network connector group.", "A Global Secure Access app.", "Application segments for private destinations.", "User or group assignments.", "Conditional Access policies.", "The Global Secure Access client."] },
    { type: "h2", id: "setup", text: "Basic setup" },
    { type: "ol", items: ["Create or confirm a connector group.", "Make sure an active private network connector is available.", "Create the private application.", "Add the app's FQDNs or IP ranges.", "Assign users or groups.", "Set Conditional Access rules.", "Enable the Private Access traffic profile.", "Test from a managed client."] },
    { type: "h2", id: "segments", text: "Use narrow application segments" },
    { type: "p", text: "An application segment should describe the resource the app needs. Avoid adding a large network range when a small range or FQDN is enough." },
    { type: "p", text: "Microsoft documents up to 500 application segments for an Enterprise app. It also documents rules for overlapping segments. Smaller segments are easier to reason about." },
    { type: "h2", id: "conditional-access", text: "Add Conditional Access" },
    { type: "p", text: "Per-app access is not the end of the security model. Conditional Access can add identity and device checks. Use it when the app needs stronger controls." },
    { type: "callout", variant: "tip", title: "Start with one app", text: "Pick one internal app with a clear owner. Test it from one pilot group before you move a whole VPN population." },
    { type: "h2", id: "vpn-migration", text: "Use Quick Access as a bridge" },
    { type: "p", text: "Microsoft documents Quick Access as a transition phase for VPN replacement. The longer term model is per-app access, because it gives more granular control." },
    { type: "h2", id: "operations", text: "Operate the service" },
    { type: "p", text: "Give every private app an owner. Track its connector group. Track its users. Review its Conditional Access policy. Remove old segments when the app changes." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Replacing the VPN with one huge private range.", "Skipping Conditional Access.", "Adding overlapping segments without a plan.", "Testing only from one network.", "Leaving old VPN routes in place without an exit plan."] },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "Private Access is useful when the goal is more than remote connectivity. It can make access smaller, clearer, and easier to tie to identity. Start with one app. Prove the model. Then migrate in rings." },
  ],
  faq: [
    { question: "Does Private Access replace every VPN use case?", answer: "It can replace many private application access cases, but each application and protocol must be tested. Microsoft documents Private Access as a Zero Trust access solution for private resources." },
    { question: "What is an application segment?", answer: "It defines the FQDN, IP address, IP range, or port scope used for a private application." },
    { question: "Can Conditional Access protect a Private Access app?", answer: "Yes. Microsoft documents Conditional Access policies for Private Access applications." },
  ],
  sources: [
    { title: "Quickstart: Configure per-app access to private resources", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/global-secure-access/quickstart-per-app-access" },
    { title: "Configure per-app access using Global Secure Access applications", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-configure-per-app-access" },
    { title: "Quickstart: Configure Quick Access to private resources", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/global-secure-access/quickstart-quick-access" },
  ],
};
