import type { Article } from "../../types";

export const article: Article = {
  slug: "entra-id-governance-lifecycle",
  category: "microsoft-entra",
  contentType: "decision-framework",
  subcategory: "Identity Governance",
  title: "Microsoft Entra ID Governance: build an access lifecycle",
  seoTitle: "Microsoft Entra ID Governance: Build an Access Lifecycle",
  metaDescription: "A practical Microsoft Entra identity governance model for joiners, movers, leavers, access packages, reviews, and privileged access.",
  standfirst: "Good identity governance follows the user. Access should change when the user's work changes.",
  excerpt: "Connect lifecycle, access packages, access reviews, and PIM into one identity governance process.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 7,
  primaryKeyword: "Microsoft Entra ID Governance",
  secondaryKeywords: ["joiner mover leaver", "access packages", "access reviews", "PIM", "identity lifecycle"],
  tags: ["Microsoft Entra", "Identity Governance", "Security", "Lifecycle"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Microsoft Entra ID Governance, PIM, and access reviews. The article presents a practical operating model and marks recommendations as such.",
  body: [
    { type: "p", text: "Identity governance starts with a simple idea. Access should follow the user's work." },
    { type: "p", text: "A new employee needs access. A person who changes role needs different access. A person who leaves needs access removed. Privileged access needs extra control." },
    { type: "h2", id: "the-lifecycle", text: "The access lifecycle" },
    { type: "ol", items: ["Joiner: give the right starting access.", "Mover: change access when the role changes.", "Leaver: remove access when work ends.", "Reviewer: check access on a schedule.", "Privileged user: give admin access only when needed."] },
    { type: "h2", id: "access-packages", text: "Use access packages for business access" },
    { type: "p", text: "Access packages can bundle access for a business need. They can make a request easier to manage than many separate grants." },
    { type: "p", text: "Use a package when a group of resources belongs to one clear business purpose. Give the package an owner. Define who can request it and how long access should last." },
    { type: "h2", id: "access-reviews", text: "Use access reviews for cleanup" },
    { type: "p", text: "Access packages and groups can still collect old assignments. Access reviews add a regular check. Reviewers can confirm access or remove it when the business need is gone." },
    { type: "h2", id: "pim", text: "Use PIM for privileged access" },
    { type: "p", text: "Privileged Identity Management adds time based and approval based activation. A user can be eligible for a role without holding the role all the time." },
    { type: "p", text: "This reduces standing privilege. It also creates a record of activation, reason, and approval when those controls are enabled." },
    { type: "h2", id: "joiner", text: "Joiner design" },
    { type: "p", text: "A joiner flow should start with a known identity source. Then map the user's job data to the access needed for the role. Keep exceptions small and visible." },
    { type: "h2", id: "mover", text: "Mover design" },
    { type: "p", text: "Movers are harder than joiners. New access is often added, but old access is not always removed. Make role changes trigger a review of old access." },
    { type: "h2", id: "leaver", text: "Leaver design" },
    { type: "p", text: "A leaver flow should remove access fast. Disable the account. Remove active sessions where required. Remove group and app access. Keep the records needed for audit." },
    { type: "h2", id: "operating-model", text: "A simple operating model" },
    { type: "table", caption: "A practical governance split", head: ["Need", "Control"], rows: [["Starting access", "Lifecycle and access packages"], ["Business access", "Access packages"], ["Stale access", "Access reviews"], ["Admin access", "PIM"], ["Audit", "Logs and review history"]] },
    { type: "callout", variant: "tip", title: "Name an owner", text: "Every access package, sensitive group, and privileged role should have a clear business or security owner." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Using groups as the only governance tool.", "Adding access without an expiry model.", "Ignoring movers.", "Keeping permanent admin roles.", "Running reviews but not applying the results."] },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "Identity governance works when controls connect. Lifecycle data starts the process. Access packages organize business access. Reviews remove stale access. PIM controls privilege. Together they create a repeatable access lifecycle." },
  ],
  faq: [
    { question: "What is Microsoft Entra ID Governance?", answer: "It is a set of Microsoft Entra capabilities for managing identity access across the lifecycle, including access packages, access reviews, and privileged access controls." },
    { question: "What is a mover in identity governance?", answer: "A mover is a user whose job or role changes. The access lifecycle should add needed access and remove access that is no longer needed." },
    { question: "Where does PIM fit?", answer: "PIM controls privileged access by using eligible assignments, activation, time limits, approval, MFA, and audit features." },
  ],
  sources: [
    { title: "Microsoft Entra ID Governance overview", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/identity-governance-overview" },
    { title: "What is Privileged Identity Management?", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-configure" },
    { title: "Plan an access reviews deployment", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/deploy-access-reviews" },
  ],
};
