import type { Article } from "../../types";

export const article: Article = {
  slug: "entra-access-reviews-stale-access",
  category: "microsoft-entra",
  contentType: "how-to",
  subcategory: "Identity Governance",
  title: "Microsoft Entra access reviews: stop stale access",
  seoTitle: "Microsoft Entra Access Reviews: Stop Stale Access",
  metaDescription: "A clear guide to Microsoft Entra access reviews for groups, apps, guests, and privileged roles.",
  standfirst: "Access changes over time. Reviews help you remove access that people no longer need.",
  excerpt: "Use Microsoft Entra access reviews to check group, app, guest, and role access on a set schedule.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 6,
  primaryKeyword: "Microsoft Entra access reviews",
  secondaryKeywords: ["stale access", "identity governance", "guest access reviews", "group access review"],
  tags: ["Microsoft Entra", "Identity Governance", "Security", "Zero Trust"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Microsoft Entra access reviews. Product behavior and review scope are based on the cited Microsoft sources.",
  body: [
    { type: "p", text: "Access is not static. People change jobs. Projects end. Guests leave. Groups grow. Old access can stay behind." },
    { type: "p", text: "Microsoft Entra access reviews help check that access still makes sense. You can review group members, app access, guests, access packages, and privileged roles. Microsoft recommends periodic reviews to reduce stale access. " },
    { type: "h2", id: "why-reviews-matter", text: "Why reviews matter" },
    { type: "p", text: "An access grant can be correct on day one. It can be wrong six months later. A review adds a human check. The reviewer asks one simple question: does this person still need this access?" },
    { type: "p", text: "This is different from a sign-in check. A user can be active and still have access they no longer need. A user can also be in a group that no longer matches the user's job." },
    { type: "h2", id: "what-you-can-review", text: "What you can review" },
    { type: "ul", items: ["Group members and group access.", "User access to applications.", "Guest user access.", "Access package assignments.", "Privileged role assignments."] },
    { type: "p", text: "Microsoft documents access reviews for groups and apps. It also documents reviews for access packages and privileged roles. The exact options depend on the resource and license in use." },
    { type: "h2", id: "simple-review-model", text: "A simple review model" },
    { type: "ol", items: ["List the access that needs review.", "Choose a reviewer who knows the business need.", "Set a review period.", "Ask the reviewer to approve or remove access.", "Apply the results.", "Keep the review record for audit work."] },
    { type: "p", text: "A review works best when the reviewer can make a clear choice. Give the reviewer enough context. Avoid huge lists with no owner." },
    { type: "callout", variant: "tip", title: "Start with high value access", text: "Review privileged roles, sensitive apps, finance groups, and guest access first. Then expand the review model." },
    { type: "h2", id: "guest-access", text: "Guest access needs special care" },
    { type: "p", text: "Guest access often lasts longer than the project that created it. A guest may still be active. That does not prove that access is still needed." },
    { type: "p", text: "Set a clear owner for guest reviews. Use a review cycle that matches the risk. A sensitive app may need a shorter cycle than a low risk collaboration group." },
    { type: "h2", id: "privileged-access", text: "Privileged access" },
    { type: "p", text: "Admin roles deserve a stronger review model. Microsoft recommends recurring checks for privileged roles. PIM can add just in time access, while access reviews check whether the role is still needed." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Making one person review every resource.", "Running reviews but not applying the result.", "Reviewing normal access while ignoring privileged access.", "Using a review cycle that is too long for the risk.", "Keeping no owner for the access decision."] },
    { type: "h2", id: "practical-model", text: "A practical enterprise model" },
    { type: "p", text: "Use three layers. Review high risk access often. Review normal business access on a set cycle. Review guests before project access expires." },
    { type: "p", text: "Keep the process simple. The goal is not more review work. The goal is less stale access." },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "Access reviews turn access cleanup into a repeatable process. They help catch old group membership, app access, guest access, and privileged roles. Use them with PIM and lifecycle controls for a stronger identity governance model." },
  ],
  faq: [
    { question: "What is a Microsoft Entra access review?", answer: "It is a scheduled review that asks people to confirm whether users or guests still need access to a resource." },
    { question: "Can access reviews cover guest users?", answer: "Yes. Microsoft documents access reviews for guest users and other access types." },
    { question: "Should privileged roles be reviewed?", answer: "Yes. Microsoft recommends recurring reviews for privileged role assignments." },
  ],
  sources: [
    { title: "Plan an access reviews deployment", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/deploy-access-reviews" },
    { title: "Create an access review of groups and applications", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/create-access-review" },
    { title: "Manage user and guest user access with access reviews", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/id-governance/manage-access-review" },
  ],
};
