import type { Article } from "../../types";

export const article: Article = {
  slug: "entra-authentication-strengths",
  category: "microsoft-entra",
  contentType: "decision-framework",
  subcategory: "Conditional Access",
  title: "Microsoft Entra authentication strengths: choose stronger MFA",
  seoTitle: "Microsoft Entra Authentication Strengths: Stronger MFA",
  metaDescription: "How Microsoft Entra authentication strengths use Conditional Access to require the right MFA methods for each risk level.",
  standfirst: "MFA is not one thing. Authentication strengths let you choose which methods can satisfy a policy.",
  excerpt: "Use authentication strengths to require normal, passwordless, or phishing-resistant MFA where it matters.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 6,
  primaryKeyword: "Microsoft Entra authentication strengths",
  secondaryKeywords: ["phishing-resistant MFA", "passwordless MFA", "Conditional Access", "custom authentication strength"],
  tags: ["Microsoft Entra", "Conditional Access", "MFA", "Identity Security"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Conditional Access authentication strengths. Built-in and custom strength behavior is based on the cited Microsoft sources.",
  body: [
    { type: "p", text: "MFA adds a second check. But MFA methods do not all have the same strength." },
    { type: "p", text: "Microsoft Entra authentication strengths let Conditional Access require a set of allowed MFA methods. Microsoft provides built-in strengths and supports custom strengths. " },
    { type: "h2", id: "built-in", text: "The built-in strengths" },
    { type: "ul", items: ["Multifactor authentication strength.", "Passwordless MFA strength.", "Phishing-resistant MFA strength."] },
    { type: "p", text: "The phishing-resistant strength is the most restrictive built-in option. The exact methods that can satisfy a strength depend on the policy and configuration." },
    { type: "h2", id: "why-strength", text: "Why strength matters" },
    { type: "p", text: "A text code can help stop some attacks. It does not give the same phishing resistance as a suitable passkey or security key." },
    { type: "p", text: "A useful policy asks more than: did MFA happen? It asks: did an allowed method happen?" },
    { type: "h2", id: "custom", text: "Use custom strengths when needed" },
    { type: "p", text: "Microsoft supports custom authentication strengths. They can define the methods that meet a specific policy need." },
    { type: "h2", id: "policy-model", text: "Match strength to risk" },
    { type: "table", caption: "Example policy model", head: ["Use case", "Example strength"], rows: [["Normal app", "MFA strength"], ["Sensitive app", "Passwordless MFA"], ["Admin access", "Phishing-resistant MFA"]] },
    { type: "p", text: "This is an example design. It is not a Microsoft default. Test the user impact before you enforce it." },
    { type: "h2", id: "external-users", text: "External users" },
    { type: "p", text: "Authentication strength can also protect external access. Microsoft documents policies that require a selected MFA strength for guests and external users." },
    { type: "h2", id: "rollout", text: "Roll out in stages" },
    { type: "ol", items: ["List sensitive apps and roles.", "Check current MFA methods.", "Create the strength policy.", "Test with a pilot.", "Review sign in results.", "Enforce in rings."] },
    { type: "callout", variant: "tip", title: "Start with admins", text: "Privileged access is a good place to test phishing-resistant authentication because the risk is high and the user group is small." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Treating every MFA method as equal.", "Requiring phishing-resistant MFA before checking device support.", "Applying one strength to every app.", "Ignoring external user flows.", "Changing policy for everyone at once."] },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "Authentication strength gives Conditional Access more control. Use it to match the sign in method to the risk. Start with sensitive access. Test. Then expand." },
  ],
  faq: [
    { question: "What is an authentication strength?", answer: "It is a Conditional Access control that defines which combinations of authentication methods can satisfy an access policy." },
    { question: "What built-in strengths does Microsoft Entra provide?", answer: "Microsoft documents MFA, passwordless MFA, and phishing-resistant MFA as built-in authentication strengths." },
    { question: "Can I create a custom authentication strength?", answer: "Yes. Microsoft documents custom authentication strengths for specific policy needs." },
  ],
  sources: [
    { title: "Require multifactor authentication strength for external users", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/identity/conditional-access/policy-guests-mfa-strength" },
    { title: "Create and manage custom Conditional Access authentication strengths", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-strength-advanced-options" },
  ],
};
