import type { Article } from "../../types";

export const article: Article = {
  slug: "global-secure-access-traffic-profiles",
  category: "microsoft-entra",
  contentType: "reference",
  subcategory: "Global Secure Access",
  title: "Microsoft Global Secure Access traffic profiles: a simple routing model",
  seoTitle: "Global Secure Access Traffic Profiles Explained",
  metaDescription: "A simple guide to Microsoft Global Secure Access Microsoft, Private, and Internet traffic profiles.",
  standfirst: "Three traffic types serve three jobs. Keep their roles clear and your routing model stays easier to manage.",
  excerpt: "Understand Microsoft, Private Access, and Internet Access profiles before you build routing rules.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 6,
  primaryKeyword: "Global Secure Access traffic profiles",
  secondaryKeywords: ["Microsoft traffic profile", "Private Access profile", "Internet Access profile", "Global Secure Access"],
  tags: ["Microsoft Entra", "Global Secure Access", "Networking", "Zero Trust"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Global Secure Access traffic profiles. The traffic roles and routing behavior are based on the cited Microsoft sources.",
  body: [
    { type: "p", text: "Global Secure Access uses traffic profiles to decide which traffic the client should acquire. The main profiles are Microsoft traffic, Private Access, and Internet Access." },
    { type: "p", text: "Each profile has a clear job. Keeping those jobs clear helps prevent bad routing and hard to debug policy conflicts." },
    { type: "h2", id: "three-profiles", text: "The three main profiles" },
    { type: "table", caption: "The documented traffic model", head: ["Profile", "Main traffic", "Purpose"], rows: [["Microsoft traffic", "Microsoft 365 and Entra services", "Optimized Microsoft service routing"], ["Private Access", "Internal resources", "Zero Trust access to private apps"], ["Internet Access", "Other internet traffic", "Web filtering and threat controls"]] },
    { type: "h2", id: "microsoft", text: "Microsoft traffic" },
    { type: "p", text: "Microsoft traffic is for supported Microsoft services. Microsoft documents optimized routing for supported Microsoft 365 and Entra traffic. It is not the same as Internet Access." },
    { type: "h2", id: "private", text: "Private Access" },
    { type: "p", text: "Private Access is for internal corporate resources. It supports a Zero Trust model for private apps without a legacy VPN." },
    { type: "h2", id: "internet", text: "Internet Access" },
    { type: "p", text: "Internet Access handles other internet traffic. Microsoft documents web filtering, threat protection, and TLS inspection as key functions." },
    { type: "h2", id: "why-separation", text: "Why separation matters" },
    { type: "p", text: "A clear profile model makes troubleshooting easier. If an app does not work, first ask which profile should own its traffic. Then check the rule that acquired it." },
    { type: "p", text: "Do not assume that one profile can safely handle every destination. Microsoft documents that traffic available for acquisition in the Microsoft profile is not acquired by Internet Access." },
    { type: "h2", id: "diagnostics", text: "Use client diagnostics" },
    { type: "p", text: "The Global Secure Access client has an Advanced Diagnostics view. The Forwarding profile tab shows active rules and their priority. Policy Tester can help identify the rule for a destination." },
    { type: "h2", id: "custom-profiles", text: "Custom Private Access profiles" },
    { type: "p", text: "Microsoft also documents custom Private Access traffic forwarding profiles. These can target different apps to different users or devices. Microsoft marks this custom profile feature as preview, so treat it with care in production." },
    { type: "callout", variant: "note", title: "Keep the default model simple", text: "Use custom profiles only when the default model cannot meet a real business need. Every extra rule adds another path to test." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Treating all traffic as internet traffic.", "Ignoring rule priority.", "Testing a route without checking the active profile.", "Creating many custom profiles too early.", "Forgetting that preview features can change."] },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "The profile model is simple. Microsoft traffic serves Microsoft services. Private Access serves private resources. Internet Access serves other internet traffic. Keep that split clear, then add detail only when needed." },
  ],
  faq: [
    { question: "What are the main Global Secure Access traffic profiles?", answer: "Microsoft documents Microsoft traffic, Private Access, and Internet Access profiles for different traffic types." },
    { question: "Does Internet Access handle Microsoft traffic?", answer: "No. Microsoft documents that traffic acquired by the Microsoft traffic profile is not routed through the Internet Access profile." },
    { question: "Can I create custom Private Access profiles?", answer: "Yes. Microsoft documents custom Private Access traffic forwarding profiles, but currently marks that feature as preview." },
  ],
  sources: [
    { title: "Enable the Microsoft traffic profile", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/global-secure-access/tutorial-microsoft-traffic-enable-profile" },
    { title: "Create a Private Access traffic forwarding profile", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-create-traffic-forwarding-profile" },
  ],
};
