import type { Segment } from "../types";

/**
 * AI for enterprise IT backlog.
 *
 * The operational counterpart to the `ai` segment, which explains how the
 * technology works. This segment covers running it inside an organisation:
 * obligations, inventory, agent integration and assistant governance.
 *
 * Boundary with `cybersecurity-ciso`: sec-91 owns AI governance *policy* — the
 * document employees are held to — and the prompt-injection security angle sits
 * there too. What lives here is the IT-operations side: what the law requires
 * and when, what is deployed, and how agents and assistants are integrated.
 */
export const segment: Segment = {
  name: "AI for enterprise IT",
  category: "ai-enterprise-it",
  topics: [
    // -------------------------------------------------------- Obligations
    {
      id: "aient-01",
      title: "Running AI systems in enterprise IT: obligations, inventory and ownership",
      category: "ai-enterprise-it",
      subcategory: "AI governance",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "enterprise ai systems it operations obligations",
      secondaryKeywords: ["ai system ownership it", "managing ai deployments enterprise"],
      updateClass: "volatile",
      pillar: "Running AI in enterprise IT",
      plannedSlug: "running-ai-systems-enterprise-it",
      plannedInternalLinks: ["aient-02", "aient-03", "aient-04"],
      requiredSources: [
        "Regulation (EU) 2024/1689 (AI Act) consolidated text",
        "NIST AI Risk Management Framework",
      ],
      notes:
        "Cluster anchor. Complements sec-91, which owns the employee-facing policy; this is the IT operating model.",
    },
    {
      id: "aient-02",
      title: "The EU AI Act in practice: what applies now and what was pushed back",
      category: "ai-enterprise-it",
      subcategory: "AI governance",
      contentType: "reference",
      searchIntent: "question",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "eu ai act obligations timeline 2026",
      secondaryKeywords: ["ai act high risk delayed", "article 50 transparency obligations"],
      updateClass: "volatile",
      pillarSlug: "running-ai-systems-enterprise-it",
      relatedTopics: ["aient-01", "aient-03"],
      articleSlug: "eu-ai-act-obligations-timeline",
      requiredSources: [
        "https://ai-act-service-desk.ec.europa.eu/en/ai-act/timeline/timeline-implementation-eu-ai-act",
        "Regulation (EU) 2024/1689 consolidated text",
      ],
      notes:
        "Verified Aug 2026 and widely reported wrongly. On 16 June 2026 the European Parliament approved amendments deferring most high-risk obligations: Annex III stand-alone systems to 2 December 2027, Annex I embedded systems to 2 August 2028. Article 50 transparency duties — chatbot disclosure, machine-readable marking of AI content, deepfake labelling — were NOT deferred and apply from 2 August 2026, with pre-existing systems given until 2 December 2026 for the watermarking duty. GPAI obligations took effect 2 August 2025; what began on 2 August 2026 is the Commission's enforcement toolkit. Highly volatile — reverify before every review.",
    },
    {
      id: "aient-03",
      title: "ISO/IEC 42001 and the NIST AI RMF: what each one is for",
      category: "ai-enterprise-it",
      subcategory: "AI governance",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "iso 42001 vs nist ai rmf",
      secondaryKeywords: ["ai management system certification", "ai risk framework adoption"],
      updateClass: "annual",
      pillarSlug: "running-ai-systems-enterprise-it",
      relatedTopics: ["aient-01", "aient-02"],
      requiredSources: [
        "ISO/IEC 42001 (publicly available scope and structure)",
        "NIST AI Risk Management Framework 1.0",
      ],
      notes:
        "Pairs with the existing ISO 27001 mapping article — same reader, adjacent problem. A strong cross-domain link.",
    },
    {
      id: "aient-04",
      title: "Building an AI system inventory before someone asks for one",
      category: "ai-enterprise-it",
      subcategory: "AI governance",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "ai system inventory register",
      secondaryKeywords: ["shadow ai discovery", "ai use case register"],
      updateClass: "annual",
      pillarSlug: "running-ai-systems-enterprise-it",
      relatedTopics: ["aient-01", "aient-02"],
      notes: "The practical artefact every obligation in aient-02 and aient-03 ends up requiring.",
    },

    // ------------------------------------------------------------- Agents
    {
      id: "aient-05",
      title: "AI agents and tool protocols in an enterprise estate",
      category: "ai-enterprise-it",
      subcategory: "Agents",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "enterprise ai agent integration architecture",
      secondaryKeywords: [
        "agent tool protocol enterprise",
        "connecting agents to internal systems",
      ],
      updateClass: "volatile",
      pillar: "AI agents and tool protocols",
      plannedSlug: "ai-agents-and-tool-protocols",
      plannedInternalLinks: ["aient-06", "aient-07", "aient-08"],
      diagramOpportunity:
        "An agent's path to an internal system, marking where identity is asserted, where authorisation is decided and where the action is logged.",
      notes:
        "Cluster anchor, and the owner of the existing ai-agents-it-operations draft (aient-06). Links across to ai-03 for the conceptual treatment of tool use.",
    },
    {
      id: "aient-06",
      title: "What AI agents can actually do in IT operations right now",
      category: "ai-enterprise-it",
      subcategory: "Agents",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "ai agents it operations",
      secondaryKeywords: ["AIOps reality", "agentic ai enterprise it"],
      updateClass: "volatile",
      pillarSlug: "ai-agents-and-tool-protocols",
      relatedTopics: ["aient-05", "aient-07"],
      articleSlug: "ai-agents-it-operations",
      notes: "Existing 319-word draft. Attaching it to aient-05 removes its orphan status.",
    },
    {
      id: "aient-07",
      title: "Model Context Protocol: what it standardises, and what changed in the 2026 revision",
      category: "ai-enterprise-it",
      subcategory: "Agents",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "model context protocol enterprise explained",
      secondaryKeywords: ["mcp stateless spec", "mcp server enterprise deployment"],
      updateClass: "volatile",
      pillarSlug: "ai-agents-and-tool-protocols",
      relatedTopics: ["aient-05", "aient-08"],
      articleSlug: "model-context-protocol-explained",
      requiredSources: [
        "https://modelcontextprotocol.io/specification/2026-07-28",
        "https://blog.modelcontextprotocol.io/posts/2026-07-28/",
      ],
      notes:
        "Verified Aug 2026: the current specification revision is 2026-07-28, released 28 July 2026, and it carries breaking changes. The headline change is a stateless protocol core — protocol-level sessions and the Mcp-Session-Id header are removed, so any instance behind ordinary HTTP load balancing can answer a request. Also adds multi round-trip requests, header-based routing, cacheable list results, authorisation hardening and a formal extensions framework. Highly volatile: the specification is dated and revises often.",
    },
    {
      id: "aient-08",
      title: "Securing an agent's access to internal systems",
      category: "ai-enterprise-it",
      subcategory: "Agents",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "securing ai agent tool access",
      secondaryKeywords: ["agent least privilege", "agent action audit trail"],
      updateClass: "volatile",
      pillarSlug: "ai-agents-and-tool-protocols",
      relatedTopics: ["aient-05", "aient-07", "itauto-03"],
      requiredSources: ["OWASP Top 10 for LLM Applications", "MCP authorisation specification"],
      notes:
        "Cross-domain link to itauto-03: an agent's permission model is the delegated-versus-application problem again, with a non-human principal.",
    },

    // -------------------------------------------------- Coding assistants
    {
      id: "aient-09",
      title: "AI coding assistants in a managed organisation",
      category: "ai-enterprise-it",
      subcategory: "Adoption",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "ai coding assistant governance organisation",
      secondaryKeywords: ["copilot enterprise controls", "code assistant data boundary"],
      updateClass: "volatile",
      pillar: "AI coding assistants",
      plannedSlug: "ai-coding-assistants-managed-org",
      plannedInternalLinks: ["aient-10", "aient-11", "aient-12"],
      notes: "Cluster anchor, and the owner of the existing ai-coding-assistants-enterprise draft.",
    },
    {
      id: "aient-10",
      title: "Rolling out an AI coding assistant across an engineering organisation",
      category: "ai-enterprise-it",
      subcategory: "Adoption",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P1",
      status: "DRAFT",
      targetKeyword: "ai coding assistant enterprise rollout",
      secondaryKeywords: ["developer ai tool adoption", "coding assistant measurement"],
      updateClass: "volatile",
      pillarSlug: "ai-coding-assistants-managed-org",
      relatedTopics: ["aient-09", "aient-12"],
      articleSlug: "ai-coding-assistants-enterprise",
      notes: "Existing 150-word draft. Attaching it to aient-09 removes its orphan status.",
    },
    {
      id: "aient-11",
      title: "Code provenance and licence exposure from generated code",
      category: "ai-enterprise-it",
      subcategory: "Adoption",
      contentType: "analysis",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "generated code licence provenance risk",
      secondaryKeywords: ["ai code copyright exposure", "code suggestion filter"],
      updateClass: "volatile",
      pillarSlug: "ai-coding-assistants-managed-org",
      relatedTopics: ["aient-09"],
      notes:
        "Must describe obligations and vendor indemnity terms, not give legal advice — the same constraint as software-03.",
    },
    {
      id: "aient-12",
      title: "Reviewing AI-generated code: what reviewers start missing",
      category: "ai-enterprise-it",
      subcategory: "Adoption",
      contentType: "analysis",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "reviewing ai generated code",
      secondaryKeywords: ["automation bias code review", "ai code quality review process"],
      updateClass: "annual",
      pillarSlug: "ai-coding-assistants-managed-org",
      relatedTopics: ["aient-09", "dev-16"],
      notes: "Cross-domain link to dev-16, which owns general code-review practice.",
    },
    {
      id: "aient-13",
      title: "An agent with tools is not a chatbot, and cannot be secured like one",
      category: "ai-enterprise-it",
      subcategory: "Agents",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "enterprise ai agents security",
      secondaryKeywords: ["prompt injection tool use", "rag data leakage"],
      requiredSources: [
        "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
        "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf",
      ],
      updateClass: "volatile",
      articleSlug: "enterprise-ai-agents-security-governance-reality",
      notes:
        "Refined from Qwen batch-002 article 5. Technically sound as drafted. Scoped deliberately to security and governance so it does not overlap ai-agents-it-operations, which covers capability; the two now link to each other. Emphasised indirect prompt injection through data the agent reads, which is the path the draft under-weighted.",
    },
  ],
};
