import type { Segment } from "../types";

/**
 * Cloud backlog.
 *
 * Azure-first by deliberate scoping — the publication's readers are a Microsoft
 * estate audience, and a cloud segment that tries to cover three hyperscalers
 * equally ends up shallow in all three. AWS and Google Cloud appear where a
 * genuine comparison changes a decision, not as parallel coverage.
 *
 * Sources: Microsoft Azure documentation and the Cloud Adoption Framework, AWS
 * Well-Architected, Google Cloud architecture framework, Kubernetes and
 * Terraform official documentation.
 */
export const segment: Segment = {
  name: "Cloud",
  category: "cloud",
  topics: [
    /* ---------------- Hub and pillars ---------------- */
    {
      id: "cloud-01",
      title: "Azure landing zones: what to decide before the first resource",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "azure landing zone",
      requiredSources: [
        "https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/",
        "https://learn.microsoft.com/azure/architecture/",
      ],
      updateClass: "annual",
      pillar: "Cloud",
      plannedSlug: "azure-landing-zones",
      plannedInternalLinks: ["cloud-identity-and-least-privilege", "cloud-cost-controls"],
      diagramOpportunity:
        "Management group, subscription and resource group topology, showing which decisions are expensive to reverse.",
      notes:
        "Subject hub. The value is the irreversibility ranking — subscription boundaries and naming are cheap now and painful later.",
    },
    {
      id: "cloud-02",
      title: "Cloud identity and least privilege at scale",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "cloud iam least privilege",
      requiredSources: [
        "https://learn.microsoft.com/entra/identity-platform/",
        "https://learn.microsoft.com/azure/role-based-access-control/",
      ],
      updateClass: "annual",
      pillar: "Cloud identity",
      plannedSlug: "cloud-identity-and-least-privilege",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity:
        "Workload identity federation: how a pipeline authenticates without a stored secret.",
      notes: "Cross-domain bridge to microsoft-365-entra-id and cybersecurity-ciso.",
    },
    {
      id: "cloud-03",
      title: "Cloud networking fundamentals",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "azure virtual network architecture",
      requiredSources: ["https://learn.microsoft.com/azure/virtual-network/"],
      updateClass: "annual",
      pillar: "Cloud networking",
      plannedSlug: "cloud-networking-fundamentals",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity: "Hub-and-spoke with private endpoints and controlled egress.",
    },
    {
      id: "cloud-04",
      title: "Cloud cost control that survives contact with engineering",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P0",
      status: "DRAFT",
      targetKeyword: "cloud cost controls finops",
      updateClass: "annual",
      pillar: "Cost and FinOps",
      plannedSlug: "cloud-cost-controls",
      pillarSlug: "azure-landing-zones",
      articleSlug: "cloud-cost-controls",
      notes:
        "Existing 161-word draft. Legitimate intent and a natural pillar — needs research and a real allocation model rather than generic advice.",
    },
    {
      id: "cloud-05",
      title: "Resilience patterns: choosing an RTO you can actually meet",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud disaster recovery rto rpo",
      requiredSources: ["https://learn.microsoft.com/azure/reliability/"],
      updateClass: "evergreen",
      pillar: "Resilience",
      plannedSlug: "cloud-resilience-patterns",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity: "DR patterns plotted against RTO, RPO and cost.",
    },

    /* ---------------- Supporting ---------------- */
    {
      id: "cloud-10",
      title: "Managed identities: removing secrets from cloud workloads",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "azure managed identity",
      updateClass: "annual",
      pillarSlug: "cloud-identity-and-least-privilege",
    },
    {
      id: "cloud-11",
      title: "Private endpoints and controlling egress",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure private endpoint egress control",
      updateClass: "annual",
      pillarSlug: "cloud-networking-fundamentals",
    },
    {
      id: "cloud-12",
      title: "Reserved capacity and savings plans: when commitment pays",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure reservations savings plan",
      updateClass: "volatile",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-13",
      title: "Cost allocation and showback that changes behaviour",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud cost allocation tagging",
      updateClass: "evergreen",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-14",
      title: "Policy as code: guardrails instead of review meetings",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure policy as code guardrails",
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
      notes: "Cross-domain: devops IaC cluster.",
    },
    {
      id: "cloud-15",
      title: "Cloud migration: rehost, replatform or rebuild",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud migration rehost replatform",
      updateClass: "evergreen",
      pillarSlug: "azure-landing-zones",
    },
    {
      id: "cloud-16",
      title: "Observability in the cloud: logs, metrics and traces",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud observability logs metrics traces",
      requiredSources: ["https://opentelemetry.io/docs/"],
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
      notes: "Cross-domain: devops observability cluster. Decide ownership before writing.",
    },
    {
      id: "cloud-17",
      title: "Multi-cloud: the costs nobody budgets for",
      category: "cloud",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "multi cloud strategy tradeoffs",
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
    },
    {
      id: "cloud-18",
      title: "Storage tiers and lifecycle policies",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "azure storage lifecycle tiers",
      updateClass: "annual",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-19",
      title: "Backup and restore in the cloud: what the SLA does not cover",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud backup responsibility model",
      updateClass: "annual",
      pillarSlug: "cloud-resilience-patterns",
      notes:
        "Cross-domain: cybersecurity-ciso immutable backup topic. Shared-responsibility angle.",
    },
  ],
};
