import type { Segment } from "../types";

/**
 * Cloud backlog.
 *
 * Azure-first by deliberate scoping — the publication's readers are a Microsoft
 * estate audience, and a cloud segment that tries to cover three hyperscalers
 * equally ends up shallow in all three. AWS and Google Cloud appear where a
 * genuine comparison changes a decision, not as parallel coverage.
 *
 * Sources: Microsoft Azure documentation and the Cloud Adoption Framework, AWS
 * Well-Architected, Google Cloud architecture framework, Kubernetes and
 * Terraform official documentation.
 */
export const segment: Segment = {
  name: "Cloud",
  category: "cloud",
  topics: [
    /* ---------------- Hub and pillars ---------------- */
    {
      id: "cloud-01",
      title: "Azure landing zones: what to decide before the first resource",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "azure landing zone",
      requiredSources: [
        "https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/",
        "https://learn.microsoft.com/azure/architecture/",
      ],
      updateClass: "annual",
      pillar: "Cloud",
      plannedSlug: "azure-landing-zones",
      plannedInternalLinks: ["cloud-identity-and-least-privilege", "cloud-cost-controls"],
      diagramOpportunity:
        "Management group, subscription and resource group topology, showing which decisions are expensive to reverse.",
      notes:
        "Subject hub. The value is the irreversibility ranking — subscription boundaries and naming are cheap now and painful later.",
    },
    {
      id: "cloud-02",
      title: "Cloud identity and least privilege at scale",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "cloud iam least privilege",
      requiredSources: [
        "https://learn.microsoft.com/entra/identity-platform/",
        "https://learn.microsoft.com/azure/role-based-access-control/",
      ],
      updateClass: "annual",
      pillar: "Cloud identity",
      plannedSlug: "cloud-identity-and-least-privilege",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity:
        "Workload identity federation: how a pipeline authenticates without a stored secret.",
      notes: "Cross-domain bridge to microsoft-365-entra-id and cybersecurity-ciso.",
    },
    {
      id: "cloud-03",
      title: "Cloud networking fundamentals",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "azure virtual network architecture",
      requiredSources: ["https://learn.microsoft.com/azure/virtual-network/"],
      updateClass: "annual",
      pillar: "Cloud networking",
      plannedSlug: "cloud-networking-fundamentals",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity: "Hub-and-spoke with private endpoints and controlled egress.",
    },
    {
      id: "cloud-04",
      title: "Cloud cost control that survives contact with engineering",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "cloud cost controls finops",
      updateClass: "annual",
      pillar: "Cost and FinOps",
      plannedSlug: "cloud-cost-controls",
      pillarSlug: "azure-landing-zones",
      articleSlug: "cloud-cost-controls",
      notes:
        "Existing 161-word draft. Legitimate intent and a natural pillar — needs research and a real allocation model rather than generic advice.",
    },
    {
      id: "cloud-05",
      title: "Resilience patterns: choosing an RTO you can actually meet",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud disaster recovery rto rpo",
      requiredSources: ["https://learn.microsoft.com/azure/reliability/"],
      updateClass: "evergreen",
      pillar: "Resilience",
      plannedSlug: "cloud-resilience-patterns",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity: "DR patterns plotted against RTO, RPO and cost.",
    },

    /* ---------------- Supporting ---------------- */
    {
      id: "cloud-10",
      title: "Managed identities: removing secrets from cloud workloads",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "azure managed identity",
      updateClass: "annual",
      pillarSlug: "cloud-identity-and-least-privilege",
    },
    {
      id: "cloud-11",
      title: "Private endpoints and controlling egress",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure private endpoint egress control",
      updateClass: "annual",
      pillarSlug: "cloud-networking-fundamentals",
    },
    {
      id: "cloud-12",
      title: "Reserved capacity and savings plans: when commitment pays",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure reservations savings plan",
      updateClass: "volatile",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-13",
      title: "Cost allocation and showback that changes behaviour",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud cost allocation tagging",
      updateClass: "evergreen",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-14",
      title: "Policy as code: guardrails instead of review meetings",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure policy as code guardrails",
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
      notes: "Cross-domain: devops IaC cluster.",
    },
    {
      id: "cloud-15",
      title: "Cloud migration: rehost, replatform or rebuild",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud migration rehost replatform",
      updateClass: "evergreen",
      pillarSlug: "azure-landing-zones",
    },
    {
      id: "cloud-16",
      title: "Observability in the cloud: logs, metrics and traces",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud observability logs metrics traces",
      requiredSources: ["https://opentelemetry.io/docs/"],
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
      notes: "Cross-domain: devops observability cluster. Decide ownership before writing.",
    },
    {
      id: "cloud-17",
      title: "Multi-cloud: the costs nobody budgets for",
      category: "cloud",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "multi cloud strategy tradeoffs",
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
    },
    {
      id: "cloud-18",
      title: "Storage tiers and lifecycle policies",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "azure storage lifecycle tiers",
      updateClass: "annual",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-19",
      title: "Backup and restore in the cloud: what the SLA does not cover",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud backup responsibility model",
      updateClass: "annual",
      pillarSlug: "cloud-resilience-patterns",
      notes:
        "Cross-domain: cybersecurity-ciso immutable backup topic. Shared-responsibility angle.",
    },
    {
      id: "cloud-20",
      title: "Egress bills are an architecture problem wearing a finance costume",
      category: "cloud",
      subcategory: "Architecture",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "cloud egress costs",
      secondaryKeywords: ["nat gateway data processing charges", "cross-az data transfer cost"],
      requiredSources: [
        "https://aws.amazon.com/vpc/pricing/",
        "https://docs.aws.amazon.com/vpc/latest/privatelink/gateway-endpoints.html",
      ],
      updateClass: "annual",
      articleSlug: "cloud-egress-costs-architecture-problem",
      notes:
        "Refined from Qwen batch-002 article 1. Every rate, monthly figure and savings percentage in the draft was removed: they vary by region and contract, and the house methodology excludes them. Corrected the draft's conflation of gateway endpoints (S3 and DynamoDB, no endpoint charge) with interface endpoints (hourly plus per-GB), which reverses the economics of the advice.",
    },
    {
      id: "cloud-21",
      title: "VPC Lattice or API Gateway: the question is which way the traffic runs",
      category: "cloud",
      subcategory: "Architecture",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "aws vpc lattice vs api gateway",
      secondaryKeywords: ["east-west service networking aws", "vpc lattice auth policy"],
      requiredSources: [
        "https://docs.aws.amazon.com/vpc-lattice/latest/ug/what-is-vpc-lattice.html",
        "https://docs.aws.amazon.com/vpc-lattice/latest/ug/auth-policies.html",
      ],
      updateClass: "volatile",
      articleSlug: "aws-vpc-lattice-vs-api-gateway-service-networking",
      notes:
        "Refined from Qwen batch-003 article 1. Removed per-request pricing and a fabricated 50-100ms latency figure. The draft also gave the Lattice DNS format as a Kubernetes cluster.local name and described charging in ELB capacity units; both were wrong and are now described without inventing the specifics.",
    },
    {
      id: "cloud-22",
      title: "Peering does not scale, and the arithmetic says so",
      category: "cloud",
      subcategory: "Architecture",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "aws transit gateway vs vpc peering",
      secondaryKeywords: ["vpc peering limits", "transit gateway route tables"],
      requiredSources: [
        "https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html",
        "https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html",
      ],
      updateClass: "evergreen",
      articleSlug: "aws-transit-gateway-vs-vpc-peering",
      notes:
        "Refined from Qwen batch-004 article 1. Removed pricing and a self-contradictory peering quota claim. Dropped a reference to Transit Gateway multicast that the draft offered as a fix for stateful firewall asymmetry, which is unrelated; appliance mode is the actual answer. Scope is the network layer, deliberately distinct from cloud-21 which covers service-level routing.",
    },
    {
      id: "cloud-23",
      title: "Aurora Serverless v2 scales memory, and your connection limit rides along",
      category: "cloud",
      subcategory: "Database",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "aurora serverless v2 scaling",
      secondaryKeywords: ["aurora capacity units acu", "rds proxy connection pooling"],
      requiredSources: [
        "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html",
        "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html",
      ],
      updateClass: "volatile",
      articleSlug: "aurora-serverless-v2-scaling-connection-limits",
      notes:
        "Refined from Qwen batch-004 article 4, the most version-dependent draft in the batch. Its ACU-to-memory ratio, ACU ceiling and max_connections formula could not be confirmed and at least the ratio appeared wrong, so all capacity figures were removed and the article was written around the mechanism. The draft also asserted that v2 cannot scale to zero as a permanent property; minimum-capacity behaviour has changed since launch, so that is now flagged as version-dependent rather than stated.",
    },
    {
      id: "cloud-24",
      title: "A cold start has phases, and only one of them responds to more memory",
      category: "cloud",
      subcategory: "Serverless",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "aws lambda cold start",
      secondaryKeywords: ["lambda snapstart", "provisioned concurrency cost"],
      requiredSources: [
        "https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html",
        "https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html",
      ],
      updateClass: "volatile",
      articleSlug: "aws-lambda-cold-start-optimization-snapstart",
      notes:
        "Refined from Qwen batch-005 article 2. Removed all cold start timings. Two draft claims had gone stale and are now flagged as version-dependent rather than restated: SnapStart runtime support beyond Java, and the API Gateway timeout ceiling. Kept the frozen-random-seed warning, which is the most consequential SnapStart caveat and fails silently.",
    },
    {
      id: "cloud-25",
      title: "Postgres gives every connection a process, and that decides your architecture",
      category: "cloud",
      subcategory: "Database",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "postgresql connection pooling",
      secondaryKeywords: ["pgbouncer transaction pooling", "rds proxy pinning"],
      requiredSources: [
        "https://www.pgbouncer.org/config.html",
        "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html",
      ],
      updateClass: "evergreen",
      articleSlug: "postgresql-connection-pooling-pgbouncer-rds-proxy",
      notes:
        "Refined from Qwen batch-005 article 5. Removed per-connection memory figures, safe-connection-count rules of thumb and a latency figure. Added RDS Proxy pinning, which the draft missed and which is how that service degrades silently. The draft's claim about replication connections counting against max_connections is version-dependent, so it is flagged rather than stated. Boundary with cloud-23: that article owns capacity-linked connection ceilings, this one owns the process model and pooling modes.",
    },
    {
      id: "cloud-26",
      title: "The index exists. The planner ignores it anyway",
      category: "cloud",
      subcategory: "Database",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "postgresql index types",
      secondaryKeywords: ["gin vs gist", "brin index correlation", "jsonb_path_ops"],
      requiredSources: [
        "https://www.postgresql.org/docs/current/indexes-types.html",
        "https://www.postgresql.org/docs/current/gin.html",
        "https://www.postgresql.org/docs/current/brin.html",
        "https://www.postgresql.org/docs/current/datatype-json.html",
      ],
      updateClass: "evergreen",
      articleSlug: "postgresql-index-types-btree-gin-brin-gist",
      notes:
        "Written from a supplied draft rather than a Qwen batch. One documentation correction: the draft stated that jsonb_path_ops supports only the containment operator, when it also supports the jsonpath operators and excludes only key existence. Illustrative query timings and index sizes were removed — the draft labelled them illustrative, but the precision implied a measurement nobody took. The BRIN correlation threshold is kept and explicitly labelled a rule of thumb rather than a documented value. Boundary with cloud-25: that article owns connection behaviour, this one owns index selection.",
    },
    {
      id: "cloud-27",
      title: "Three ways to share files in AWS, and only one of them is really a file system",
      category: "cloud",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "AWS EFS vs FSx Lustre vs S3 Mountpoint",
      secondaryKeywords: [
        "AWS shared file storage",
        "EFS elastic throughput",
        "FSx for Lustre metadata",
      ],
      updateClass: "volatile",
      articleSlug: "aws-efs-vs-fsx-lustre-s3-mountpoint",
    },
    {
      id: "cloud-29",
      title: "Your function is fine. The account it lives in ran out of room",
      category: "cloud",
      subcategory: "Serverless",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "AWS Lambda concurrency reserved provisioned throttling",
      secondaryKeywords: [
        "Lambda requests per second limit",
        "concurrency scaling rate",
        "TooManyRequestsException",
      ],
      updateClass: "volatile",
      articleSlug: "aws-lambda-concurrency-reserved-provisioned-throttling",
    },
    {
      id: "cloud-32",
      title: "Vacuum reclaims space. Freezing is the part with a deadline",
      category: "cloud",
      subcategory: "Database",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "PostgreSQL autovacuum tuning wraparound",
      secondaryKeywords: [
        "autovacuum_freeze_max_age",
        "transaction ID wraparound",
        "vacuum_failsafe_age",
      ],
      updateClass: "annual",
      articleSlug: "postgresql-autovacuum-wraparound-freezing-tuning",
    },
    {
      id: "cloud-33",
      title: "The account boundary is the only AWS control an application cannot argue with",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "AWS Control Tower multi-account strategy",
      secondaryKeywords: [
        "AWS Organizations SCP",
        "service control policies",
        "resource control policies",
      ],
      updateClass: "annual",
      articleSlug: "aws-control-tower-multi-account-governance-scp",
    },
    {
      id: "cloud-34",
      title: "The secret you never created cannot leak",
      category: "cloud",
      subcategory: "Architecture",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Azure Managed Identities vs App Registrations",
      secondaryKeywords: [
        "Azure IMDS endpoint",
        "user-assigned managed identity",
        "Azure workload identity AKS",
      ],
      updateClass: "annual",
      articleSlug: "azure-managed-identities-vs-app-registrations-secrets",
    },
    {
      id: "cloud-35",
      title: "The database recovered in a minute. The application did not notice for fifteen",
      category: "cloud",
      subcategory: "Database",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "database connection failover mechanics",
      secondaryKeywords: [
        "TCP_USER_TIMEOUT database",
        "tcp_retries2 timeout",
        "half-open TCP connection",
      ],
      updateClass: "annual",
      articleSlug: "database-connection-failover-mechanics-timeouts",
    },
    {
      id: "cloud-36",
      title: "Two teams both picked 10.0.0.0/16, and the Transit Gateway quietly chose one",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "AWS VPC IPAM overlapping CIDR",
      secondaryKeywords: [
        "AWS IPAM pools",
        "VPC IPAM RAM sharing",
        "Transit Gateway overlapping CIDR",
      ],
      updateClass: "annual",
      articleSlug: "aws-vpc-ipam-overlapping-cidr-management",
    },
    {
      id: "cloud-37",
      title: "Your backup is only as good as the last WAL file that reached the archive",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "PostgreSQL PITR WAL archiving",
      secondaryKeywords: [
        "PostgreSQL log sequence number",
        "recovery_target_action",
        "archive_command failure",
      ],
      updateClass: "annual",
      articleSlug: "postgresql-pitr-wal-archiving-lsn-mechanics",
    },
    {
      id: "cloud-38",
      title:
        "A certificate your server already has can replace the AWS key it should never have had",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "AWS IAM Roles Anywhere certificate authentication",
      secondaryKeywords: [
        "IAM Roles Anywhere trust anchor",
        "X.509 workload authentication",
        "AWS Private CA",
      ],
      updateClass: "annual",
      articleSlug: "aws-iam-roles-anywhere-certificate-authentication",
    },
    {
      id: "cloud-39",
      title: "Partitioning only pays off if the planner can throw partitions away",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "PostgreSQL declarative partitioning",
      secondaryKeywords: [
        "partition pruning",
        "DETACH PARTITION CONCURRENTLY",
        "ATTACH PARTITION lock",
      ],
      updateClass: "volatile",
      articleSlug: "postgresql-declarative-partitioning-query-pruning",
    },
    {
      id: "cloud-40",
      title: "Sentinel keeps one dataset alive; Cluster splits it up. Those are different problems",
      category: "cloud",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Redis Cluster vs Sentinel architecture",
      secondaryKeywords: ["Redis hash slots", "Redis gossip protocol", "Redis split-brain"],
      updateClass: "volatile",
      articleSlug: "redis-cluster-vs-sentinel-architecture",
    },
    {
      id: "cloud-41",
      title: "A shard key you cannot split is a shard you cannot rebalance",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "MongoDB sharding jumbo chunk trap",
      secondaryKeywords: [
        "MongoDB shard key selection",
        "MongoDB balancer",
        "monotonic shard key hotspot",
      ],
      updateClass: "volatile",
      articleSlug: "mongodb-sharding-jumbo-chunk-trap",
    },
  ],
};
