import type { Segment } from "../types";

/**
 * Cloud backlog.
 *
 * Azure-first by deliberate scoping — the publication's readers are a Microsoft
 * estate audience, and a cloud segment that tries to cover three hyperscalers
 * equally ends up shallow in all three. AWS and Google Cloud appear where a
 * genuine comparison changes a decision, not as parallel coverage.
 *
 * Sources: Microsoft Azure documentation and the Cloud Adoption Framework, AWS
 * Well-Architected, Google Cloud architecture framework, Kubernetes and
 * Terraform official documentation.
 */
export const segment: Segment = {
  name: "Cloud",
  category: "cloud",
  topics: [
    /* ---------------- Hub and pillars ---------------- */
    {
      id: "cloud-01",
      title: "Azure landing zones: what to decide before the first resource",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "azure landing zone",
      requiredSources: [
        "https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/",
        "https://learn.microsoft.com/azure/architecture/",
      ],
      updateClass: "annual",
      pillar: "Cloud",
      plannedSlug: "azure-landing-zones",
      plannedInternalLinks: ["cloud-identity-and-least-privilege", "cloud-cost-controls"],
      diagramOpportunity:
        "Management group, subscription and resource group topology, showing which decisions are expensive to reverse.",
      notes:
        "Subject hub. The value is the irreversibility ranking — subscription boundaries and naming are cheap now and painful later.",
    },
    {
      id: "cloud-02",
      title: "Cloud identity and least privilege at scale",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "cloud iam least privilege",
      requiredSources: [
        "https://learn.microsoft.com/entra/identity-platform/",
        "https://learn.microsoft.com/azure/role-based-access-control/",
      ],
      updateClass: "annual",
      pillar: "Cloud identity",
      plannedSlug: "cloud-identity-and-least-privilege",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity:
        "Workload identity federation: how a pipeline authenticates without a stored secret.",
      notes: "Cross-domain bridge to microsoft-365-entra-id and cybersecurity-ciso.",
    },
    {
      id: "cloud-03",
      title: "Cloud networking fundamentals",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "azure virtual network architecture",
      requiredSources: ["https://learn.microsoft.com/azure/virtual-network/"],
      updateClass: "annual",
      pillar: "Cloud networking",
      plannedSlug: "cloud-networking-fundamentals",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity: "Hub-and-spoke with private endpoints and controlled egress.",
    },
    {
      id: "cloud-04",
      title: "Cloud cost control that survives contact with engineering",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "cloud cost controls finops",
      updateClass: "annual",
      pillar: "Cost and FinOps",
      plannedSlug: "cloud-cost-controls",
      pillarSlug: "azure-landing-zones",
      articleSlug: "cloud-cost-controls",
      notes:
        "Existing 161-word draft. Legitimate intent and a natural pillar — needs research and a real allocation model rather than generic advice.",
    },
    {
      id: "cloud-05",
      title: "Resilience patterns: choosing an RTO you can actually meet",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud disaster recovery rto rpo",
      requiredSources: ["https://learn.microsoft.com/azure/reliability/"],
      updateClass: "evergreen",
      pillar: "Resilience",
      plannedSlug: "cloud-resilience-patterns",
      pillarSlug: "azure-landing-zones",
      diagramOpportunity: "DR patterns plotted against RTO, RPO and cost.",
    },

    /* ---------------- Supporting ---------------- */
    {
      id: "cloud-10",
      title: "Managed identities: removing secrets from cloud workloads",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "azure managed identity",
      updateClass: "annual",
      pillarSlug: "cloud-identity-and-least-privilege",
    },
    {
      id: "cloud-11",
      title: "Private endpoints and controlling egress",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure private endpoint egress control",
      updateClass: "annual",
      pillarSlug: "cloud-networking-fundamentals",
    },
    {
      id: "cloud-12",
      title: "Reserved capacity and savings plans: when commitment pays",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure reservations savings plan",
      updateClass: "volatile",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-13",
      title: "Cost allocation and showback that changes behaviour",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud cost allocation tagging",
      updateClass: "evergreen",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-14",
      title: "Policy as code: guardrails instead of review meetings",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "azure policy as code guardrails",
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
      notes: "Cross-domain: devops IaC cluster.",
    },
    {
      id: "cloud-15",
      title: "Cloud migration: rehost, replatform or rebuild",
      category: "cloud",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud migration rehost replatform",
      updateClass: "evergreen",
      pillarSlug: "azure-landing-zones",
    },
    {
      id: "cloud-16",
      title: "Observability in the cloud: logs, metrics and traces",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud observability logs metrics traces",
      requiredSources: ["https://opentelemetry.io/docs/"],
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
      notes: "Cross-domain: devops observability cluster. Decide ownership before writing.",
    },
    {
      id: "cloud-17",
      title: "Multi-cloud: the costs nobody budgets for",
      category: "cloud",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "multi cloud strategy tradeoffs",
      updateClass: "annual",
      pillarSlug: "azure-landing-zones",
    },
    {
      id: "cloud-18",
      title: "Storage tiers and lifecycle policies",
      category: "cloud",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "azure storage lifecycle tiers",
      updateClass: "annual",
      pillarSlug: "cloud-cost-controls",
    },
    {
      id: "cloud-19",
      title: "Backup and restore in the cloud: what the SLA does not cover",
      category: "cloud",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud backup responsibility model",
      updateClass: "annual",
      pillarSlug: "cloud-resilience-patterns",
      notes:
        "Cross-domain: cybersecurity-ciso immutable backup topic. Shared-responsibility angle.",
    },
    {
      id: "cloud-20",
      title: "Egress bills are an architecture problem wearing a finance costume",
      category: "cloud",
      subcategory: "Architecture",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "cloud egress costs",
      secondaryKeywords: ["nat gateway data processing charges", "cross-az data transfer cost"],
      requiredSources: [
        "https://aws.amazon.com/vpc/pricing/",
        "https://docs.aws.amazon.com/vpc/latest/privatelink/gateway-endpoints.html",
      ],
      updateClass: "annual",
      articleSlug: "cloud-egress-costs-architecture-problem",
      notes:
        "Refined from Qwen batch-002 article 1. Every rate, monthly figure and savings percentage in the draft was removed: they vary by region and contract, and the house methodology excludes them. Corrected the draft's conflation of gateway endpoints (S3 and DynamoDB, no endpoint charge) with interface endpoints (hourly plus per-GB), which reverses the economics of the advice.",
    },
    {
      id: "cloud-21",
      title: "VPC Lattice or API Gateway: the question is which way the traffic runs",
      category: "cloud",
      subcategory: "Architecture",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "aws vpc lattice vs api gateway",
      secondaryKeywords: ["east-west service networking aws", "vpc lattice auth policy"],
      requiredSources: [
        "https://docs.aws.amazon.com/vpc-lattice/latest/ug/what-is-vpc-lattice.html",
        "https://docs.aws.amazon.com/vpc-lattice/latest/ug/auth-policies.html",
      ],
      updateClass: "volatile",
      articleSlug: "aws-vpc-lattice-vs-api-gateway-service-networking",
      notes:
        "Refined from Qwen batch-003 article 1. Removed per-request pricing and a fabricated 50-100ms latency figure. The draft also gave the Lattice DNS format as a Kubernetes cluster.local name and described charging in ELB capacity units; both were wrong and are now described without inventing the specifics.",
    },
    {
      id: "cloud-22",
      title: "Peering does not scale, and the arithmetic says so",
      category: "cloud",
      subcategory: "Architecture",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "aws transit gateway vs vpc peering",
      secondaryKeywords: ["vpc peering limits", "transit gateway route tables"],
      requiredSources: [
        "https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html",
        "https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html",
      ],
      updateClass: "evergreen",
      articleSlug: "aws-transit-gateway-vs-vpc-peering",
      notes:
        "Refined from Qwen batch-004 article 1. Removed pricing and a self-contradictory peering quota claim. Dropped a reference to Transit Gateway multicast that the draft offered as a fix for stateful firewall asymmetry, which is unrelated; appliance mode is the actual answer. Scope is the network layer, deliberately distinct from cloud-21 which covers service-level routing.",
    },
    {
      id: "cloud-23",
      title: "Aurora Serverless v2 scales memory, and your connection limit rides along",
      category: "cloud",
      subcategory: "Database",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "aurora serverless v2 scaling",
      secondaryKeywords: ["aurora capacity units acu", "rds proxy connection pooling"],
      requiredSources: [
        "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html",
        "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html",
      ],
      updateClass: "volatile",
      articleSlug: "aurora-serverless-v2-scaling-connection-limits",
      notes:
        "Refined from Qwen batch-004 article 4, the most version-dependent draft in the batch. Its ACU-to-memory ratio, ACU ceiling and max_connections formula could not be confirmed and at least the ratio appeared wrong, so all capacity figures were removed and the article was written around the mechanism. The draft also asserted that v2 cannot scale to zero as a permanent property; minimum-capacity behaviour has changed since launch, so that is now flagged as version-dependent rather than stated.",
    },
    {
      id: "cloud-24",
      title: "A cold start has phases, and only one of them responds to more memory",
      category: "cloud",
      subcategory: "Serverless",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "aws lambda cold start",
      secondaryKeywords: ["lambda snapstart", "provisioned concurrency cost"],
      requiredSources: [
        "https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html",
        "https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html",
      ],
      updateClass: "volatile",
      articleSlug: "aws-lambda-cold-start-optimization-snapstart",
      notes:
        "Refined from Qwen batch-005 article 2. Removed all cold start timings. Two draft claims had gone stale and are now flagged as version-dependent rather than restated: SnapStart runtime support beyond Java, and the API Gateway timeout ceiling. Kept the frozen-random-seed warning, which is the most consequential SnapStart caveat and fails silently.",
    },
    {
      id: "cloud-25",
      title: "Postgres gives every connection a process, and that decides your architecture",
      category: "cloud",
      subcategory: "Database",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "postgresql connection pooling",
      secondaryKeywords: ["pgbouncer transaction pooling", "rds proxy pinning"],
      requiredSources: [
        "https://www.pgbouncer.org/config.html",
        "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html",
      ],
      updateClass: "evergreen",
      articleSlug: "postgresql-connection-pooling-pgbouncer-rds-proxy",
      notes:
        "Refined from Qwen batch-005 article 5. Removed per-connection memory figures, safe-connection-count rules of thumb and a latency figure. Added RDS Proxy pinning, which the draft missed and which is how that service degrades silently. The draft's claim about replication connections counting against max_connections is version-dependent, so it is flagged rather than stated. Boundary with cloud-23: that article owns capacity-linked connection ceilings, this one owns the process model and pooling modes.",
    },
  ],
};
