import type { Segment } from "../types";

/**
 * Cybersecurity and security leadership backlog.
 *
 * Researched against NIST, CISA, CIS, OWASP, MITRE and Microsoft Security in
 * August 2026. Three currency findings shaped what is planned here:
 *
 * 1. NIST CSF 2.0 has six functions — Govern, Identify, Protect, Detect,
 *    Respond, Recover. Govern was added in the 2024 revision, the framework's
 *    first major update since 2014, and it is the change that matters most to a
 *    CISO audience.
 * 2. OWASP Top 10:2025 is current, superseding 2021. A01 Broken Access Control
 *    remains first; A03 Software Supply Chain Failures is new, expanded from
 *    A06:2021 Vulnerable and Outdated Components; Cryptographic Failures fell
 *    from second to fourth. A backlog planned around the 2021 list would be
 *    stale on arrival.
 * 3. CIS Controls v8.1 defines 153 Safeguards across three Implementation
 *    Groups — IG1 56, IG2 74, IG3 the remaining 23. IG1 is framed as essential
 *    cyber hygiene and is the practical on-ramp for most organisations.
 *
 * CSF 2.0 informs the structure without dictating it. Mirroring the six
 * functions as clusters would produce poor editorial boundaries — "Protect"
 * alone would swallow identity, endpoint, network and data security. The
 * clusters below follow how a practitioner actually specialises; CSF is used as
 * a mapping layer inside articles instead.
 */
export const segment: Segment = {
  name: "Cybersecurity / CISO",
  category: "cybersecurity-ciso",
  topics: [
    /* ---------------- Hub and cluster pillars ---------------- */
    {
      id: "sec-01",
      title: "Zero Trust for a Microsoft estate",
      category: "cybersecurity-ciso",
      subcategory: "Zero Trust",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "zero trust architecture microsoft",
      secondaryKeywords: ["zero trust principles", "zero trust implementation"],
      requiredSources: [
        "https://csrc.nist.gov/pubs/sp/800/207/final",
        "https://learn.microsoft.com/security/zero-trust/",
        "https://www.cisa.gov/zero-trust-maturity-model",
      ],
      updateClass: "evergreen",
      pillar: "Cybersecurity",
      plannedSlug: "zero-trust-for-a-microsoft-estate",
      plannedInternalLinks: [
        "identity-is-the-security-perimeter",
        "detection-and-response-architecture",
        "security-governance-and-frameworks",
        "conditional-access-framework",
      ],
      diagramOpportunity:
        "Zero Trust control plane: the signal sources (identity, device, network, workload), the policy decision point, and the enforcement points — showing where Intune and Entra each sit.",
      notes:
        "The subject hub. Must resist becoming a marketing definition: NIST SP 800-207 describes an architecture, and the useful article explains which parts an organisation can actually implement and in what order. Anchor for the whole segment.",
    },
    {
      id: "sec-02",
      title: "Identity is the security perimeter",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "identity security architecture",
      requiredSources: [
        "https://learn.microsoft.com/entra/identity/",
        "https://attack.mitre.org/tactics/TA0006/",
        "https://www.cisa.gov/resources-tools/resources/identity-and-access-management",
      ],
      updateClass: "annual",
      pillar: "Identity security",
      plannedSlug: "identity-is-the-security-perimeter",
      pillarSlug: "zero-trust-for-a-microsoft-estate",
      plannedInternalLinks: ["conditional-access-framework", "zero-trust-for-a-microsoft-estate"],
      diagramOpportunity:
        "Identity attack paths mapped to MITRE ATT&CK credential-access techniques, with the control that breaks each one.",
    },
    {
      id: "sec-03",
      title: "Detection and response architecture",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "detection and response architecture",
      requiredSources: [
        "https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-61r3.pdf",
        "https://attack.mitre.org/",
      ],
      updateClass: "annual",
      pillar: "Security operations",
      plannedSlug: "detection-and-response-architecture",
      pillarSlug: "zero-trust-for-a-microsoft-estate",
      diagramOpportunity:
        "Telemetry to case: sources, collection, normalisation, detection logic, triage, escalation — marking where signal is typically lost.",
    },
    {
      id: "sec-04",
      title: "Security governance and frameworks",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "security governance framework",
      requiredSources: [
        "https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf",
        "https://www.cisecurity.org/controls/v8-1",
      ],
      updateClass: "annual",
      pillar: "Governance and risk",
      plannedSlug: "security-governance-and-frameworks",
      pillarSlug: "zero-trust-for-a-microsoft-estate",
      diagramOpportunity:
        "How CSF 2.0, CIS Controls v8.1 and ISO 27001 overlap and where they genuinely differ, so a reader can pick one rather than adopting all three.",
      notes:
        "Must cover the Govern function properly — it is the substantive change in CSF 2.0 and the part a CISO is accountable for.",
    },
    {
      id: "sec-05",
      title: "Incident response readiness",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "RESEARCHED",
      targetKeyword: "incident response readiness",
      requiredSources: [
        "https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-61r3.pdf",
        "https://www.cisa.gov/topics/cyber-threats-and-advisories",
      ],
      updateClass: "annual",
      pillar: "Incident response",
      plannedSlug: "incident-response-readiness",
      pillarSlug: "zero-trust-for-a-microsoft-estate",
      diagramOpportunity:
        "Incident lifecycle against NIST SP 800-61r3, with the decisions that must be pre-agreed rather than made during an incident.",
    },

    /* ---------------- Zero Trust ---------------- */
    {
      id: "sec-10",
      title: "Zero Trust maturity: what to implement first",
      category: "cybersecurity-ciso",
      subcategory: "Zero Trust",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "zero trust maturity model",
      requiredSources: ["https://www.cisa.gov/zero-trust-maturity-model"],
      updateClass: "annual",
      pillarSlug: "zero-trust-for-a-microsoft-estate",
      relatedTopics: ["sec-01"],
    },
    {
      id: "sec-11",
      title: "Microsegmentation without breaking the business",
      category: "cybersecurity-ciso",
      subcategory: "Zero Trust",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "microsegmentation implementation",
      updateClass: "evergreen",
      pillarSlug: "zero-trust-for-a-microsoft-estate",
      relatedTopics: ["sec-01"],
      notes: "Cross-domain: pairs with the enterprise-networking segmentation cluster.",
    },
    {
      id: "sec-12",
      title: "Conditional Access as a Zero Trust policy engine",
      category: "cybersecurity-ciso",
      subcategory: "Zero Trust",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "conditional access zero trust policy engine",
      updateClass: "annual",
      pillarSlug: "identity-is-the-security-perimeter",
      plannedInternalLinks: ["conditional-access-framework"],
      notes:
        "Distinct from the Entra conditional-access-framework article, which is policy design. This is the architectural role CA plays as the policy decision point.",
    },

    /* ---------------- Identity security ---------------- */
    {
      id: "sec-20",
      title: "Phishing-resistant MFA: what actually qualifies",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "explainer",
      searchIntent: "decision",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "phishing resistant mfa",
      requiredSources: [
        "https://www.cisa.gov/resources-tools/resources/implementing-phishing-resistant-mfa",
        "https://pages.nist.gov/800-63-3/",
      ],
      updateClass: "annual",
      pillarSlug: "identity-is-the-security-perimeter",
      diagramOpportunity:
        "MFA methods ranked by what they resist — SMS through push through FIDO2 — showing which attack each one stops.",
    },
    {
      id: "sec-21",
      title: "Adversary-in-the-middle and token theft: the attacks MFA does not stop",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "analysis",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "token theft aitm attack",
      requiredSources: ["https://attack.mitre.org/techniques/T1550/"],
      updateClass: "annual",
      pillarSlug: "identity-is-the-security-perimeter",
      relatedTopics: ["sec-20"],
    },
    {
      id: "sec-22",
      title: "Privileged access management for a cloud estate",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "privileged access management cloud",
      updateClass: "annual",
      pillarSlug: "identity-is-the-security-perimeter",
    },
    {
      id: "sec-23",
      title: "Consent phishing and malicious OAuth applications",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "oauth consent phishing",
      updateClass: "annual",
      pillarSlug: "identity-is-the-security-perimeter",
      relatedTopics: ["sec-21"],
    },
    {
      id: "sec-24",
      title: "Service accounts and workload identity hygiene",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "service account security",
      updateClass: "evergreen",
      pillarSlug: "identity-is-the-security-perimeter",
    },

    /* ---------------- Endpoint security ---------------- */
    {
      id: "sec-30",
      title: "EDR, XDR and antivirus: what the categories actually mean",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "edr vs xdr vs antivirus",
      updateClass: "annual",
      pillarSlug: "detection-and-response-architecture",
      notes: "Vendor category inflation is the reason this is confusing. Say so plainly.",
    },
    {
      id: "sec-31",
      title: "Endpoint hardening: the controls that earn their operational cost",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "endpoint hardening priorities",
      requiredSources: ["https://www.cisecurity.org/cis-benchmarks"],
      updateClass: "annual",
      pillarSlug: "detection-and-response-architecture",
      notes: "Cross-domain: links to the Intune endpoint security pillar and to windows.",
    },

    /* ---------------- Application and supply chain ---------------- */
    {
      id: "sec-40",
      title: "OWASP Top 10:2025: what changed and why",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "reference",
      searchIntent: "question",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "owasp top 10 2025",
      requiredSources: ["https://owasp.org/Top10/2025/"],
      updateClass: "annual",
      pillarSlug: "security-governance-and-frameworks",
      diagramOpportunity:
        "2021 to 2025 category movement, showing the consolidation and the two new entries.",
      notes:
        "Verified August 2026: Top 10:2025 is current. A01 Broken Access Control remains first. A03 Software Supply Chain Failures is new, expanded from A06:2021 Vulnerable and Outdated Components. Cryptographic Failures moved from second to fourth. 248 CWEs across the ten categories. Cross-domain anchor for development.",
    },
    {
      id: "sec-41",
      title: "Software supply chain security: SBOM, provenance and what they prove",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "software supply chain security sbom",
      requiredSources: [
        "https://www.cisa.gov/sbom",
        "https://slsa.dev/spec/v1.0/",
        "https://owasp.org/Top10/2025/",
      ],
      updateClass: "annual",
      pillarSlug: "security-governance-and-frameworks",
      relatedTopics: ["sec-40"],
      notes: "Cross-domain: the shared anchor for development and devops supply-chain topics.",
    },
    {
      id: "sec-42",
      title: "Dependency risk: what pinning and lockfiles do not protect you from",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "analysis",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "dependency confusion supply chain attack",
      updateClass: "annual",
      pillarSlug: "security-governance-and-frameworks",
      relatedTopics: ["sec-41"],
      notes:
        "Overlaps software-04 in the software segment. Merge candidate — decide before either is written; do not publish both.",
    },

    /* ---------------- Data security and cryptography ---------------- */
    {
      id: "sec-50",
      title: "Data classification that people actually apply",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "data classification scheme",
      updateClass: "evergreen",
      pillarSlug: "security-governance-and-frameworks",
    },
    {
      id: "sec-51",
      title: "TLS, certificates and the trust chain, explained",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "how tls certificates work",
      requiredSources: [
        "https://datatracker.ietf.org/doc/html/rfc8446",
        "https://datatracker.ietf.org/doc/html/rfc5280",
      ],
      updateClass: "evergreen",
      pillarSlug: "identity-is-the-security-perimeter",
      diagramOpportunity:
        "TLS 1.3 handshake and the certificate chain validation that runs alongside it.",
      notes: "Cross-domain anchor for networking and development. Low volatility, high link value.",
    },
    {
      id: "sec-52",
      title: "Post-quantum cryptography: what to do before it matters",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "post quantum cryptography migration",
      requiredSources: ["https://csrc.nist.gov/projects/post-quantum-cryptography"],
      updateClass: "volatile",
      pillarSlug: "security-governance-and-frameworks",
      relatedTopics: ["sec-51"],
      notes: "Cross-domain: pairs with emerging-tech. Harvest-now-decrypt-later is the real hook.",
    },
    {
      id: "sec-53",
      title: "Secrets management: stopping credentials living in repositories",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "secrets management best practices",
      updateClass: "annual",
      pillarSlug: "security-governance-and-frameworks",
      notes: "Cross-domain: devops pipeline secrets.",
    },

    /* ---------------- Vulnerability management ---------------- */
    {
      id: "sec-60",
      title: "Vulnerability prioritisation: CVSS, EPSS and KEV together",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "vulnerability prioritisation cvss epss kev",
      requiredSources: [
        "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
        "https://www.first.org/epss/",
      ],
      updateClass: "annual",
      pillarSlug: "detection-and-response-architecture",
      diagramOpportunity:
        "Decision tree combining severity, exploit probability and known exploitation into one queue.",
      notes:
        "CVSS alone produces an unworkable backlog of criticals. The combination is the useful answer.",
    },
    {
      id: "sec-61",
      title: "Patch management that survives an emergency",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "emergency patch management process",
      updateClass: "evergreen",
      pillarSlug: "detection-and-response-architecture",
      relatedTopics: ["sec-60"],
      notes: "Cross-domain: Intune update rings and Autopatch are the delivery mechanism.",
    },

    /* ---------------- Incident response ---------------- */
    {
      id: "sec-70",
      title: "Ransomware: the controls that change the outcome",
      category: "cybersecurity-ciso",
      subcategory: "Resilience",
      contentType: "analysis",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "ransomware defence controls",
      requiredSources: ["https://www.cisa.gov/stopransomware"],
      updateClass: "annual",
      pillarSlug: "incident-response-readiness",
      diagramOpportunity:
        "Ransomware kill chain with the control that interrupts each stage, and the point after which only recovery helps.",
    },
    {
      id: "sec-71",
      title: "Tabletop exercises worth running",
      category: "cybersecurity-ciso",
      subcategory: "Resilience",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "security tabletop exercise",
      updateClass: "evergreen",
      pillarSlug: "incident-response-readiness",
    },
    {
      id: "sec-72",
      title: "Backup architecture that survives an attacker with admin rights",
      category: "cybersecurity-ciso",
      subcategory: "Resilience",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "immutable backup ransomware",
      updateClass: "evergreen",
      pillarSlug: "incident-response-readiness",
      relatedTopics: ["sec-70"],
      plannedInternalLinks: ["backup-restore-testing"],
      diagramOpportunity:
        "Backup topology showing which copies an attacker with domain admin can reach and which they cannot.",
      notes:
        "Direct parent for the existing backup-restore-testing draft, which currently has no cluster.",
    },

    /* ---------------- Governance, risk and compliance ---------------- */
    {
      id: "sec-80",
      title: "NIST CSF 2.0: the Govern function and what changed",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "reference",
      searchIntent: "question",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "nist csf 2.0 govern function",
      requiredSources: [
        "https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf",
        "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.1299.pdf",
      ],
      updateClass: "annual",
      pillarSlug: "security-governance-and-frameworks",
      diagramOpportunity: "The six functions and how Govern relates to the other five.",
      notes:
        "Verified August 2026: CSF 2.0 has six functions, Govern added in the 2024 revision — the first major update since the framework's 2014 creation. Govern is where risk strategy, expectations and policy are established and monitored.",
    },
    {
      id: "sec-81",
      title: "CIS Controls v8.1: starting with IG1",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "reference",
      searchIntent: "how-to",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "cis controls implementation group 1",
      requiredSources: [
        "https://www.cisecurity.org/controls/v8-1",
        "https://www.cisecurity.org/controls/implementation-groups/ig1",
      ],
      updateClass: "annual",
      pillarSlug: "security-governance-and-frameworks",
      relatedTopics: ["sec-80"],
      notes:
        "Verified August 2026: v8.1 defines 153 Safeguards. IG1 is 56 Safeguards and is framed as essential cyber hygiene; IG2 totals 74; IG3 adds the remaining 23. IG1 is the practical starting point and the article's spine.",
    },
    {
      id: "sec-82",
      title: "Reporting security risk to a board",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "board security risk reporting",
      updateClass: "evergreen",
      pillarSlug: "security-governance-and-frameworks",
      notes: "Cross-domain: the technology-leadership bridge.",
    },
    {
      id: "sec-83",
      title: "Third-party and vendor security assessment",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "third party security assessment",
      updateClass: "annual",
      pillarSlug: "security-governance-and-frameworks",
      relatedTopics: ["sec-41"],
    },

    /* ---------------- AI security ---------------- */
    {
      id: "sec-90",
      title: "Securing AI systems: prompt injection and data exfiltration",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "ai security prompt injection",
      requiredSources: [
        "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
        "https://www.nist.gov/itl/ai-risk-management-framework",
      ],
      updateClass: "volatile",
      pillarSlug: "zero-trust-for-a-microsoft-estate",
      diagramOpportunity:
        "Prompt-injection path through a retrieval-augmented system, showing where untrusted content becomes instruction.",
      notes:
        "Cross-domain anchor shared with the ai segment. One article, not two — the ai segment links here rather than duplicating it.",
    },
    {
      id: "sec-91",
      title: "AI governance: policy that survives contact with employees",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "enterprise ai governance policy",
      requiredSources: ["https://www.nist.gov/itl/ai-risk-management-framework"],
      updateClass: "volatile",
      pillarSlug: "security-governance-and-frameworks",
      relatedTopics: ["sec-90"],
      notes: "Cross-domain: pairs with ai-enterprise-it. Keep the split at policy versus rollout.",
    },

    /* ---------------- Email, mobile and cloud security ---------------- */
    {
      id: "sec-100",
      title: "Email authentication: SPF, DKIM and DMARC configured correctly",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "spf dkim dmarc configuration",
      requiredSources: [
        "https://datatracker.ietf.org/doc/html/rfc7489",
        "https://datatracker.ietf.org/doc/html/rfc7208",
      ],
      updateClass: "evergreen",
      pillarSlug: "detection-and-response-architecture",
      diagramOpportunity: "How a receiving server evaluates SPF, DKIM and DMARC in order.",
      notes:
        "Overlaps m365-43. Decide ownership before writing: this is the protocol explanation, m365-43 is the Exchange Online configuration.",
    },
    {
      id: "sec-101",
      title: "Mobile device security for a BYOD workforce",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "byod security policy",
      updateClass: "annual",
      pillarSlug: "zero-trust-for-a-microsoft-estate",
      plannedInternalLinks: ["smartphone-security-for-work"],
      notes:
        "Parent for the existing smartphone-security-for-work draft. Cross-domain: smartphones, microsoft-intune.",
    },
    {
      id: "sec-102",
      title: "Cloud security posture: what CSPM actually tells you",
      category: "cybersecurity-ciso",
      subcategory: "Security operations",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "cloud security posture management",
      updateClass: "annual",
      pillarSlug: "detection-and-response-architecture",
      notes: "Cross-domain: cloud governance cluster.",
    },
    {
      id: "sec-103",
      title: "ISO 27001 mapped to Microsoft 365 controls",
      category: "cybersecurity-ciso",
      subcategory: "Governance",
      contentType: "reference",
      searchIntent: "architecture",
      priority: "P1",
      status: "DRAFT",
      targetKeyword: "iso 27001 microsoft 365 mapping",
      updateClass: "annual",
      pillarSlug: "security-governance-and-frameworks",
      articleSlug: "iso-27001-microsoft-365-mapping",
      relatedTopics: ["sec-80", "sec-81"],
      notes:
        "Existing 287-word draft — the strongest of the stubs. Needs a full rewrite rather than expansion, and a decision on which Annex A revision it maps.",
    },
    {
      id: "sec-104",
      title: "Testing backups properly: a restore drill worth running",
      category: "cybersecurity-ciso",
      subcategory: "Resilience",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "DRAFT",
      targetKeyword: "backup restore testing procedure",
      updateClass: "evergreen",
      pillarSlug: "incident-response-readiness",
      articleSlug: "backup-restore-testing",
      relatedTopics: ["sec-72"],
      notes:
        "Existing 220-word draft. Legitimate intent; needs research and a real drill procedure.",
    },
    {
      id: "sec-105",
      title: "Team password managers: what to assess before standardising",
      category: "cybersecurity-ciso",
      subcategory: "Identity security",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P2",
      status: "DRAFT",
      targetKeyword: "team password manager selection criteria",
      updateClass: "annual",
      pillarSlug: "identity-is-the-security-perimeter",
      articleSlug: "password-managers-for-teams",
      notes:
        "Existing 191-word draft, reviewStatus research-based. Stays a decision-framework, not a review — no product was tested.",
    },
  ],
};
