import type { Segment } from "../types";

/**
 * Development backlog.
 *
 * Scoped deliberately to the practitioner's side of building software: how an
 * interface is designed and evolved, how a test suite stays trustworthy, how a
 * runtime's lifecycle is managed, and how a codebase stays workable.
 *
 * Software *security* is not here. `cybersecurity-ciso` already owns SBOM and
 * provenance (sec-41), dependency risk (sec-42) and the npm supply-chain
 * angle (software-04); duplicating them from a developer framing would split
 * the link graph for no editorial gain. Topics here link across to those
 * instead.
 */
export const segment: Segment = {
  name: "Development",
  category: "development",
  topics: [
    // ---------------------------------------------------------------- API
    {
      id: "dev-01",
      title: "Designing an API that can change without breaking its callers",
      category: "development",
      subcategory: "APIs",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "api design evolution backwards compatibility",
      secondaryKeywords: ["breaking change api", "api contract design"],
      updateClass: "evergreen",
      pillar: "API design and evolution",
      plannedSlug: "api-design-and-evolution",
      plannedInternalLinks: ["dev-02", "dev-03", "dev-04", "dev-05"],
      diagramOpportunity:
        "A single endpoint across three releases, showing which changes callers absorb silently and which break them.",
      requiredSources: [
        "RFC 9110 HTTP Semantics",
        "OpenAPI Specification",
        "Google API Improvement Proposals (AIP)",
      ],
      notes: "Cluster anchor. Must define compatibility precisely before the children specialise.",
    },
    {
      id: "dev-02",
      title: "REST, GraphQL or gRPC: choosing by traffic shape and client, not fashion",
      category: "development",
      subcategory: "APIs",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "rest vs graphql vs grpc",
      secondaryKeywords: ["when to use grpc", "graphql vs rest enterprise"],
      updateClass: "evergreen",
      pillarSlug: "api-design-and-evolution",
      relatedTopics: ["dev-01", "dev-05"],
      requiredSources: [
        "GraphQL Specification",
        "gRPC official documentation",
        "RFC 9110 HTTP Semantics",
      ],
    },
    {
      id: "dev-03",
      title: "API versioning: URI, header and field-level, and what each costs later",
      category: "development",
      subcategory: "APIs",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "api versioning strategy comparison",
      secondaryKeywords: ["url versioning vs header versioning", "deprecating an api version"],
      updateClass: "evergreen",
      pillarSlug: "api-design-and-evolution",
      relatedTopics: ["dev-01"],
      requiredSources: ["Google API Improvement Proposals (AIP-180 compatibility)", "RFC 9110"],
    },
    {
      id: "dev-04",
      title: "Idempotency and retries: making a client's second attempt safe",
      category: "development",
      subcategory: "APIs",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "idempotency key api retries",
      secondaryKeywords: ["safe retry http", "exactly once api"],
      updateClass: "evergreen",
      pillarSlug: "api-design-and-evolution",
      relatedTopics: ["dev-01"],
      requiredSources: ["RFC 9110 §9.2.2 Idempotent Methods", "IETF draft: Idempotency-Key header"],
      diagramOpportunity:
        "A retried POST with and without an idempotency key, showing where the duplicate is absorbed.",
    },
    {
      id: "dev-05",
      title: "Pagination and error contracts: the two things clients always get wrong",
      category: "development",
      subcategory: "APIs",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "cursor vs offset pagination api errors",
      secondaryKeywords: ["problem details rfc 9457", "api error response design"],
      updateClass: "evergreen",
      pillarSlug: "api-design-and-evolution",
      relatedTopics: ["dev-01", "dev-02"],
      requiredSources: ["RFC 9457 Problem Details for HTTP APIs", "RFC 9110"],
    },

    // ------------------------------------------------------------- Testing
    {
      id: "dev-06",
      title: "A testing strategy that survives a real codebase",
      category: "development",
      subcategory: "Testing",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "software testing strategy pyramid practice",
      secondaryKeywords: ["unit vs integration vs e2e", "test suite design"],
      updateClass: "evergreen",
      pillar: "Testing strategy",
      plannedSlug: "testing-strategy-real-codebase",
      plannedInternalLinks: ["dev-07", "dev-08", "dev-09", "dev-10"],
      diagramOpportunity:
        "Cost-to-write against confidence-gained for each test level, showing where the curve crosses.",
      requiredSources: ["Official documentation for the framework used in examples"],
      notes:
        "Cluster anchor. Argue from feedback latency and failure diagnosis, not the pyramid shape.",
    },
    {
      id: "dev-07",
      title: "Contract testing: catching integration breaks without a full environment",
      category: "development",
      subcategory: "Testing",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "consumer driven contract testing",
      secondaryKeywords: ["pact contract test", "service integration testing"],
      updateClass: "annual",
      pillarSlug: "testing-strategy-real-codebase",
      relatedTopics: ["dev-06", "dev-01"],
      requiredSources: ["Pact official documentation", "OpenAPI Specification"],
    },
    {
      id: "dev-08",
      title: "Flaky tests: finding the cause instead of adding a retry",
      category: "development",
      subcategory: "Testing",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "flaky test root cause fix",
      secondaryKeywords: ["intermittent test failure", "test retry anti-pattern"],
      updateClass: "evergreen",
      pillarSlug: "testing-strategy-real-codebase",
      relatedTopics: ["dev-06"],
      requiredSources: ["Test runner documentation for the examples used"],
      notes: "High-intent failure-mode query. The taxonomy of causes is the value here.",
    },
    {
      id: "dev-09",
      title: "Code coverage as a signal, not a target",
      category: "development",
      subcategory: "Testing",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "code coverage target percentage",
      secondaryKeywords: ["coverage gate ci", "mutation testing"],
      updateClass: "evergreen",
      pillarSlug: "testing-strategy-real-codebase",
      relatedTopics: ["dev-06"],
    },
    {
      id: "dev-10",
      title: "Test data: fixtures, factories and the production-copy trap",
      category: "development",
      subcategory: "Testing",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "test data management strategy",
      secondaryKeywords: ["test fixtures vs factories", "anonymised production data testing"],
      updateClass: "evergreen",
      pillarSlug: "testing-strategy-real-codebase",
      relatedTopics: ["dev-06"],
      notes: "Touches data protection; link across to the privacy angle rather than restating it.",
    },

    // ---------------------------------------------------- Runtime lifecycle
    {
      id: "dev-11",
      title: "Managing language runtime lifecycles before they manage you",
      category: "development",
      subcategory: "Languages",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "language runtime version lifecycle policy",
      secondaryKeywords: ["end of life runtime upgrade", "lts version policy"],
      updateClass: "annual",
      pillar: "Runtime lifecycle",
      plannedSlug: "language-runtime-lifecycle",
      plannedInternalLinks: ["dev-12", "dev-13", "dev-14"],
      requiredSources: [
        "Node.js release schedule (nodejs.org)",
        "Python developer guide version status",
        ".NET support policy",
      ],
      notes:
        "Cluster anchor. The argument is that upgrade cadence is a design decision, not an event.",
    },
    {
      id: "dev-12",
      title: "Node.js is changing how it releases: what the new schedule means for upgrades",
      category: "development",
      subcategory: "Languages",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "nodejs release schedule change lts",
      secondaryKeywords: ["node 26 lts", "node js version support 2026"],
      updateClass: "volatile",
      pillarSlug: "language-runtime-lifecycle",
      relatedTopics: ["dev-11", "dev-14"],
      articleSlug: "nodejs-release-schedule-change",
      requiredSources: [
        "https://nodejs.org/en/blog/announcements/evolving-the-nodejs-release-schedule",
        "https://nodejs.org/en/about/previous-releases",
      ],
      notes:
        "Verified Aug 2026: Node 24 is Active LTS, 22 Maintenance, 26 Current and entering LTS October 2026. Node 26 is the last release under the old model; from Node 27 there is one major per year, calendar-aligned numbering, every release becomes LTS, plus a new Alpha channel. Volatile — recheck at the October 2026 transition.",
    },
    {
      id: "dev-13",
      title: "Python version support: what actually blocks the upgrade",
      category: "development",
      subcategory: "Languages",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "python version upgrade blockers",
      secondaryKeywords: ["python end of life version", "python dependency compatibility upgrade"],
      updateClass: "annual",
      pillarSlug: "language-runtime-lifecycle",
      relatedTopics: ["dev-11"],
      requiredSources: ["Python Developer's Guide — status of Python versions", "PEP 602"],
    },
    {
      id: "dev-14",
      title: "Automated dependency updates without a permanent review queue",
      category: "development",
      subcategory: "Languages",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "renovate dependabot update strategy",
      secondaryKeywords: ["grouped dependency updates", "automerge dependency bot"],
      updateClass: "annual",
      pillarSlug: "language-runtime-lifecycle",
      relatedTopics: ["dev-11", "dev-12"],
      requiredSources: ["Renovate documentation", "GitHub Dependabot documentation"],
      notes:
        "Distinct from sec-42, which covers dependency *risk*. This is the operational cadence.",
    },

    // ------------------------------------------------------ Codebase health
    {
      id: "dev-15",
      title: "Keeping a codebase workable as the team changes",
      category: "development",
      subcategory: "Architecture",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "codebase maintainability practice",
      secondaryKeywords: ["legacy code strategy", "code health metrics"],
      updateClass: "evergreen",
      pillar: "Codebase health",
      plannedSlug: "codebase-health-and-review",
      plannedInternalLinks: ["dev-16", "dev-17", "dev-18"],
      notes: "Cluster anchor. Cross-links naturally to technology-leadership on team structure.",
    },
    {
      id: "dev-16",
      title: "Code review that finds defects rather than opinions",
      category: "development",
      subcategory: "Architecture",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "effective code review practice",
      secondaryKeywords: ["pull request review checklist", "review turnaround time"],
      updateClass: "evergreen",
      pillarSlug: "codebase-health-and-review",
      relatedTopics: ["dev-15"],
    },
    {
      id: "dev-17",
      title: "Technical debt: deciding what to repay and what to keep paying interest on",
      category: "development",
      subcategory: "Architecture",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "technical debt prioritisation framework",
      secondaryKeywords: ["when to refactor", "rewrite vs refactor decision"],
      updateClass: "evergreen",
      pillarSlug: "codebase-health-and-review",
      relatedTopics: ["dev-15"],
    },
    {
      id: "dev-18",
      title: "Monorepo or many repositories: the operational consequences",
      category: "development",
      subcategory: "Architecture",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "monorepo vs polyrepo tradeoffs",
      secondaryKeywords: ["monorepo build tooling", "repository strategy team"],
      updateClass: "evergreen",
      pillarSlug: "codebase-health-and-review",
      relatedTopics: ["dev-15"],
    },
  ],
};
