import type { Segment } from "../types";

/**
 * DevOps and platform backlog.
 *
 * Weighted towards decisions a platform team has to make and live with —
 * ingress, state, pipeline identity, base images — rather than tool tutorials,
 * which every project's own quickstart already covers better.
 *
 * The Gateway API cluster is the highest-priority work in this segment: the
 * `ingress-nginx` controller was archived in March 2026, which turns a
 * background modernisation into a dated migration with a security deadline.
 */
export const segment: Segment = {
  name: "DevOps / Platform",
  category: "devops",
  topics: [
    // -------------------------------------------------- Kubernetes ingress
    {
      id: "devops-01",
      title: "Kubernetes ingress after Ingress NGINX: the Gateway API transition",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "kubernetes gateway api transition ingress",
      secondaryKeywords: ["gateway api vs ingress", "kubernetes ingress replacement"],
      updateClass: "volatile",
      pillar: "Kubernetes ingress and Gateway API",
      plannedSlug: "kubernetes-gateway-api-transition",
      plannedInternalLinks: ["devops-02", "devops-03", "devops-04"],
      diagramOpportunity:
        "The Ingress single-resource model beside the Gateway API split of GatewayClass, Gateway and HTTPRoute, showing which team owns which object.",
      requiredSources: [
        "https://gateway-api.sigs.k8s.io/",
        "https://github.com/kubernetes/ingress-nginx",
        "https://kubernetes.io/blog/2026/03/20/ingress2gateway-1-0-release",
      ],
      notes:
        "Cluster anchor. The role separation between infrastructure and application teams is the real argument for Gateway API, not the feature list.",
    },
    {
      id: "devops-02",
      title: "Ingress NGINX is archived: what to do about it now",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "how-to",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "ingress nginx archived migration",
      secondaryKeywords: ["ingress-nginx end of life", "ingress nginx no security updates"],
      updateClass: "volatile",
      pillarSlug: "kubernetes-gateway-api-transition",
      relatedTopics: ["devops-01", "devops-03", "devops-04"],
      requiredSources: [
        "https://github.com/kubernetes/ingress-nginx",
        "https://github.com/kubernetes-sigs/ingress2gateway",
      ],
      notes:
        "Verified Aug 2026 from the repository itself: archived by the owner on 24 March 2026 and read-only. No further releases, bugfixes or security vulnerability updates. The project states that anyone not already using it should not deploy it, and directs users to pick a Gateway API implementation. This is an unpatched-component problem, not a preference question — frame it that way.",
    },
    {
      id: "devops-03",
      title: "The Gateway API resource model, and who owns each object",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "gateway api resource model httproute",
      secondaryKeywords: ["gatewayclass gateway httproute", "gateway api rbac separation"],
      updateClass: "volatile",
      pillarSlug: "kubernetes-gateway-api-transition",
      relatedTopics: ["devops-01"],
      requiredSources: ["https://gateway-api.sigs.k8s.io/api-types/gateway/"],
    },
    {
      id: "devops-04",
      title: "Choosing a Gateway API implementation without repeating the ingress mistake",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "gateway api implementation comparison",
      secondaryKeywords: ["conformance gateway api", "envoy gateway vs cilium vs istio"],
      updateClass: "volatile",
      pillarSlug: "kubernetes-gateway-api-transition",
      relatedTopics: ["devops-01", "devops-02"],
      requiredSources: ["https://gateway-api.sigs.k8s.io/implementations/"],
      notes: "Conformance level and governance model are the criteria that would have predicted the ingress-nginx outcome.",
    },

    // ------------------------------------------------------------------ IaC
    {
      id: "devops-05",
      title: "Infrastructure as code at team scale: what breaks after the first year",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "infrastructure as code team scale problems",
      secondaryKeywords: ["terraform module structure", "iac repository layout"],
      updateClass: "annual",
      pillar: "Infrastructure as code at scale",
      plannedSlug: "infrastructure-as-code-at-scale",
      plannedInternalLinks: ["devops-06", "devops-07", "devops-08", "devops-09"],
      notes: "Cluster anchor. Blast radius and state boundaries are the organising idea.",
    },
    {
      id: "devops-06",
      title: "Terraform or OpenTofu: a decision that is now about governance, not features",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "terraform vs opentofu decision",
      secondaryKeywords: ["opentofu migration", "terraform bsl licence enterprise"],
      updateClass: "volatile",
      pillarSlug: "infrastructure-as-code-at-scale",
      relatedTopics: ["devops-05", "devops-07"],
      requiredSources: [
        "https://opentofu.org/docs/",
        "https://developer.hashicorp.com/terraform/docs",
        "HashiCorp BUSL licence FAQ",
      ],
      notes:
        "Verified Aug 2026: Terraform moved from MPL 2.0 to BUSL 1.1 in August 2023; OpenTofu forked at 1.6, is MPL 2.0 and Linux Foundation governed, currently 1.12, and remains wire-compatible with Terraform providers and state. Terraform is now under IBM ownership. OpenTofu-only capabilities worth naming: native state and plan encryption, provider-level for_each, and the -exclude flag. Volatile — licence and ownership positions move.",
    },
    {
      id: "devops-07",
      title: "State files: locking, isolation and the blast radius of one apply",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "terraform state isolation locking",
      secondaryKeywords: ["remote state backend design", "state file splitting"],
      updateClass: "annual",
      pillarSlug: "infrastructure-as-code-at-scale",
      relatedTopics: ["devops-05", "devops-06"],
      requiredSources: ["Terraform state documentation", "OpenTofu state documentation"],
    },
    {
      id: "devops-08",
      title: "Configuration drift: detecting it before the next apply does",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "infrastructure drift detection",
      secondaryKeywords: ["terraform plan unexpected changes", "manual change cloud console"],
      updateClass: "annual",
      pillarSlug: "infrastructure-as-code-at-scale",
      relatedTopics: ["devops-05", "devops-07"],
    },
    {
      id: "devops-09",
      title: "Policy as code: guardrails that fail the plan rather than the audit",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "policy as code terraform opa",
      secondaryKeywords: ["conftest rego policy", "preventive cloud guardrails"],
      updateClass: "annual",
      pillarSlug: "infrastructure-as-code-at-scale",
      relatedTopics: ["devops-05"],
      requiredSources: ["Open Policy Agent documentation", "Conftest documentation"],
    },

    // -------------------------------------------------------- Pipeline security
    {
      id: "devops-10",
      title: "Pipeline security: the build system is production access",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "ci cd pipeline security model",
      secondaryKeywords: ["build system threat model", "pipeline privilege escalation"],
      updateClass: "annual",
      pillar: "Pipeline security",
      plannedSlug: "cicd-pipeline-security",
      plannedInternalLinks: ["devops-11", "devops-12", "devops-13"],
      diagramOpportunity:
        "The trust path from a pull request to a production credential, marking each point where an untrusted contributor can influence execution.",
      requiredSources: ["SLSA specification", "GitHub Actions security hardening documentation"],
      notes: "Cluster anchor. Links across to sec-41 for provenance rather than restating it.",
    },
    {
      id: "devops-11",
      title: "Workload identity federation: retiring long-lived cloud credentials from CI",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "oidc workload identity federation ci",
      secondaryKeywords: ["github actions oidc cloud", "remove static cloud keys pipeline"],
      updateClass: "annual",
      pillarSlug: "cicd-pipeline-security",
      relatedTopics: ["devops-10"],
      requiredSources: [
        "GitHub Actions OIDC documentation",
        "Microsoft Entra workload identity federation documentation",
      ],
    },
    {
      id: "devops-12",
      title: "Self-hosted runners: the isolation problem nobody budgets for",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "analysis",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "self hosted runner isolation security",
      secondaryKeywords: ["ephemeral ci runner", "runner escape risk"],
      updateClass: "annual",
      pillarSlug: "cicd-pipeline-security",
      relatedTopics: ["devops-10"],
      requiredSources: ["GitHub self-hosted runner security documentation"],
    },
    {
      id: "devops-13",
      title: "Signing what you ship: build provenance a consumer can verify",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "build provenance attestation signing",
      secondaryKeywords: ["sigstore cosign artifact", "slsa build level"],
      updateClass: "annual",
      pillarSlug: "cicd-pipeline-security",
      relatedTopics: ["devops-10"],
      requiredSources: ["SLSA specification", "Sigstore documentation"],
      notes: "Operational how-to. sec-41 owns what SBOM and provenance *prove*; do not repeat that argument.",
    },

    // ----------------------------------------------------------- Containers
    {
      id: "devops-14",
      title: "Container image strategy: what you inherit from the base image",
      category: "devops",
      subcategory: "Containers",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "container base image strategy",
      secondaryKeywords: ["image layer size", "container image lifecycle"],
      updateClass: "annual",
      pillar: "Container image strategy",
      plannedSlug: "container-image-strategy",
      plannedInternalLinks: ["devops-15", "devops-16"],
      requiredSources: ["Docker official documentation", "OCI Image Format Specification"],
      notes: "Cluster anchor.",
    },
    {
      id: "devops-15",
      title: "Distroless, Alpine or a full distribution: choosing a base image",
      category: "devops",
      subcategory: "Containers",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "distroless vs alpine base image",
      secondaryKeywords: ["musl glibc container issue", "minimal container image debugging"],
      updateClass: "annual",
      pillarSlug: "container-image-strategy",
      relatedTopics: ["devops-14"],
      requiredSources: ["Distroless project documentation", "Alpine Linux documentation"],
    },
    {
      id: "devops-16",
      title: "Image scanning: why the CVE count is not the risk",
      category: "devops",
      subcategory: "Containers",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "container image cve scanning noise",
      secondaryKeywords: ["reachable vulnerability container", "vex vulnerability exploitability"],
      updateClass: "annual",
      pillarSlug: "container-image-strategy",
      relatedTopics: ["devops-14", "devops-15"],
      requiredSources: ["OpenVEX specification", "Trivy documentation"],
    },
  ],
};
