import type { Segment } from "../types";

/**
 * DevOps and platform backlog.
 *
 * Weighted towards decisions a platform team has to make and live with —
 * ingress, state, pipeline identity, base images — rather than tool tutorials,
 * which every project's own quickstart already covers better.
 *
 * The Gateway API cluster is the highest-priority work in this segment: the
 * `ingress-nginx` controller was archived in March 2026, which turns a
 * background modernisation into a dated migration with a security deadline.
 */
export const segment: Segment = {
  name: "DevOps / Platform",
  category: "devops",
  topics: [
    // -------------------------------------------------- Kubernetes ingress
    {
      id: "devops-01",
      title: "Kubernetes ingress after Ingress NGINX: the Gateway API transition",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "kubernetes gateway api transition ingress",
      secondaryKeywords: ["gateway api vs ingress", "kubernetes ingress replacement"],
      updateClass: "volatile",
      pillar: "Kubernetes ingress and Gateway API",
      plannedSlug: "kubernetes-gateway-api-transition",
      plannedInternalLinks: ["devops-02", "devops-03", "devops-04"],
      diagramOpportunity:
        "The Ingress single-resource model beside the Gateway API split of GatewayClass, Gateway and HTTPRoute, showing which team owns which object.",
      requiredSources: [
        "https://gateway-api.sigs.k8s.io/",
        "https://github.com/kubernetes/ingress-nginx",
        "https://kubernetes.io/blog/2026/03/20/ingress2gateway-1-0-release",
      ],
      notes:
        "Cluster anchor. The role separation between infrastructure and application teams is the real argument for Gateway API, not the feature list.",
    },
    {
      id: "devops-02",
      title: "Ingress NGINX is archived: what to do about it now",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "how-to",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "ingress nginx archived migration",
      secondaryKeywords: ["ingress-nginx end of life", "ingress nginx no security updates"],
      updateClass: "volatile",
      pillarSlug: "kubernetes-gateway-api-transition",
      relatedTopics: ["devops-01", "devops-03", "devops-04"],
      articleSlug: "ingress-nginx-archived-migration",
      requiredSources: [
        "https://github.com/kubernetes/ingress-nginx",
        "https://github.com/kubernetes-sigs/ingress2gateway",
      ],
      notes:
        "Verified Aug 2026 from the repository itself: archived by the owner on 24 March 2026 and read-only. No further releases, bugfixes or security vulnerability updates. The project states that anyone not already using it should not deploy it, and directs users to pick a Gateway API implementation. This is an unpatched-component problem, not a preference question — frame it that way.",
    },
    {
      id: "devops-03",
      title: "The Gateway API resource model, and who owns each object",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "gateway api resource model httproute",
      secondaryKeywords: ["gatewayclass gateway httproute", "gateway api rbac separation"],
      updateClass: "volatile",
      pillarSlug: "kubernetes-gateway-api-transition",
      relatedTopics: ["devops-01"],
      requiredSources: ["https://gateway-api.sigs.k8s.io/api-types/gateway/"],
    },
    {
      id: "devops-04",
      title: "Choosing a Gateway API implementation without repeating the ingress mistake",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "gateway api implementation comparison",
      secondaryKeywords: ["conformance gateway api", "envoy gateway vs cilium vs istio"],
      updateClass: "volatile",
      pillarSlug: "kubernetes-gateway-api-transition",
      relatedTopics: ["devops-01", "devops-02"],
      requiredSources: ["https://gateway-api.sigs.k8s.io/implementations/"],
      notes:
        "Conformance level and governance model are the criteria that would have predicted the ingress-nginx outcome.",
    },

    // ------------------------------------------------------------------ IaC
    {
      id: "devops-05",
      title: "Infrastructure as code at team scale: what breaks after the first year",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "infrastructure as code team scale problems",
      secondaryKeywords: ["terraform module structure", "iac repository layout"],
      updateClass: "annual",
      pillar: "Infrastructure as code at scale",
      plannedSlug: "infrastructure-as-code-at-scale",
      plannedInternalLinks: ["devops-06", "devops-07", "devops-08", "devops-09"],
      notes: "Cluster anchor. Blast radius and state boundaries are the organising idea.",
    },
    {
      id: "devops-06",
      title: "Terraform or OpenTofu: a decision that is now about governance, not features",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "terraform vs opentofu decision",
      secondaryKeywords: ["opentofu migration", "terraform bsl licence enterprise"],
      updateClass: "volatile",
      pillarSlug: "infrastructure-as-code-at-scale",
      relatedTopics: ["devops-05", "devops-07"],
      articleSlug: "terraform-vs-opentofu",
      requiredSources: [
        "https://opentofu.org/docs/",
        "https://developer.hashicorp.com/terraform/docs",
        "HashiCorp BUSL licence FAQ",
      ],
      notes:
        "Verified Aug 2026: Terraform moved from MPL 2.0 to BUSL 1.1 in August 2023; OpenTofu forked at 1.6, is MPL 2.0 and Linux Foundation governed, currently 1.12, and remains wire-compatible with Terraform providers and state. Terraform is now under IBM ownership. OpenTofu-only capabilities worth naming: native state and plan encryption, provider-level for_each, and the -exclude flag. Volatile — licence and ownership positions move.",
    },
    {
      id: "devops-07",
      title: "State files: locking, isolation and the blast radius of one apply",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "terraform state isolation locking",
      secondaryKeywords: ["remote state backend design", "state file splitting"],
      updateClass: "annual",
      pillarSlug: "infrastructure-as-code-at-scale",
      relatedTopics: ["devops-05", "devops-06"],
      requiredSources: ["Terraform state documentation", "OpenTofu state documentation"],
    },
    {
      id: "devops-08",
      title: "Configuration drift: detecting it before the next apply does",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "infrastructure drift detection",
      secondaryKeywords: ["terraform plan unexpected changes", "manual change cloud console"],
      updateClass: "annual",
      pillarSlug: "infrastructure-as-code-at-scale",
      relatedTopics: ["devops-05", "devops-07"],
    },
    {
      id: "devops-09",
      title: "Policy as code: guardrails that fail the plan rather than the audit",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "policy as code terraform opa",
      secondaryKeywords: ["conftest rego policy", "preventive cloud guardrails"],
      updateClass: "annual",
      pillarSlug: "infrastructure-as-code-at-scale",
      relatedTopics: ["devops-05"],
      requiredSources: ["Open Policy Agent documentation", "Conftest documentation"],
    },

    // -------------------------------------------------------- Pipeline security
    {
      id: "devops-10",
      title: "Pipeline security: the build system is production access",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "ci cd pipeline security model",
      secondaryKeywords: ["build system threat model", "pipeline privilege escalation"],
      updateClass: "annual",
      pillar: "Pipeline security",
      plannedSlug: "cicd-pipeline-security",
      plannedInternalLinks: ["devops-11", "devops-12", "devops-13"],
      diagramOpportunity:
        "The trust path from a pull request to a production credential, marking each point where an untrusted contributor can influence execution.",
      requiredSources: ["SLSA specification", "GitHub Actions security hardening documentation"],
      notes: "Cluster anchor. Links across to sec-41 for provenance rather than restating it.",
    },
    {
      id: "devops-11",
      title: "Workload identity federation: retiring long-lived cloud credentials from CI",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "oidc workload identity federation ci",
      secondaryKeywords: ["github actions oidc cloud", "remove static cloud keys pipeline"],
      updateClass: "annual",
      pillarSlug: "cicd-pipeline-security",
      relatedTopics: ["devops-10"],
      requiredSources: [
        "GitHub Actions OIDC documentation",
        "Microsoft Entra workload identity federation documentation",
      ],
    },
    {
      id: "devops-12",
      title: "Self-hosted runners: the isolation problem nobody budgets for",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "analysis",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "self hosted runner isolation security",
      secondaryKeywords: ["ephemeral ci runner", "runner escape risk"],
      updateClass: "annual",
      pillarSlug: "cicd-pipeline-security",
      relatedTopics: ["devops-10"],
      requiredSources: ["GitHub self-hosted runner security documentation"],
    },
    {
      id: "devops-13",
      title: "Signing what you ship: build provenance a consumer can verify",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "build provenance attestation signing",
      secondaryKeywords: ["sigstore cosign artifact", "slsa build level"],
      updateClass: "annual",
      pillarSlug: "cicd-pipeline-security",
      relatedTopics: ["devops-10"],
      requiredSources: ["SLSA specification", "Sigstore documentation"],
      notes:
        "Operational how-to. sec-41 owns what SBOM and provenance *prove*; do not repeat that argument.",
    },

    // ----------------------------------------------------------- Containers
    {
      id: "devops-14",
      title: "Container image strategy: what you inherit from the base image",
      category: "devops",
      subcategory: "Containers",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "container base image strategy",
      secondaryKeywords: ["image layer size", "container image lifecycle"],
      updateClass: "annual",
      pillar: "Container image strategy",
      plannedSlug: "container-image-strategy",
      plannedInternalLinks: ["devops-15", "devops-16"],
      requiredSources: ["Docker official documentation", "OCI Image Format Specification"],
      notes: "Cluster anchor.",
    },
    {
      id: "devops-15",
      title: "Distroless, Alpine or a full distribution: choosing a base image",
      category: "devops",
      subcategory: "Containers",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "distroless vs alpine base image",
      secondaryKeywords: ["musl glibc container issue", "minimal container image debugging"],
      updateClass: "annual",
      pillarSlug: "container-image-strategy",
      relatedTopics: ["devops-14"],
      requiredSources: ["Distroless project documentation", "Alpine Linux documentation"],
    },
    {
      id: "devops-16",
      title: "Image scanning: why the CVE count is not the risk",
      category: "devops",
      subcategory: "Containers",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "container image cve scanning noise",
      secondaryKeywords: ["reachable vulnerability container", "vex vulnerability exploitability"],
      updateClass: "annual",
      pillarSlug: "container-image-strategy",
      relatedTopics: ["devops-14", "devops-15"],
      requiredSources: ["OpenVEX specification", "Trivy documentation"],
    },
    {
      id: "devops-17",
      title: "What actually happens when a pod sends a packet",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "kubernetes pod networking",
      secondaryKeywords: ["cni plugin packet flow", "kubernetes mtu vxlan"],
      requiredSources: [
        "https://kubernetes.io/docs/concepts/cluster-administration/networking/",
        "https://kubernetes.io/docs/reference/networking/virtual-ips/",
      ],
      updateClass: "evergreen",
      articleSlug: "kubernetes-pod-networking-packet-flow",
      notes:
        "Refined from Qwen batch-001 article 4. Technically sound as drafted; no factual corrections were needed. Deliberately does not link the eBPF piece, which is still a draft, because that would be a published-to-draft link.",
    },
    {
      id: "devops-18",
      title: "Three settings in a StorageClass decide your bill and your outages",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "kubernetes storageclass",
      secondaryKeywords: [
        "volumebindingmode waitforfirstconsumer",
        "persistent volume reclaim policy",
      ],
      requiredSources: [
        "https://kubernetes.io/docs/concepts/storage/storage-classes/",
        "https://kubernetes.io/docs/concepts/storage/persistent-volumes/",
      ],
      updateClass: "evergreen",
      articleSlug: "kubernetes-storage-classes-costs-performance-traps",
      notes:
        "Refined from Qwen batch-003 article 4. Technically sound; removed the illustrative bill, volume totals and IOPS figures. Scoped to StorageClass mechanics so it does not collide with the batch-011 draft on StatefulSets and storage identity, which should keep to ordinals, per-replica claims and identity.",
    },
    {
      id: "devops-19",
      title: "Your pipeline does not need a secret. It needs to prove who it is",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "ci/cd secrets management oidc",
      secondaryKeywords: ["github actions oidc", "vault jwt auth method"],
      requiredSources: [
        "https://developer.hashicorp.com/vault/docs/auth/jwt",
        "https://owasp.org/www-project-top-10-ci-cd-security-risks/",
      ],
      updateClass: "annual",
      articleSlug: "secrets-management-cicd-vault-oidc-reality",
      notes:
        "Refined from Qwen batch-003 article 5. Technically sound; removed the illustrative breach cost. Added the point the draft's own title promised but never made: the clouds accept CI OIDC tokens directly, so for single-cloud deploys Vault is not required at all. The security win is OIDC, not the broker.",
    },
    {
      id: "devops-20",
      title: "Node groups made autoscaling a shape problem, not a capacity problem",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "karpenter vs cluster autoscaler",
      secondaryKeywords: ["karpenter nodepool", "karpenter consolidation"],
      requiredSources: [
        "https://karpenter.sh/docs/concepts/nodepools/",
        "https://karpenter.sh/docs/concepts/disruption/",
      ],
      updateClass: "volatile",
      articleSlug: "karpenter-vs-cluster-autoscaler-node-scaling",
      notes:
        "Refined from Qwen batch-004 article 5. Removed a spot savings percentage and an invented recovery time. Corrected the Azure equivalent, which the draft called Karpenter-AKS; it is node autoprovisioning, built on Karpenter. Scope is node provisioning only — pod networking is devops-17 and storage is devops-18, and none of the three overlap.",
    },
    {
      id: "devops-21",
      title: "Mesh mTLS moves your problem from firewall rules to certificate expiry",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "service mesh mtls",
      secondaryKeywords: ["spiffe workload identity", "certificate rotation kubernetes"],
      requiredSources: [
        "https://istio.io/latest/docs/concepts/security/",
        "https://linkerd.io/2/features/automatic-mtls/",
      ],
      updateClass: "volatile",
      articleSlug: "service-mesh-mtls-operational-overhead",
      notes:
        "Refined from Qwen batch-005 article 1. The draft attributed Envoy to Linkerd; Linkerd uses its own Rust proxy, and the two are routinely conflated. Removed unsourced CPU overhead percentages. Added Istio ambient mode, which changes the sidecar trade the draft treats as fixed.",
    },
    {
      id: "devops-22",
      title: "Terraform state is a memory, and it can be wrong about your infrastructure",
      category: "devops",
      subcategory: "Infrastructure as Code",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "terraform state locking",
      secondaryKeywords: ["terraform drift detection", "terraform moved block"],
      requiredSources: [
        "https://developer.hashicorp.com/terraform/language/state/locking",
        "https://developer.hashicorp.com/terraform/language/modules/develop/refactoring",
      ],
      updateClass: "annual",
      articleSlug: "terraform-state-locking-drift-enterprise-reality",
      notes:
        "Refined from Qwen batch-005 article 4. Removed a fabricated plan-duration benchmark. Flagged S3 native locking, which supersedes the DynamoDB table pattern the draft presents as required. Scope is state management, distinct from the published terraform-vs-opentofu tool comparison.",
    },
    {
      id: "devops-23",
      title: "A clean scan tells you about yesterday's known bugs",
      category: "devops",
      subcategory: "Containers",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "container image security",
      secondaryKeywords: ["container image signing", "sigstore cosign"],
      requiredSources: [
        "https://docs.sigstore.dev/cosign/signing/overview/",
        "https://falco.org/docs/",
      ],
      updateClass: "annual",
      articleSlug: "container-image-security-beyond-scanning",
      notes:
        "Refined from Qwen batch-006 article 5. The draft named an OpenSSL version as vulnerable to a CVE that version had in fact fixed — the same inversion recorded in the handover for an earlier batch. No CVE-and-version pairings are used at all, and a callout warns about the pattern. Added software bill of materials, which the draft omitted. Boundary: devops-21 owns runtime workload identity, this owns image provenance; they cross-link.",
    },
    {
      id: "devops-24",
      title: "A runner that survives the job also survives whatever the job left behind",
      category: "devops",
      subcategory: "CI/CD",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "GitHub Actions self-hosted runner security",
      secondaryKeywords: ["Actions Runner Controller", "runner scale sets", "ephemeral CI runners"],
      updateClass: "volatile",
      articleSlug: "github-actions-self-hosted-runner-security",
    },
    {
      id: "devops-25",
      title: "You built an image with no shell, and now you need a shell",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Kubernetes ephemeral containers debugging",
      secondaryKeywords: ["kubectl debug", "distroless debugging", "ephemeralContainers spec"],
      updateClass: "volatile",
      articleSlug: "kubernetes-ephemeral-containers-debugging-production",
    },
    {
      id: "devops-26",
      title: "The controller is not the proxy, and the gap between them is the comparison",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Kubernetes ingress controller comparison",
      secondaryKeywords: [
        "Envoy Gateway xDS",
        "Traefik IngressRoute CRD",
        "Gateway API conformance",
      ],
      updateClass: "volatile",
      articleSlug: "kubernetes-ingress-controller-architecture-nginx-traefik-envoy",
    },
    {
      id: "devops-27",
      title: "There is no Pending pod to look at, because no pod was ever made",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Kubernetes ResourceQuota LimitRange namespace governance",
      secondaryKeywords: [
        "quota admission rejection",
        "LimitRange defaultRequest",
        "maxLimitRequestRatio",
      ],
      updateClass: "annual",
      articleSlug: "kubernetes-resourcequota-vs-limitrange-namespace-governance",
    },
    {
      id: "devops-28",
      title: "One state file is one lock, and one lock is the whole deployment pipeline",
      category: "devops",
      subcategory: "Infrastructure as code",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Terraform state splitting enterprise scale",
      secondaryKeywords: [
        "terraform_remote_state data source",
        "Terragrunt dependency block",
        "terraform state mv",
      ],
      updateClass: "volatile",
      articleSlug: "terraform-state-splitting-enterprise-scale-terragrunt",
    },
    {
      id: "devops-29",
      title:
        "EKS Pod Identity vs IRSA: architecture, migration, and the boundary that still matters",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "EKS Pod Identity vs IRSA",
      secondaryKeywords: [
        "EKS Pod Identity association",
        "IAM Roles for Service Accounts migration",
        "EKS pod IAM role",
      ],
      updateClass: "volatile",
      articleSlug: "eks-pod-identity-vs-irsa-migration",
    },
    {
      id: "devops-30",
      title: "eBPF in production: what the verifier guarantees, and what it does not",
      category: "devops",
      subcategory: "Observability",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "ebpf in production",
      secondaryKeywords: [
        "ebpf verifier limits",
        "cap_bpf cap_perfmon",
        "btf co-re kernel requirements",
      ],
      updateClass: "annual",
      articleSlug: "ebpf-production-observability-security-boundaries",
    },
    {
      id: "devops-31",
      title: "Your network policy might be doing nothing, and nothing will tell you",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Kubernetes NetworkPolicy default deny",
      secondaryKeywords: [
        "CNI network policy enforcement",
        "Kubernetes micro-segmentation",
        "Calico vs Cilium policy",
      ],
      updateClass: "annual",
      articleSlug: "kubernetes-network-policy-default-deny-implementation",
    },
    {
      id: "devops-32",
      title: "A disruption budget is a promise the cluster has to keep, even when it cannot",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Kubernetes Pod Disruption Budgets",
      secondaryKeywords: [
        "minAvailable vs maxUnavailable",
        "Kubernetes Eviction API 429",
        "node drain stuck PDB",
      ],
      updateClass: "annual",
      articleSlug: "kubernetes-pod-disruption-budgets-eviction-mechanics",
    },
    {
      id: "devops-33",
      title:
        "OpenTelemetry vs proprietary APM: the observability decision that changes your operating model",
      category: "devops",
      subcategory: "Observability",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "OpenTelemetry vs Datadog",
      secondaryKeywords: [
        "OpenTelemetry Collector architecture",
        "OTLP protocol",
        "observability cost optimization",
      ],
      updateClass: "annual",
      articleSlug: "opentelemetry-vs-proprietary-apm-observability-cost",
    },
    {
      id: "devops-34",
      title: "Taking the proxy out of the pod changes who pays for the mesh",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Istio Ambient Mesh architecture",
      secondaryKeywords: ["ztunnel node proxy", "waypoint proxy", "HBONE protocol"],
      updateClass: "annual",
      articleSlug: "istio-ambient-mesh-sidecarless-architecture",
    },
    {
      id: "devops-35",
      title: "The rebalance loop that eats a consumer group alive",
      category: "devops",
      subcategory: "Observability",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Apache Kafka consumer group rebalance",
      secondaryKeywords: [
        "max.poll.interval.ms",
        "cooperative sticky assignor",
        "Kafka exactly-once semantics",
      ],
      updateClass: "annual",
      articleSlug: "kafka-consumer-groups-rebalance-exactly-once",
    },
    {
      id: "devops-36",
      title: "One rule says never; the other says how uneven you can live with",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "comparison",
      searchIntent: "comparison",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Kubernetes Topology Spread Constraints vs Pod Anti-Affinity",
      secondaryKeywords: [
        "maxSkew",
        "whenUnsatisfiable DoNotSchedule",
        "pod anti-affinity deadlock",
      ],
      updateClass: "annual",
      articleSlug: "kubernetes-topology-spread-constraints-vs-pod-anti-affinity",
    },
    {
      id: "devops-37",
      title: "Priority decides who gets scheduled, not who gets to keep running",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Kubernetes PriorityClass preemption eviction",
      secondaryKeywords: [
        "pod priority scheduling",
        "preemptionPolicy Never",
        "system-node-critical",
      ],
      updateClass: "annual",
      articleSlug: "kubernetes-priorityclass-preemption-pod-eviction",
    },
    {
      id: "devops-38",
      title: "A StatefulSet is not a Deployment with a disk bolted on",
      category: "devops",
      subcategory: "Kubernetes",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Kubernetes StatefulSet vs Deployment",
      secondaryKeywords: [
        "StatefulSet stable network identity",
        "persistentVolumeClaimRetentionPolicy",
        "headless service Kubernetes",
      ],
      updateClass: "volatile",
      articleSlug: "kubernetes-statefulset-vs-deployment-storage-identity",
    },
    {
      id: "devops-39",
      title:
        "OOMKilled is a kernel decision, and your memory limit is the number that triggered it",
      category: "devops",
      subcategory: "Containers",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "Linux cgroups v2 memory OOM killer",
      secondaryKeywords: [
        "memory.high vs memory.max",
        "Kubernetes OOMKilled",
        "cgroup memory pressure PSI",
      ],
      updateClass: "volatile",
      articleSlug: "linux-cgroups-v2-memory-oom-killer-reality",
    },
  ],
};
