import type { Segment } from "../types";

/**
 * Enterprise networking backlog.
 *
 * Distinct from the `networking` segment by audience and altitude: `networking`
 * explains how a protocol works, this segment decides how an organisation's
 * network is arranged and governed.
 *
 * Two boundaries are deliberate. Cryptographic migration belongs to the
 * segments that already own it — `cybersecurity-ciso` holds post-quantum
 * migration planning (sec-52) and `networking` holds the on-the-wire ClientHello
 * behaviour (net-44) — so the transport cluster here covers enterprise
 * operational concerns only and links across. Microsegmentation as a technique
 * is sec-11; what lives here is the architecture that contains it.
 */
export const segment: Segment = {
  name: "Enterprise networking",
  category: "enterprise-networking",
  topics: [
    // --------------------------------------------------------- Segmentation
    {
      id: "entnet-01",
      title: "Segmentation architecture: drawing boundaries that survive an audit and an outage",
      category: "enterprise-networking",
      subcategory: "Segmentation",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "enterprise network segmentation architecture",
      secondaryKeywords: ["segmentation design principles", "network zones enterprise"],
      updateClass: "evergreen",
      pillar: "Network segmentation architecture",
      plannedSlug: "enterprise-network-segmentation-architecture",
      plannedInternalLinks: ["entnet-02", "entnet-03", "entnet-04"],
      diagramOpportunity:
        "Boundaries drawn by blast radius against boundaries drawn by org chart, on the same estate, showing where the two disagree.",
      requiredSources: [
        "NIST SP 800-207 Zero Trust Architecture",
        "CISA Zero Trust Maturity Model",
      ],
      notes:
        "Cluster anchor, and the owner of the existing zero-trust-network-segmentation draft (entnet-02), which is currently an orphan in the knowledge graph.",
    },
    {
      id: "entnet-02",
      title: "Network segmentation for zero trust",
      category: "enterprise-networking",
      subcategory: "Segmentation",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "DRAFT",
      targetKeyword: "network segmentation best practices",
      secondaryKeywords: ["zero trust segmentation", "flat network risk"],
      updateClass: "evergreen",
      pillarSlug: "enterprise-network-segmentation-architecture",
      relatedTopics: ["entnet-01", "entnet-03"],
      articleSlug: "zero-trust-network-segmentation",
      requiredSources: ["NIST SP 800-207 Zero Trust Architecture"],
      notes:
        "Existing 190-word draft. Attaching it to entnet-01 is what removes its orphan status; expand against NIST SP 800-207 before lifting draft.",
    },
    {
      id: "entnet-03",
      title: "Segmenting OT, IoT and the devices that cannot be patched",
      category: "enterprise-networking",
      subcategory: "Segmentation",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "ot iot network segmentation",
      secondaryKeywords: ["unpatchable device isolation", "building systems network security"],
      updateClass: "evergreen",
      pillarSlug: "enterprise-network-segmentation-architecture",
      relatedTopics: ["entnet-01"],
      requiredSources: ["NIST SP 800-82 Guide to OT Security", "CISA ICS advisories"],
      notes: "The realistic answer for devices with a ten-year life and no vendor patches.",
    },
    {
      id: "entnet-04",
      title: "Policy enforcement points: where the decision is actually made",
      category: "enterprise-networking",
      subcategory: "Segmentation",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "policy enforcement point network design",
      secondaryKeywords: ["pdp pep zero trust", "identity aware proxy enterprise"],
      updateClass: "evergreen",
      pillarSlug: "enterprise-network-segmentation-architecture",
      relatedTopics: ["entnet-01", "entnet-06"],
      requiredSources: ["NIST SP 800-207 Zero Trust Architecture"],
    },

    // ------------------------------------------------------------ WAN / edge
    {
      id: "entnet-05",
      title: "The enterprise WAN and internet edge after the office stopped being the centre",
      category: "enterprise-networking",
      subcategory: "WAN",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "enterprise wan internet edge architecture",
      secondaryKeywords: ["branch connectivity design", "hub and spoke wan alternative"],
      updateClass: "annual",
      pillar: "Enterprise WAN and edge",
      plannedSlug: "enterprise-wan-and-edge",
      plannedInternalLinks: ["entnet-06", "entnet-07", "entnet-08"],
      notes:
        "Cluster anchor. Traffic no longer returns to a datacentre; the design has to admit that.",
    },
    {
      id: "entnet-06",
      title: "SASE and SSE: what the acronyms actually buy, and what they replace",
      category: "enterprise-networking",
      subcategory: "WAN",
      contentType: "explainer",
      searchIntent: "decision",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "sase vs sse enterprise",
      secondaryKeywords: ["secure service edge explained", "sase replace vpn"],
      updateClass: "volatile",
      pillarSlug: "enterprise-wan-and-edge",
      relatedTopics: ["entnet-05", "entnet-04"],
      requiredSources: ["Vendor primary documentation for the platforms compared"],
      notes:
        "Volatile: vendor category definitions shift. Anchor on the functions, not the marketing term.",
    },
    {
      id: "entnet-07",
      title: "SD-WAN or MPLS: a cost and failure-mode comparison",
      category: "enterprise-networking",
      subcategory: "WAN",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "sd-wan vs mpls decision",
      secondaryKeywords: ["mpls replacement cost", "branch wan failover"],
      updateClass: "annual",
      pillarSlug: "enterprise-wan-and-edge",
      relatedTopics: ["entnet-05"],
    },
    {
      id: "entnet-08",
      title: "Internet edge resilience: multihoming, and what actually fails",
      category: "enterprise-networking",
      subcategory: "WAN",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "enterprise internet multihoming resilience",
      secondaryKeywords: ["dual isp failover design", "bgp multihoming enterprise"],
      updateClass: "evergreen",
      pillarSlug: "enterprise-wan-and-edge",
      relatedTopics: ["entnet-05"],
      requiredSources: ["RFC 4786 Operation of Anycast Services", "RIPE routing documentation"],
      notes:
        "Links across to the networking segment's BGP fundamentals rather than re-teaching BGP.",
    },

    // --------------------------------------------------- Transport security
    {
      id: "entnet-09",
      title: "Transport security as an operational problem, not a cryptographic one",
      category: "enterprise-networking",
      subcategory: "Transport security",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "enterprise transport security operations",
      secondaryKeywords: ["internal tls estate", "encryption in transit enterprise"],
      updateClass: "annual",
      pillar: "Enterprise transport security",
      plannedSlug: "enterprise-transport-security",
      plannedInternalLinks: ["entnet-10", "entnet-11", "entnet-12"],
      notes:
        "Cluster anchor. Deliberately excludes post-quantum migration planning (sec-52) and ClientHello wire behaviour (net-44); links to both instead.",
    },
    {
      id: "entnet-10",
      title: "Certificate lifecycle at enterprise scale: the expiry that takes a service down",
      category: "enterprise-networking",
      subcategory: "Transport security",
      contentType: "how-to",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "enterprise certificate lifecycle management",
      secondaryKeywords: ["certificate expiry outage", "acme internal certificates"],
      updateClass: "annual",
      pillarSlug: "enterprise-transport-security",
      relatedTopics: ["entnet-09"],
      requiredSources: ["RFC 8555 ACME", "CA/Browser Forum Baseline Requirements"],
      notes:
        "Certificate lifetimes are shortening industry-wide, which converts a manual renewal process into an automation requirement. Verify the current maximum lifetime before drafting.",
    },
    {
      id: "entnet-11",
      title: "TLS inspection: the cost, the blast radius and what it cannot see",
      category: "enterprise-networking",
      subcategory: "Transport security",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "tls inspection enterprise tradeoffs",
      secondaryKeywords: ["ssl decryption proxy risk", "certificate pinning breaks inspection"],
      updateClass: "annual",
      pillarSlug: "enterprise-transport-security",
      relatedTopics: ["entnet-09", "entnet-06"],
      requiredSources: ["NIST SP 800-52 Rev. 2", "Vendor documentation for the proxy discussed"],
    },
    {
      id: "entnet-12",
      title: "mTLS between internal services: when it is worth the operational weight",
      category: "enterprise-networking",
      subcategory: "Transport security",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "mutual tls internal services decision",
      secondaryKeywords: ["service mesh mtls cost", "workload identity certificates"],
      updateClass: "annual",
      pillarSlug: "enterprise-transport-security",
      relatedTopics: ["entnet-09", "entnet-10", "devops-01"],
      requiredSources: ["SPIFFE specification", "RFC 8446 TLS 1.3"],
      notes: "Cross-domain link to the Kubernetes cluster, where mTLS usually arrives via a mesh.",
    },
  ],
};
