import type { Segment } from "../types";

/**
 * IT automation backlog.
 *
 * The bridge segment: it connects the publication's existing Microsoft depth to
 * the newer development and platform coverage, which makes it unusually
 * valuable for internal linking despite being small.
 *
 * Scope boundary worth keeping: `microsoft-intune` owns Intune-specific
 * reporting (intune-71), and `software` owns editor and packaging tooling.
 * What lives here is the automation *mechanism* — authentication, permissions,
 * platform choice, unattended execution — independent of the product being
 * automated.
 */
export const segment: Segment = {
  name: "IT automation",
  category: "it-automation",
  topics: [
    // ------------------------------------------------------ Microsoft Graph
    {
      id: "itauto-01",
      title: "Microsoft Graph as an automation surface: what it is good and bad at",
      category: "it-automation",
      subcategory: "Microsoft Graph",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "microsoft graph automation surface",
      secondaryKeywords: ["graph api vs powershell module", "automating microsoft 365 with graph"],
      updateClass: "annual",
      pillar: "Microsoft Graph for IT automation",
      plannedSlug: "microsoft-graph-for-it-automation",
      plannedInternalLinks: ["itauto-02", "itauto-03", "itauto-04"],
      requiredSources: [
        "https://learn.microsoft.com/graph/overview",
        "https://learn.microsoft.com/powershell/microsoftgraph/overview",
      ],
      notes:
        "Cluster anchor. Must state the v1.0 versus beta stability guarantee plainly — it is the single most common cause of automation that breaks without warning.",
    },
    {
      id: "itauto-02",
      title: "App-only authentication for Graph: certificate, secret or managed identity",
      category: "it-automation",
      subcategory: "Microsoft Graph",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "graph app only authentication managed identity",
      secondaryKeywords: ["connect-mggraph certificate", "unattended graph script auth"],
      updateClass: "annual",
      pillarSlug: "microsoft-graph-for-it-automation",
      relatedTopics: ["itauto-01", "itauto-03", "itauto-11"],
      requiredSources: [
        "https://learn.microsoft.com/powershell/microsoftgraph/app-only",
        "https://learn.microsoft.com/powershell/microsoftgraph/authentication-commands",
        "https://learn.microsoft.com/graph/tutorials/powershell-app-only",
      ],
      notes:
        "Verified Aug 2026 against Microsoft Learn: Connect-MgGraph supports -CertificateThumbprint / -CertificateName, -ClientSecretCredential and managed identity; app-only uses the client credentials flow so permissions are configured on the app registration and require admin consent; Get-MgContext AuthType confirms AppOnly. PowerShell 7 is recommended. Note the separate Entra PowerShell module (Connect-Entra -Identity) as an adjacent path, not a replacement.",
    },
    {
      id: "itauto-03",
      title: "Delegated or application permissions: the choice that decides what your script can do",
      category: "it-automation",
      subcategory: "Microsoft Graph",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "delegated vs application permissions graph",
      secondaryKeywords: ["graph permission scope least privilege", "admin consent graph scope"],
      updateClass: "annual",
      pillarSlug: "microsoft-graph-for-it-automation",
      relatedTopics: ["itauto-01", "itauto-02"],
      requiredSources: [
        "https://learn.microsoft.com/graph/permissions-overview",
        "https://learn.microsoft.com/graph/permissions-reference",
      ],
      diagramOpportunity:
        "The effective-permission calculation for delegated (user ∩ app) against application (app only), showing why a delegated script fails for some users and not others.",
    },
    {
      id: "itauto-04",
      title: "Throttling, paging and batching: making Graph automation survive a large tenant",
      category: "it-automation",
      subcategory: "Microsoft Graph",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "graph api throttling 429 pagination",
      secondaryKeywords: ["graph batch request", "nextlink paging powershell"],
      updateClass: "annual",
      pillarSlug: "microsoft-graph-for-it-automation",
      relatedTopics: ["itauto-01"],
      requiredSources: [
        "https://learn.microsoft.com/graph/throttling",
        "https://learn.microsoft.com/graph/paging",
        "https://learn.microsoft.com/graph/json-batching",
      ],
      notes: "High-intent failure mode: scripts that work in a lab and fail at 10,000 objects.",
    },

    // -------------------------------------------------------- Platform choice
    {
      id: "itauto-05",
      title: "Choosing an automation platform in Azure without regretting it in a year",
      category: "it-automation",
      subcategory: "Azure automation",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P0",
      status: "RESEARCHED",
      targetKeyword: "azure automation platform choice",
      secondaryKeywords: ["logic apps vs functions vs automation", "which azure automation service"],
      updateClass: "volatile",
      pillar: "Automation platform choice",
      plannedSlug: "azure-automation-platform-choice",
      plannedInternalLinks: ["itauto-06", "itauto-07", "itauto-08"],
      requiredSources: [
        "https://learn.microsoft.com/azure/automation/automation-services",
        "https://learn.microsoft.com/azure/azure-functions/functions-compare-logic-apps-ms-flow-webjobs",
        "https://learn.microsoft.com/azure/logic-apps/automation/compare-automation-services",
      ],
      notes:
        "Cluster anchor. Verified Aug 2026: Microsoft's own comparison now includes Azure Logic Apps Automation (preview), which is AI/agent-oriented and supports MCP and A2A protocols — label it preview, since preview behaviour changes without notice. The durable decision axis remains orchestration-first (Logic Apps) versus code-first (Functions) versus script-and-hybrid-worker (Automation runbooks).",
    },
    {
      id: "itauto-06",
      title: "Logic Apps, Functions or Automation runbooks for an operational task",
      category: "it-automation",
      subcategory: "Azure automation",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "logic apps vs automation runbook operational task",
      secondaryKeywords: ["hybrid runbook worker on premises", "azure functions scheduled job"],
      updateClass: "volatile",
      pillarSlug: "azure-automation-platform-choice",
      relatedTopics: ["itauto-05"],
      requiredSources: ["https://learn.microsoft.com/azure/automation/automation-services"],
    },
    {
      id: "itauto-07",
      title: "Azure Automation runtime environments and the PowerShell version problem",
      category: "it-automation",
      subcategory: "Azure automation",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "azure automation runtime environment powershell version",
      secondaryKeywords: ["runbook module conflict", "upgrade runbook powershell 7"],
      updateClass: "volatile",
      pillarSlug: "azure-automation-platform-choice",
      relatedTopics: ["itauto-05", "itauto-06"],
      requiredSources: ["https://learn.microsoft.com/azure/automation/runtime-environment-overview"],
      notes: "Runtime environment was still labelled preview at last check — verify state before drafting.",
    },
    {
      id: "itauto-08",
      title: "Where Power Automate stops and Logic Apps starts",
      category: "it-automation",
      subcategory: "Azure automation",
      contentType: "explainer",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "power automate vs logic apps boundary",
      secondaryKeywords: ["citizen developer automation governance", "power platform sprawl"],
      updateClass: "volatile",
      pillarSlug: "azure-automation-platform-choice",
      relatedTopics: ["itauto-05"],
      requiredSources: [
        "https://learn.microsoft.com/azure/logic-apps/power-automate-migration",
      ],
      notes: "The governance angle — who owns a flow when its author leaves — is the durable part.",
    },

    // ---------------------------------------------------- Operational scripting
    {
      id: "itauto-09",
      title: "Operational PowerShell: scripts that run unattended without supervision",
      category: "it-automation",
      subcategory: "PowerShell",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "unattended powershell automation design",
      secondaryKeywords: ["production powershell script standards", "powershell automation reliability"],
      updateClass: "evergreen",
      pillar: "Operational PowerShell",
      plannedSlug: "operational-powershell",
      plannedInternalLinks: ["itauto-10", "itauto-11", "itauto-12"],
      notes:
        "Cluster anchor. Distinct from the Windows segment's PowerShell basics topic, which is an introduction; this is about unattended execution.",
    },
    {
      id: "itauto-10",
      title: "Idempotency and error handling in operational scripts",
      category: "it-automation",
      subcategory: "PowerShell",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "idempotent powershell script error handling",
      secondaryKeywords: ["erroractionpreference automation", "safe rerun script"],
      updateClass: "evergreen",
      pillarSlug: "operational-powershell",
      relatedTopics: ["itauto-09", "dev-04"],
      requiredSources: ["PowerShell about_Try_Catch_Finally documentation"],
      notes: "Deliberate cross-domain link to dev-04: the same idea, one in an API and one in a script.",
    },
    {
      id: "itauto-11",
      title: "Secrets in automation: what replaces the credential in the script",
      category: "it-automation",
      subcategory: "PowerShell",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "automation secrets key vault managed identity",
      secondaryKeywords: ["remove hardcoded credential script", "secret rotation automation"],
      updateClass: "annual",
      pillarSlug: "operational-powershell",
      relatedTopics: ["itauto-09", "itauto-02", "devops-11"],
      requiredSources: [
        "https://learn.microsoft.com/azure/key-vault/general/overview",
        "https://learn.microsoft.com/entra/identity/managed-identities-azure-resources/overview",
      ],
      notes: "Cross-domain link to devops-11: the same problem solved in a pipeline instead of a script.",
    },
    {
      id: "itauto-12",
      title: "What breaks when automation runs unattended at 03:00",
      category: "it-automation",
      subcategory: "PowerShell",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "scheduled automation silent failure",
      secondaryKeywords: ["scheduled task runs but does nothing", "automation alerting on failure"],
      updateClass: "evergreen",
      pillarSlug: "operational-powershell",
      relatedTopics: ["itauto-09", "itauto-04"],
      notes: "Expired certificates, consent revocation, throttling and silent partial success.",
    },
  ],
};
