import type { Segment } from "../types";

/**
 * Microsoft Intune backlog.
 *
 * Organised by the operational area an administrator is actually in when they
 * search, not by product feature. Every entry is a distinct problem with a
 * distinct answer — where two topics would resolve to the same article, only
 * one is listed.
 */
export const segment: Segment = {
  name: "Microsoft Intune",
  category: "microsoft-intune",
  topics: [
    /* ---------------- Autopilot and provisioning ---------------- */
    {
      id: "intune-01",
      title: "Enrollment Status Page stuck: a systematic troubleshooting method",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "enrollment status page stuck",
      updateClass: "annual",
      articleSlug: "enrollment-status-page-troubleshooting",
    },
    {
      id: "intune-02",
      title: "Autopilot device registration failures: hash, hardware ID and duplicate objects",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "autopilot device not registering",
      secondaryKeywords: ["autopilot hardware hash import failed", "duplicate autopilot device"],
      relatedTopics: ["intune-01", "intune-03"],
      requiredSources: ["Microsoft Learn: Windows Autopilot registration overview"],
      updateClass: "annual",
      articleSlug: "autopilot-device-registration-failures",
      notes: "Written 2026-08-13, 2,238 words. Published.",
    },
    {
      id: "intune-03",
      title: "Autopilot device preparation vs the classic Autopilot profile: what changed",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "autopilot device preparation policy",
      relatedTopics: ["intune-01"],
      requiredSources: ["Microsoft Learn: Windows Autopilot device preparation"],
      updateClass: "volatile",
      articleSlug: "autopilot-device-preparation-vs-autopilot",
      notes:
        "Written 2026-08-13, 1,678 words. Published. Volatile area — recheck feature parity at each review.",
    },
    {
      id: "intune-04",
      title: "Pre-provisioning technician flow failures and how to read the reseal step",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "autopilot pre-provisioning failed",
      relatedTopics: ["intune-01"],
      updateClass: "annual",
      articleSlug: "autopilot-pre-provisioning-failures",
      notes: "Written 2026-08-13, 1,946 words. Published.",
    },
    {
      id: "intune-05",
      title: "Autopilot reset, wipe, fresh start and Autopilot again: choosing the right recovery",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "autopilot reset vs wipe",
      updateClass: "evergreen",
    },
    {
      id: "intune-06",
      title: "Device naming templates: what they can and cannot express",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "reference",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "intune device naming template",
      updateClass: "evergreen",
    },
    {
      id: "intune-07",
      title: "Self-deploying mode for kiosks and shared devices: prerequisites that actually bite",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "autopilot self-deploying mode",
      relatedTopics: ["intune-01"],
      updateClass: "annual",
    },

    /* ---------------- Configuration policy ---------------- */
    {
      id: "intune-10",
      title: "Intune policy conflicts: how to detect, diagnose and prevent them",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "intune policy conflict",
      updateClass: "annual",
      articleSlug: "intune-policy-conflicts",
    },
    {
      id: "intune-11",
      title: "Migrating from Group Policy to the Intune settings catalog",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "group policy to intune migration",
      updateClass: "annual",
      articleSlug: "group-policy-to-settings-catalog-migration",
    },
    {
      id: "intune-12",
      title: "Settings catalog, templates or custom OMA-URI: choosing a profile type",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "intune settings catalog vs template",
      relatedTopics: ["intune-10", "intune-11", "intune-13"],
      requiredSources: ["Microsoft Learn: Settings catalog", "Microsoft Learn: Custom settings"],
      updateClass: "annual",
    },
    {
      id: "intune-13",
      title: "Ingesting third-party ADMX templates into Intune",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "intune admx ingestion",
      secondaryKeywords: ["custom admx intune", "chrome admx intune"],
      relatedTopics: ["intune-12"],
      requiredSources: ["Microsoft Learn: Win32 and Desktop Bridge app ADMX policy CSP"],
      updateClass: "annual",
    },
    {
      id: "intune-14",
      title: "Assignment filters: rule syntax, evaluation order and the cases they cannot cover",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "reference",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "intune assignment filters",
      relatedTopics: ["intune-10"],
      updateClass: "annual",
    },
    {
      id: "intune-15",
      title: "User-targeted vs device-targeted policy: which to use and why it matters",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "intune user vs device assignment",
      relatedTopics: ["intune-10", "intune-14"],
      updateClass: "evergreen",
    },
    {
      id: "intune-16",
      title: "Scope tags and RBAC for distributed IT teams",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "intune scope tags",
      updateClass: "evergreen",
    },
    {
      id: "intune-17",
      title: "Config refresh: forcing policy back into place after local tampering",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "intune config refresh",
      updateClass: "volatile",
    },

    /* ---------------- Application delivery ---------------- */
    {
      id: "intune-20",
      title: "Win32 app detection rules: the four kinds and when each one lies to you",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "intune win32 app detection rule",
      secondaryKeywords: ["intune app keeps reinstalling", "detection rule not working"],
      relatedTopics: ["intune-21", "intune-01"],
      requiredSources: ["Microsoft Learn: Win32 app management"],
      updateClass: "evergreen",
      notes: "The 'app reinstalls every cycle' failure is a high-volume, low-competition query.",
      articleSlug: "win32-app-detection-rules",
    },
    {
      id: "intune-21",
      title: "Reading the Intune Management Extension log to diagnose app failures",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "intune management extension log",
      secondaryKeywords: ["IntuneManagementExtension.log", "intune app install failed 0x"],
      relatedTopics: ["intune-20", "intune-01"],
      updateClass: "annual",
      articleSlug: "intune-management-extension-logs",
    },
    {
      id: "intune-22",
      title: "Supersedence and dependencies: modelling an application estate that upgrades itself",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "intune app supersedence",
      relatedTopics: ["intune-20"],
      updateClass: "annual",
      articleSlug: "win32-app-supersedence-dependencies",
    },
    {
      id: "intune-23",
      title: "Packaging a Win32 app properly: IntuneWinAppUtil, exit codes and restart behaviour",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "intunewinapputil packaging",
      relatedTopics: ["intune-20", "intune-21"],
      updateClass: "evergreen",
      articleSlug: "intunewin-packaging-win32-apps",
    },
    {
      id: "intune-24",
      title: "Enterprise App Catalog vs your own Win32 packages",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "intune enterprise app catalog",
      updateClass: "volatile",
    },
    {
      id: "intune-25",
      title: "Required, available and uninstall: app assignment intents and their side effects",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "intune app assignment types",
      updateClass: "evergreen",
    },

    /* ---------------- Compliance ---------------- */
    {
      id: "intune-30",
      title: "Designing compliance policies that do not lock people out",
      category: "microsoft-intune",
      subcategory: "Compliance",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "intune compliance policy best practices",
      secondaryKeywords: ["compliance grace period", "mark device noncompliant"],
      relatedTopics: ["intune-31", "intune-10"],
      updateClass: "annual",
      articleSlug: "intune-compliance-policy-design",
    },
    {
      id: "intune-31",
      title: "Custom compliance scripts: writing and debugging the JSON contract",
      category: "microsoft-intune",
      subcategory: "Compliance",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "intune custom compliance script",
      relatedTopics: ["intune-30", "intune-41"],
      requiredSources: ["Microsoft Learn: Custom compliance settings"],
      updateClass: "annual",
      articleSlug: "intune-custom-compliance-scripts",
    },
    {
      id: "intune-32",
      title: "Why a compliant device still fails Conditional Access",
      category: "microsoft-intune",
      subcategory: "Compliance",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "device compliant but conditional access blocks",
      relatedTopics: ["intune-30"],
      updateClass: "annual",
      notes: "Cross-pillar: strong internal link target for the Entra Conditional Access article.",
      articleSlug: "compliant-device-conditional-access-blocked",
    },

    /* ---------------- Endpoint security ---------------- */
    {
      id: "intune-40",
      title: "Silent BitLocker encryption: the prerequisites that are actually required",
      category: "microsoft-intune",
      subcategory: "Compliance",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "intune bitlocker not encrypting",
      secondaryKeywords: ["silent bitlocker requirements", "bitlocker recovery key not escrowed"],
      relatedTopics: ["intune-10"],
      requiredSources: [
        "Microsoft Learn: BitLocker CSP",
        "Microsoft Learn: Disk encryption policy",
      ],
      updateClass: "annual",
    },
    {
      id: "intune-41",
      title: "Proactive remediations: detection and fix scripts that are safe to run fleet-wide",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "intune remediation script",
      secondaryKeywords: ["proactive remediations", "intune detection script"],
      relatedTopics: ["intune-31", "intune-42"],
      updateClass: "annual",
    },
    {
      id: "intune-42",
      title: "Platform scripts vs remediations vs Win32 apps for running code on endpoints",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "intune powershell script vs remediation",
      relatedTopics: ["intune-41", "intune-23"],
      updateClass: "evergreen",
    },
    {
      id: "intune-43",
      title: "Deploying attack surface reduction rules without breaking line-of-business apps",
      category: "microsoft-intune",
      subcategory: "Compliance",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "deploy asr rules intune",
      secondaryKeywords: ["asr audit mode", "asr rule exclusions"],
      relatedTopics: ["intune-10"],
      requiredSources: ["Microsoft Learn: Attack surface reduction rules deployment"],
      updateClass: "annual",
    },
    {
      id: "intune-44",
      title: "Windows LAPS with Intune: rotation, retrieval and the audit trail",
      category: "microsoft-intune",
      subcategory: "Compliance",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "windows laps intune",
      updateClass: "annual",
    },

    /* ---------------- Updates ---------------- */
    {
      id: "intune-50",
      title: "Windows Update rings that survive a Patch Tuesday problem",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "intune update rings",
      secondaryKeywords: ["windows update for business deferral", "pause windows updates intune"],
      updateClass: "annual",
    },
    {
      id: "intune-51",
      title: "Feature update policies: pinning a version and controlling when it moves",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "intune feature update policy",
      relatedTopics: ["intune-50"],
      updateClass: "volatile",
    },
    {
      id: "intune-52",
      title: "Why a device is not receiving updates: a diagnostic order of operations",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "intune device not getting updates",
      relatedTopics: ["intune-50"],
      updateClass: "annual",
    },

    /* ---------------- Enrollment ---------------- */
    {
      id: "intune-60",
      title: "Enrollment restrictions and device limits: what they block and what they do not",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "PUBLISHED",
      targetKeyword: "intune enrollment restrictions",
      relatedTopics: ["intune-02"],
      updateClass: "annual",
      articleSlug: "intune-enrollment-restrictions",
      notes: "Written 2026-08-13, 1,806 words. Published.",
    },
    {
      id: "intune-61",
      title: "Corporate device identifiers: making BYOD and corporate enrolment distinguishable",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "intune corporate device identifiers",
      updateClass: "evergreen",
    },
    {
      id: "intune-62",
      title: "Microsoft Entra join vs hybrid join: choosing for a Windows estate today",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "entra join vs hybrid join",
      relatedTopics: ["intune-11", "intune-02"],
      updateClass: "annual",
      articleSlug: "entra-join-vs-hybrid-join",
      notes:
        "High-intent decision query. Must be careful to describe current guidance, not history.",
    },

    /* ---------------- Reporting and diagnostics ---------------- */
    {
      id: "intune-70",
      title: "Collecting and reading Intune device diagnostics remotely",
      category: "microsoft-intune",
      subcategory: "Autopilot",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "intune collect diagnostics",
      relatedTopics: ["intune-01", "intune-21"],
      updateClass: "annual",
    },
    {
      id: "intune-71",
      title: "Building Intune reports with Microsoft Graph when the portal will not answer",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "DRAFT",
      targetKeyword: "intune graph api reporting",
      relatedTopics: ["intune-10"],
      requiredSources: ["Microsoft Graph documentation: deviceManagement resources"],
      updateClass: "annual",
      articleSlug: "graph-api-intune-reporting",
      notes: "Existing 128-word stub. Needs full rewrite, not expansion.",
    },
    {
      id: "intune-72",
      title: "Endpoint analytics: which of these scores are worth acting on",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "intune endpoint analytics",
      updateClass: "annual",
    },

    /* ---------------- Co-management and migration ---------------- */
    {
      id: "intune-80",
      title: "Moving co-management workloads from Configuration Manager to Intune, in order",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "co-management workloads intune",
      relatedTopics: ["intune-11", "intune-10"],
      requiredSources: ["Microsoft Learn: Co-management workloads"],
      updateClass: "annual",
    },
    {
      id: "intune-81",
      title: "Tenant attach: what it gives you before you commit to co-management",
      category: "microsoft-intune",
      subcategory: "Configuration policy",
      contentType: "explainer",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "configmgr tenant attach",
      relatedTopics: ["intune-80"],
      updateClass: "annual",
    },

    /* ---------------- Non-Windows platforms ---------------- */
    {
      id: "intune-90",
      title: "Android Enterprise enrolment modes: work profile, fully managed and dedicated",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "android enterprise enrollment modes",
      updateClass: "annual",
    },
    {
      id: "intune-91",
      title: "Apple Business Manager and automated device enrolment with Intune",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "apple business manager intune",
      relatedTopics: ["intune-90"],
      updateClass: "annual",
    },
    {
      id: "intune-92",
      title: "Managing macOS with Intune: what is genuinely covered and what is not",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "intune macos management",
      relatedTopics: ["intune-91"],
      updateClass: "volatile",
    },
    {
      id: "intune-93",
      title: "Platform SSO for macOS: what it replaces and what it requires",
      category: "microsoft-intune",
      subcategory: "App delivery",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "platform sso macos intune",
      relatedTopics: ["intune-92"],
      updateClass: "volatile",
    },
  ],
};
