import type { Segment } from "../types";

/**
 * Microsoft 365 and Entra ID backlog.
 *
 * Weighted towards identity, because that is where the failure modes are
 * expensive and the documentation is thinnest on the operational reality.
 */
export const segment: Segment = {
  name: "Microsoft 365 / Entra ID",
  category: "microsoft-365-entra-id",
  topics: [
    /* ---------------- Conditional Access ---------------- */
    {
      id: "m365-01",
      title: "A Conditional Access policy framework you can actually maintain",
      category: "microsoft-365-entra-id",
      subcategory: "Conditional Access",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P0",
      status: "EDITORIAL_REVIEW",
      targetKeyword: "conditional access framework",
      secondaryKeywords: ["conditional access policy design", "conditional access naming standard"],
      relatedTopics: ["m365-02", "m365-03", "intune-32"],
      requiredSources: ["Microsoft Learn: Conditional Access architecture and personas"],
      updateClass: "annual",
      articleSlug: "conditional-access-framework",
      notes:
        "Rewritten from the 385-word stub to 3,124 words against Microsoft Learn. Still draft:true pending review. Absorbs most of m365-03 (report-only) — re-scope or archive that topic before writing it.",
    },
    {
      id: "m365-02",
      title: "Break-glass accounts: the configuration most tenants get wrong",
      category: "microsoft-365-entra-id",
      subcategory: "Entra ID",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P0",
      status: "DRAFT",
      targetKeyword: "break glass account entra id",
      relatedTopics: ["m365-01"],
      requiredSources: ["Microsoft Learn: Manage emergency access accounts"],
      updateClass: "evergreen",
      articleSlug: "conditional-access-break-glass-accounts",
      notes: "Existing 231-word stub. Pairs with m365-01; publish together.",
    },
    {
      id: "m365-03",
      title: "Conditional Access report-only mode: how to use it as a real change process",
      category: "microsoft-365-entra-id",
      subcategory: "Conditional Access",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "conditional access report only mode",
      relatedTopics: ["m365-01"],
      updateClass: "evergreen",
    },
    {
      id: "m365-04",
      title: "Why a Conditional Access policy did not apply: reading the sign-in log",
      category: "microsoft-365-entra-id",
      subcategory: "Conditional Access",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "conditional access policy not applied",
      secondaryKeywords: ["sign-in log conditional access", "why was policy not applied"],
      relatedTopics: ["m365-01", "intune-32"],
      updateClass: "annual",
    },
    {
      id: "m365-05",
      title: "Blocking legacy authentication without breaking something important",
      category: "microsoft-365-entra-id",
      subcategory: "Conditional Access",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "block legacy authentication",
      relatedTopics: ["m365-01"],
      updateClass: "annual",
    },
    {
      id: "m365-06",
      title: "Device filters in Conditional Access: targeting by device property, not group",
      category: "microsoft-365-entra-id",
      subcategory: "Conditional Access",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "conditional access device filter",
      relatedTopics: ["m365-01", "intune-14"],
      updateClass: "annual",
    },

    /* ---------------- Identity and access ---------------- */
    {
      id: "m365-10",
      title: "Entra ID group types: which one to use for licensing, access and policy",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "entra id group types",
      secondaryKeywords: ["security group vs microsoft 365 group", "dynamic group rules"],
      updateClass: "evergreen",
    },
    {
      id: "m365-11",
      title: "Dynamic group rules that do not silently stop matching",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "troubleshooting",
      searchIntent: "failure-mode",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "entra dynamic group not updating",
      relatedTopics: ["m365-10"],
      updateClass: "annual",
    },
    {
      id: "m365-12",
      title: "Privileged Identity Management: designing role activation people will actually use",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "entra pim setup",
      relatedTopics: ["m365-02"],
      updateClass: "annual",
    },
    {
      id: "m365-13",
      title: "Administrative units: when tenant-wide roles are too much",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "entra administrative units",
      relatedTopics: ["m365-12"],
      updateClass: "evergreen",
    },
    {
      id: "m365-14",
      title: "Guest access and B2B collaboration: the settings that decide your exposure",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "entra guest access settings",
      relatedTopics: ["m365-01"],
      updateClass: "annual",
    },
    {
      id: "m365-15",
      title: "Passwordless in practice: passkeys, Windows Hello and the rollout order",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "entra passwordless rollout",
      secondaryKeywords: ["passkeys entra id", "windows hello for business deployment"],
      relatedTopics: ["m365-01", "m365-16"],
      requiredSources: ["Microsoft Learn: Passwordless authentication deployment"],
      updateClass: "volatile",
    },
    {
      id: "m365-16",
      title: "Authentication methods policy: migrating off the legacy MFA settings",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "entra authentication methods policy migration",
      relatedTopics: ["m365-15"],
      updateClass: "volatile",
    },

    /* ---------------- Licensing ---------------- */
    {
      id: "m365-20",
      title: "Group-based licensing: assignment, inheritance and the errors it produces",
      category: "microsoft-365-entra-id",
      subcategory: "Licensing",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "microsoft 365 group based licensing",
      relatedTopics: ["m365-10"],
      updateClass: "annual",
    },
    {
      id: "m365-21",
      title: "What you actually lose stepping down a Microsoft 365 licence tier",
      category: "microsoft-365-entra-id",
      subcategory: "Licensing",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "microsoft 365 e3 vs e5",
      relatedTopics: ["m365-20"],
      updateClass: "volatile",
      notes:
        "Licensing changes frequently. Verify against current service descriptions at write time.",
    },

    /* ---------------- Copilot and AI readiness ---------------- */
    {
      id: "m365-30",
      title: "Copilot readiness: fix your permissions before you buy licences",
      category: "microsoft-365-entra-id",
      subcategory: "Collaboration",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "microsoft 365 copilot readiness",
      secondaryKeywords: ["copilot oversharing", "sharepoint permissions before copilot"],
      relatedTopics: ["m365-31", "m365-14"],
      requiredSources: ["Microsoft Learn: Microsoft 365 Copilot data protection"],
      updateClass: "volatile",
      notes: "High commercial intent. The oversharing angle is the genuinely useful one.",
    },
    {
      id: "m365-31",
      title: "Finding oversharing in SharePoint before it becomes a Copilot problem",
      category: "microsoft-365-entra-id",
      subcategory: "Collaboration",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "sharepoint oversharing report",
      relatedTopics: ["m365-30"],
      updateClass: "annual",
    },

    /* ---------------- Collaboration and data ---------------- */
    {
      id: "m365-40",
      title: "Sensitivity labels: a taxonomy small enough that people apply it",
      category: "microsoft-365-entra-id",
      subcategory: "Collaboration",
      contentType: "decision-framework",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "sensitivity labels design",
      relatedTopics: ["m365-30"],
      updateClass: "annual",
    },
    {
      id: "m365-41",
      title: "Retention policies vs retention labels: which one to reach for",
      category: "microsoft-365-entra-id",
      subcategory: "Collaboration",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "retention policy vs retention label",
      relatedTopics: ["m365-40"],
      updateClass: "annual",
    },
    {
      id: "m365-42",
      title: "Teams sprawl: governing creation without blocking work",
      category: "microsoft-365-entra-id",
      subcategory: "Collaboration",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "teams sprawl governance",
      relatedTopics: ["m365-10"],
      updateClass: "evergreen",
    },
    {
      id: "m365-43",
      title: "Exchange Online anti-spoofing: SPF, DKIM and DMARC configured correctly",
      category: "microsoft-365-entra-id",
      subcategory: "Collaboration",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P0",
      status: "IDEA",
      targetKeyword: "microsoft 365 dmarc setup",
      secondaryKeywords: ["spf dkim dmarc exchange online", "dmarc reject policy"],
      requiredSources: ["Microsoft Learn: Email authentication in Microsoft 365"],
      updateClass: "annual",
    },

    /* ---------------- Automation ---------------- */
    {
      id: "m365-50",
      title: "Automating joiner-mover-leaver with Microsoft Graph",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "how-to",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "joiner mover leaver automation microsoft 365",
      relatedTopics: ["m365-10", "m365-20", "intune-71"],
      requiredSources: ["Microsoft Graph documentation: users and group membership"],
      updateClass: "annual",
    },
    {
      id: "m365-51",
      title: "Entra ID lifecycle workflows: what they cover and where scripts still win",
      category: "microsoft-365-entra-id",
      subcategory: "Identity",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "entra lifecycle workflows",
      relatedTopics: ["m365-50"],
      updateClass: "volatile",
    },
  ],
};
