import type { Segment } from "../types";

/**
 * Software and developer tools backlog.
 *
 * Deliberately weighted towards decisions and licensing rather than tutorials:
 * "how to install X" is answered adequately by every vendor's own docs, while
 * "which of these should a team standardise on, and what does it cost" is not.
 */
export const segment: Segment = {
  name: "Software / Developer Tools",
  category: "software",
  topics: [
    {
      id: "software-01",
      title: "VS Code or a JetBrains IDE: choosing by workload, not preference",
      category: "software",
      subcategory: "Developer tools",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P0",
      status: "PUBLISHED",
      targetKeyword: "vs code vs jetbrains",
      updateClass: "volatile",
      articleSlug: "vscode-vs-jetbrains",
      notes: "Volatile: licensing terms and marketplace restrictions change.",
    },
    {
      id: "software-02",
      title: "Standardising formatting and linting so the editor stops mattering",
      category: "software",
      subcategory: "Developer tools",
      contentType: "how-to",
      searchIntent: "how-to",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "editorconfig prettier eslint team setup",
      relatedTopics: ["software-01"],
      updateClass: "evergreen",
    },
    {
      id: "software-03",
      title: "Open source licence obligations a business actually has to meet",
      category: "software",
      subcategory: "Developer tools",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "open source licence compliance business",
      secondaryKeywords: ["gpl vs mit commercial use", "copyleft obligations"],
      updateClass: "evergreen",
      notes: "Must be careful to describe obligations, not give legal advice.",
    },
    {
      id: "software-04",
      title:
        "Package manager supply-chain risk: what pinning and lockfiles do not protect you from",
      category: "software",
      subcategory: "Developer tools",
      contentType: "analysis",
      searchIntent: "architecture",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "npm supply chain attack protection",
      relatedTopics: ["software-03"],
      updateClass: "annual",
    },
    {
      id: "software-05",
      title: "Windows Package Manager in an enterprise: what winget can and cannot replace",
      category: "software",
      subcategory: "Windows",
      contentType: "analysis",
      searchIntent: "decision",
      priority: "P1",
      status: "IDEA",
      targetKeyword: "winget enterprise deployment",
      relatedTopics: ["intune-24"],
      updateClass: "volatile",
    },
    {
      id: "software-06",
      title: "WSL2 in a managed environment: networking, security and the support boundary",
      category: "software",
      subcategory: "Windows",
      contentType: "explainer",
      searchIntent: "architecture",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "wsl2 enterprise security",
      updateClass: "annual",
    },
    {
      id: "software-07",
      title: "Browser choice for a managed estate: management surface, not benchmarks",
      category: "software",
      subcategory: "Productivity",
      contentType: "comparison",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "enterprise browser management comparison",
      relatedTopics: ["intune-13"],
      updateClass: "volatile",
    },
    {
      id: "software-08",
      title: "Self-hosting versus SaaS for internal tools: the honest cost comparison",
      category: "software",
      subcategory: "Productivity",
      contentType: "decision-framework",
      searchIntent: "decision",
      priority: "P2",
      status: "IDEA",
      targetKeyword: "self host vs saas internal tools",
      updateClass: "evergreen",
    },
  ],
};
