import type { Article } from "../../types";

export const article: Article = {
  slug: "aws-transit-gateway-vs-vpc-peering",
  category: "cloud",
  contentType: "comparison",
  subcategory: "Architecture",
  title: "Peering does not scale, and the arithmetic says so",
  seoTitle: "AWS Transit Gateway vs VPC Peering: when to switch",
  metaDescription:
    "Full-mesh peering grows as the square of your VPC count. What Transit Gateway solves, what it charges for, and the routing traps that come with it.",
  standfirst:
    "Ten VPCs need forty-five links. Fifty need more than twelve hundred. That curve decides this for you.",
  excerpt:
    "VPC peering is free and simple until the mesh grows. Where the arithmetic breaks, what Transit Gateway gives you in exchange, and the two settings that decide whether it works.",
  authorId: "rahul-velapure",
  publishedAt: "2026-08-23",
  lastReviewedAt: "2026-08-23",
  nextReviewAt: "2027-08-23",
  readingMinutes: 4,
  primaryKeyword: "AWS Transit Gateway vs VPC Peering",
  secondaryKeywords: [
    "VPC peering limits",
    "Transit Gateway route tables",
    "AWS hub and spoke networking",
    "Transit Gateway appliance mode",
    "transitive routing AWS",
  ],
  tags: ["AWS", "Cloud", "Networking", "Architecture"],
  reviewStatus: "research-based",
  relatedSlugs: ["bgp-in-the-cloud-why-it-matters", "cloud-egress-costs-architecture-problem"],
  methodology:
    "Written from AWS documentation on Transit Gateway, VPC peering and VPC quotas, verified August 2026. The mesh arithmetic is stated because it is arithmetic. Quota values are described relative to what a growing estate needs rather than quoted, since they are adjustable and change; the same applies to rates, which are not given. Scope is deliberately the network layer — service-level routing is a different decision.",
  body: [
    { type: "p", text: "Most AWS estates start with one VPC. Then the estate grows. A team needs a new VPC. A test system needs its own space. An acquisition brings another network." },
    { type: "p", text: "Soon, those VPCs need to talk. AWS gives you two main choices. You can use VPC peering. Or you can use Transit Gateway." },
    { type: "p", text: "The choice matters. Peering grows as a mesh. Transit Gateway uses a hub. The math gets hard long before the design looks hard." },
    { type: "h2", id: "maths", text: "The arithmetic that decides it" },
    { type: "p", text: "VPC peering is one to one. Each pair of VPCs gets a link. Each link needs route work on both sides." },
    { type: "p", text: "A full mesh across n VPCs needs n(n−1)/2 links. The count rises fast." },
    { type: "table", caption: "Connections required for a full mesh", head: ["VPCs", "Peering connections"], rows: [["5", "10"], ["10", "45"], ["20", "190"], ["50", "1,225"]] },
    { type: "p", text: "There is also a per-VPC limit on active peer links. That limit can be changed. It still puts a cap on large meshes." },
    { type: "p", text: "The bigger cost is daily work. Add one VPC. Then update every VPC that must reach it. Each change touches more route tables." },
    { type: "h2", id: "two-limits", text: "Two things peering cannot do" },
    { type: "p", text: "Peering has two key limits. Know them before you build around it." },
    { type: "p", text: "**It is not transitive.** A peers with B. B peers with C. A still cannot reach C through B. Each pair needs its own peer link." },
    { type: "p", text: "**It cannot use overlapping ranges.** Two VPCs with the same CIDR block cannot be peered. This is common after mergers and fast growth." },
    { type: "h2", id: "tgw", text: "What Transit Gateway changes" },
    { type: "p", text: "Transit Gateway is a hub. VPCs attach to the hub. They do not need a link to every other VPC." },
    { type: "p", text: "The hub has its own route tables. An attachment joins a route table. That table controls where the VPC can send traffic." },
    { type: "table", caption: "The differences that drive the choice", head: ["", "VPC peering", "Transit Gateway"], rows: [["Growth", "Links grow as a mesh", "One attachment per VPC"], ["Transitive routing", "Not supported", "Supported"], ["Overlapping CIDRs", "Cannot be peered", "Can coexist in separate routing domains"], ["Segmentation", "Choose peer pairs", "Use route table association"], ["Charging", "No charge for the link", "Attachment and data processing charges"]] },
    { type: "p", text: "This gives you a clear way to split traffic. Production can use one route table. Test can use another. Both can share one hub." },
    { type: "callout", variant: "note", title: "Overlap is tolerated, not solved", text: "Two VPCs with the same CIDR can attach to a Transit Gateway. They still cannot route to each other. Address translation is needed if they must talk." },
    { type: "h2", id: "cost", text: "Where the cost comes from" },
    { type: "p", text: "Peering has no charge for the link. Traffic still uses normal data transfer pricing." },
    { type: "p", text: "Transit Gateway has two main cost parts. There is a charge for each attachment. There is also a charge for data that the hub processes." },
    { type: "p", text: "The data charge can grow fast. The route matters. A VPC that reaches a cloud service may not need the hub. A VPC endpoint can keep that path local." },
    { type: "callout", variant: "tip", title: "Keep the path simple", text: "Keep VPC to VPC traffic on the hub when the hub is the design. Keep other traffic off the hub unless you need central inspection. This can reduce data processing cost." },
    { type: "p", text: "This is also an egress design issue. See [egress charges generally](/cloud/cloud-egress-costs-architecture-problem). A route table can create a bill without anyone naming that path in the plan." },
    { type: "h2", id: "inspection", text: "Central inspection can add risk" },
    { type: "p", text: "Many teams want traffic to pass through a firewall. Transit Gateway can send spoke traffic to an attachment with the firewall." },
    { type: "p", text: "That design adds two main risks. The first is load. The second is flow symmetry." },
    { type: "p", text: "Load is easy to miss. A flow can cross the hub on its way to the firewall. It can cross again on its way to the target. The firewall also becomes part of the path for each flow." },
    { type: "p", text: "Symmetry is also key. A stateful firewall needs both sides of a flow to reach the same node. If the return path hits another node, that node may have no flow state." },
    { type: "callout", variant: "warning", title: "Appliance mode matters", text: "Use appliance mode on the attachment that holds stateful network appliances. It helps keep both sides of a flow on the same appliance node. Without it, some flows can fail in ways that look like app errors." },
    { type: "p", text: "Do not inspect every flow by habit. Inspect the flows that need it. Let safe, high-volume traffic take a direct path when the design allows it." },
    { type: "h2", id: "mistakes", text: "Two more mistakes to avoid" },
    { type: "p", text: "**Route limits.** On-premises networks can send many routes over Direct Connect. A Transit Gateway route table has a limit. Summarise routes at the edge when you can. For more context, see [BGP in the cloud](/enterprise-networking/bgp-in-the-cloud-why-it-matters)." },
    { type: "p", text: "**Shared attachment subnets.** A VPC attachment uses network interfaces in chosen subnets. Do not mix those subnets with busy app workloads. Use small, dedicated subnets in each availability zone." },
    { type: "h2", id: "choosing", text: "Choosing when to switch" },
    { type: "p", text: "Peering is still a good fit for a small set of VPCs. It works well for stable, point to point traffic. It has no hub to run." },
    { type: "p", text: "Transit Gateway is a better fit when you need transitive routing. It also helps when you need clear network segments. It fits well with on-premises links and larger VPC estates." },
    { type: "p", text: "Do not wait for the mesh to hurt. Moving a large mesh later means changing many route tables. A hub is often easier to adopt while the estate is still small." },
    { type: "callout", variant: "note", title: "This is the network layer", text: "This article covers VPC routing. Service discovery and service auth are different problems. For that layer, see [VPC Lattice or API Gateway](/cloud/aws-vpc-lattice-vs-api-gateway-service-networking)." },
    { type: "h2", id: "takeaways", text: "What to do with this" },
    { type: "ul", items: ["Count the VPCs on the roadmap, not just today’s VPCs.", "Plan IP ranges early. Overlap is hard to fix later.", "Use route tables to make network segments clear.", "Use appliance mode with stateful inspection appliances.", "Give Transit Gateway attachments their own subnets."] },
    { type: "p", text: "Peering is not wrong. Transit Gateway is not always right. The key is scale. Use the mesh while it is small. Use a hub when the network needs one." },
  ],
  faq: [
    { question: "How many VPCs before peering stops working?", answer: "There is no single number. The mesh is the issue. Ten VPCs need forty-five links. Twenty need one hundred and ninety. The work can become hard before a quota does." },
    { question: "Can I peer two VPCs that use the same IP range?", answer: "No. VPC peering does not support overlapping CIDR blocks. A Transit Gateway can attach both VPCs. They still need address translation to talk to each other." },
    { question: "Why is my Transit Gateway bill higher than expected?", answer: "Check the traffic path. Some service or internet traffic may be crossing the hub without a need to do so. A VPC endpoint can keep some service traffic local." },
    { question: "Why do connections through my firewall drop?", answer: "The flow may be reaching different firewall nodes. A stateful node needs the flow state. Use appliance mode on the firewall attachment." },
    { question: "Should I start with peering and move later?", answer: "Only if the estate will stay small. A later move can mean many route changes. A hub can be easier to adopt early." },
  ],
  sources: [
    { title: "What is a transit gateway?", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html" },
    { title: "Transit gateway route tables", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/vpc/latest/tgw/tgw-route-tables.html" },
    { title: "Transit gateway appliance mode support", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-appliance-scenario.html" },
    { title: "What is VPC peering?", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html" },
    { title: "Amazon VPC quotas", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html" },
  ],
};
