import type { Article } from "../../types";

export const article: Article = {
  slug: "aws-lambda-cold-start-optimization-snapstart",
  category: "cloud",
  contentType: "explainer",
  subcategory: "Serverless",
  title: "A cold start has phases, and only one phase responds to more memory",
  seoTitle: "AWS Lambda cold starts: SnapStart and provisioned concurrency",
  metaDescription:
    "Lambda cold starts have several phases. Each phase has a different fix. Learn what memory changes, what SnapStart changes, and when pre-warming makes sense.",
  standfirst:
    "More memory is not a universal cold-start fix. It helps with CPU work, but it cannot fix every phase.",
  excerpt:
    "A cold start has several steps. Find the slow step first. Then choose between code changes, SnapStart and provisioned concurrency.",
  authorId: "rahul-velapure",
  publishedAt: "2026-08-23",
  lastReviewedAt: "2026-08-23",
  nextReviewAt: "2027-02-23",
  readingMinutes: 5,
  primaryKeyword: "AWS Lambda cold start",
  secondaryKeywords: [
    "Lambda SnapStart",
    "provisioned concurrency cost",
    "Lambda init phase",
    "CRaC checkpoint restore",
    "lazy initialization Lambda",
  ],
  tags: ["AWS", "Cloud", "Serverless", "Performance", "Architecture"],
  reviewStatus: "research-based",
  relatedSlugs: ["aurora-serverless-v2-scaling-connection-limits", "cloud-cost-controls"],
  methodology:
    "Written from AWS documentation on the Lambda execution environment lifecycle, SnapStart, provisioned concurrency and function scaling, plus the OpenJDK CRaC project, verified August 2026. Latency figures are not given because they vary by runtime, package size, dependencies and region. Runtime support and gateway limits are treated as version-dependent.",
  body: [
    { type: "p", text: "Cold starts are one of the most common Lambda complaints. They are also one of the most misunderstood." },
    { type: "p", text: "The usual advice is simple: add memory. Sometimes that works. Sometimes it does almost nothing." },
    { type: "p", text: "The reason is simple too. A cold start is a set of steps. Each step has a different cause." },
    { type: "h2", id: "phases", text: "What happens before your code runs" },
    { type: "p", text: "When Lambda needs a new execution environment, it moves through several phases." },
    {
      type: "ol",
      items: [
        "**Lambda creates an isolated environment.** It prepares the place where the function will run.",
        "**Lambda fetches the package and layers.** Your code and dependencies must be available first.",
        "**The runtime starts.** Node.js, Python, Java or another supported runtime boots.",
        "**Your init code runs.** This can include SDK clients, caches and connection setup.",
        "**The handler runs.** This is the work for the request itself.",
      ],
    },
    { type: "p", text: "The caller waits for all of these steps. That is why a cold start can hurt a user even when the handler itself is fast." },
    {
      type: "callout",
      variant: "note",
      title: "More memory helps only some phases",
      text: "More memory also gives a Lambda function more CPU. That can speed up runtime startup and init work. It does not make a large package smaller or make every network fetch faster. Measure the init phase before you change memory.",
    },
    { type: "p", text: "Lambda exposes initialization time in its execution data. Use that signal first. It tells you whether the work is inside the function or outside it." },
    { type: "h2", id: "snapstart", text: "SnapStart saves the startup work" },
    { type: "p", text: "Some runtimes have a lot of startup work. A JVM can load a framework and many classes before the first request is ready." },
    { type: "p", text: "SnapStart changes when that work happens. The runtime starts at deployment. Your init code runs. Lambda then saves the memory state as a snapshot." },
    { type: "p", text: "A later cold start can restore that snapshot. It does not need to build the same state from zero. The slow startup work happens once instead of for every new environment." },
    { type: "p", text: "This is a different idea from keeping an environment warm. It uses checkpoint and restore techniques, including work from the OpenJDK CRaC project." },
    { type: "h3", id: "snapstart-limits", text: "Two things you must fix" },
    { type: "p", text: "A snapshot saves memory state. That means it can also save state that should not be reused." },
    { type: "p", text: "**Connections can be stale.** A database connection opened during init can be captured. When the snapshot is restored later, the remote side may have closed it. The app must detect that state and reconnect. The same design rule matters for [connection handling on a scaling database](/cloud/aurora-serverless-v2-scaling-connection-limits)." },
    { type: "p", text: "**Random state can repeat.** If a random generator gets its seed during init, the seed can be saved too. Restores can then start from the same state. Values that should be unpredictable may repeat." },
    { type: "callout", variant: "warning", title: "Re-seed after restore", text: "The dangerous part of frozen randomness is that the function may keep working. There may be no error. Use the supported restore hook or another safe design to refresh random state after a restore." },
    { type: "p", text: "That bug can survive testing because normal invocations use fresh startup state. SnapStart changes that test condition." },
    { type: "callout", variant: "note", title: "Runtime support changes", text: "SnapStart support has expanded since launch. Older articles may say it is limited to Java. Check the current AWS support list for the runtime you use." },
    { type: "h2", id: "provisioned", text: "Provisioned concurrency removes the wait" },
    { type: "p", text: "The other AWS-native option is to keep execution environments ready before requests arrive. This is provisioned concurrency." },
    { type: "p", text: "It works because the environment is already initialized. The request does not pay the normal cold-start setup." },
    { type: "p", text: "The trade is cost. You pay for the provisioned capacity while it is reserved. A short peak can mean many quiet hours of paid capacity." },
    { type: "p", text: "That makes a direct cost comparison useful. Compare provisioned concurrency with a small container service for the same workload. The result may favor Lambda or containers. Either result is useful." },
    { type: "p", text: "Scheduled changes can help with a predictable daily peak. They do not solve an unexpected spike that arrives before the extra capacity is ready." },
    { type: "h2", id: "code", text: "Code changes can be the cheapest fix" },
    { type: "p", text: "When SnapStart does not fit and provisioned concurrency costs too much, improve the function itself." },
    {
      type: "ul",
      items: [
        "**Use lazy initialization.** Build clients on first use when that is safe. Cache them for later calls.",
        "**Trim the package.** Remove unused dependencies and layers. Memory cannot fix a package that is too large to fetch quickly.",
        "**Check extensions.** Monitoring extensions can add their own startup work. Measure the extra time they introduce.",
        "**Use response streaming when it helps.** It can improve what the user sees without making the function itself faster.",
      ],
    },
    { type: "h2", id: "traps", text: "Two limits cause confusing failures" },
    { type: "p", text: "**Initialization has a time limit.** Heavy work in init can fail before the handler runs. Large downloads and cache warm-ups are common causes." },
    { type: "p", text: "**Concurrency errors are not a queue.** When a function cannot accept more requests, Lambda can reject new work. A client that retries at once can add even more load." },
    { type: "callout", variant: "note", title: "Check the gateway limit", text: "API Gateway limits have changed across configurations and generations. Check the current limit for the API type you use before making it an architectural assumption." },
    { type: "h2", id: "choosing", text: "Match the fix to the slow phase" },
    {
      type: "table",
      caption: "Use the smallest fix that targets the real delay",
      head: ["Main delay", "Best first move"],
      rows: [
        ["Runtime or framework startup", "SnapStart when the runtime supports it"],
        ["Large package or layer download", "Trim dependencies and layers"],
        ["Your own init code", "Lazy initialization or SnapStart"],
        ["Cold starts are not acceptable", "Provisioned concurrency after cost review"],
        ["User waits on the body", "Response streaming where it fits"],
      ],
    },
    { type: "h2", id: "takeaways", text: "What to do" },
    {
      type: "ul",
      items: [
        "Measure init time before changing memory.",
        "With SnapStart, refresh random state and validate connections after restore.",
        "Compare a full day of provisioned concurrency with a container option.",
        "Move heavy setup out of init when safe.",
        "Check current runtime support and gateway limits before relying on old advice.",
      ],
    },
    { type: "p", text: "A cold start is not one problem. It is a group of steps that happen before the handler runs. Find the slow step first. Then the right fix is often clear, and the cheapest fix may be a small code change." },
  ],
  faq: [
    { question: "Will more memory fix a cold start?", answer: "Only when CPU work is the slow part. Memory will not solve every startup phase. Measure init time first." },
    { question: "What does SnapStart do?", answer: "It runs startup work once and saves the memory state. Later environments restore that state instead of starting from zero." },
    { question: "Why is random state a SnapStart risk?", answer: "A seed created during init can be saved in the snapshot. Restores can then start from the same state." },
    { question: "Is provisioned concurrency always worth it?", answer: "No. It removes cold-start wait, but you pay for reserved capacity while it is idle. Compare the full-day cost." },
    { question: "Why can a function fail before the handler?", answer: "Heavy initialization work can hit the init time limit. Move large setup tasks or downloads out of that phase when safe." },
  ],
  sources: [
    { title: "Lambda execution environment lifecycle", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html" },
    { title: "Improving startup performance with Lambda SnapStart", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html" },
    { title: "Lambda SnapStart uniqueness and runtime hooks", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/lambda/latest/dg/snapstart-uniqueness.html" },
    { title: "Configuring provisioned concurrency", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html" },
    { title: "CRaC: Coordinated Restore at Checkpoint", publisher: "OpenJDK", url: "https://openjdk.org/projects/crac/" },
  ],
};
