import type { Article } from "../../types";

export const article: Article = {
  slug: "postgresql-connection-pooling-pgbouncer-rds-proxy",
  category: "cloud",
  contentType: "explainer",
  subcategory: "Database",
  title: "Postgres gives each connection a process, and that shapes the design",
  seoTitle: "PostgreSQL connection pooling: PgBouncer and RDS Proxy",
  metaDescription:
    "Postgres uses a process for each connection. Learn why that makes pooling important, what transaction pooling breaks, and why RDS Proxy can pin sessions.",
  standfirst:
    "Each Postgres connection has a process behind it. That is why pooling matters as your app grows.",
  excerpt:
    "Postgres connections use real processes. Pooling lets many clients share fewer database connections, but the mode you choose can change session behavior.",
  authorId: "rahul-velapure",
  publishedAt: "2026-08-23",
  lastReviewedAt: "2026-08-23",
  nextReviewAt: "2027-08-23",
  readingMinutes: 4,
  primaryKeyword: "PostgreSQL connection pooling",
  secondaryKeywords: ["PgBouncer transaction pooling", "RDS Proxy pinning", "prepared statement does not exist", "max_connections PostgreSQL", "too many clients already"],
  tags: ["Database", "PostgreSQL", "Cloud", "AWS", "Architecture"],
  reviewStatus: "research-based",
  relatedSlugs: ["aurora-serverless-v2-scaling-connection-limits", "aws-lambda-cold-start-optimization-snapstart"],
  methodology:
    "Written from PostgreSQL documentation on connections and resource limits, PgBouncer documentation on pooling modes and prepared statements, and AWS documentation on RDS Proxy and pinning, verified August 2026. Per-connection memory, safe counts and latency figures are not quoted because they vary by workload, version and instance.",
  body: [
    { type: "p", text: "Most databases use threads for client work. Postgres gives each connection a process." },
    { type: "p", text: "That matters. A process needs its own memory and scheduling time. A very large connection count can make the server spend more time managing processes than running useful queries." },
    { type: "p", text: "That is why a Postgres connection is a resource to manage, not a cheap socket you can open without thought." },
    { type: "h2", id: "limit", text: "Why raising the connection limit can make things worse" },
    { type: "p", text: "The first response to a connection error is often to raise the limit. It is one setting. The error can disappear at once." },
    { type: "p", text: "But the root problem may stay. A server with too many processes can become slow long before it reaches a clear failure. Queries wait. Context switches rise. The system feels sick, but the error message is gone." },
    { type: "p", text: "A better pattern is to keep the number of real database connections modest. Put a pool in front of them. Let many clients share a smaller set of connections." },
    { type: "callout", variant: "note", title: "App pools do not pool the whole fleet", text: "A pool inside one app process is still local to that process. Twenty replicas with twenty connections each can present hundreds of connections to Postgres. The database sees the total. A fleet-wide pooler solves a different problem." },
    { type: "h2", id: "modes", text: "PgBouncer has three pooling modes" },
    { type: "p", text: "PgBouncer is a common choice. The mode you pick changes the behavior of the application." },
    { type: "table", caption: "When the pooler gives a real connection back", head: ["Mode", "Connection held for", "Main trade"], rows: [["Session", "Full client session", "Safe, but little sharing"], ["Transaction", "One transaction", "Strong sharing, less session state"], ["Statement", "One statement", "Strongest sharing, limited transactions"]] },
    { type: "p", text: "Session mode keeps a database connection for the full client session. It is easy to reason about. It also gives you little benefit if clients sit idle with open sessions." },
    { type: "p", text: "Transaction mode is where pooling becomes useful. A client gets a real connection for one transaction. The pool then gives that connection to another client." },
    { type: "p", text: "That works well, but it changes an important assumption. A client may not get the same backend connection for its next transaction." },
    { type: "h2", id: "session-state", text: "Session state may not follow the client" },
    { type: "p", text: "A setting applied to one backend connection can vanish when the client gets another connection. This includes search paths, time zones and some session variables." },
    { type: "p", text: "The bugs can look random. One request may use the expected time zone. Another may not. One query may find an object. Another may fail because it landed on a connection with different state." },
    { type: "callout", variant: "warning", title: "Prepared statements are a common trap", text: "A named prepared statement lives on the backend connection where it was created. Transaction pooling can send the next call to another connection. That backend has no statement with that name, so the query fails." },
    { type: "p", text: "This is common with ORMs. Many use server-side prepared statements by default. Before enabling transaction pooling, check the driver settings your application uses." },
    { type: "p", text: "You can disable server-side prepared statements. You can also use a driver mode that avoids named statements. Newer pooler versions can support more prepared-statement cases, but the feature still needs correct setup." },
    { type: "h2", id: "rds-proxy", text: "RDS Proxy adds managed pooling on AWS" },
    { type: "p", text: "RDS Proxy offers managed connection pooling for supported AWS databases. It can also help during failover. Client connections can stay on the proxy while the database endpoint changes." },
    { type: "p", text: "The proxy can also work with IAM authentication. That can reduce the need to pass a long-lived database password through the app." },
    { type: "p", text: "The important part is how the proxy handles session state." },
    { type: "callout", variant: "warning", title: "Pinning can stop the pooling benefit", text: "When RDS Proxy sees state that must stay tied to a backend, it can pin the client to one connection. That protects application behavior. It also means that connection is no longer shared for that client." },
    { type: "p", text: "Pinning is a quiet problem. The application still works. The proxy is just doing less multiplexing. Watch the pinning metrics. If pinning is high, find which application behavior triggers it." },
    { type: "h2", id: "scenario", text: "How the incident appears" },
    { type: "p", text: "An app scales out. Each new replica opens its own pool. Total connections pass the database limit. New clients fail." },
    { type: "p", text: "The app restarts. More replicas reconnect. That creates more connection attempts during the incident." },
    { type: "p", text: "A pooler fixes the first problem. Then transaction pooling exposes the second layer. Prepared statements fail. Session settings do not always follow the client." },
    { type: "p", text: "None of those behaviors appeared by magic. The pooling layer made the hidden assumptions visible." },
    { type: "h2", id: "replication", text: "Check connection rules for your Postgres version" },
    { type: "p", text: "Replication and change-data-capture connections also need headroom. Their interaction with general connection limits can differ between PostgreSQL versions and deployment types." },
    { type: "p", text: "That matters because a busy application can use the headroom you thought was reserved for replication. The result can be lag at the same time as user traffic is high." },
    { type: "p", text: "Use the settings for the version you run. Do not copy an old connection-count rule from a blog post." },
    { type: "h2", id: "choosing", text: "Choosing a pooler" },
    { type: "table", caption: "A practical choice", head: ["PgBouncer", "RDS Proxy"], rows: [["You need several pooling modes", "You want a managed AWS service"], ["You run outside AWS", "You want managed failover support"], ["You want direct control", "You want IAM authentication options"], ["You can operate the pooler", "You do not want to run one"]] },
    { type: "p", text: "Keep the application pool too. The app pool reduces repeated handshakes. The fleet pool reduces the number of real database connections. They solve different problems." },
    { type: "h2", id: "takeaways", text: "What to do" },
    { type: "ul", items: ["Do not solve connection errors by raising the limit without checking process and memory pressure.", "Use a pooler when many app replicas share one database.", "Treat transaction pooling as a behavior change. Check session state first.", "Test prepared statements before enabling transaction pooling.", "Watch RDS Proxy pinning. High pinning can hide a loss of pooling efficiency."] },
    { type: "p", text: "Postgres is not wrong for using a process per connection. That design provides useful isolation. The lesson is that connection count becomes a real capacity limit as an application grows. Pooling manages that limit. The pooling mode then decides which application assumptions still hold." },
  ],
  faq: [
    { question: "Why not raise max_connections?", answer: "Because each connection uses a process. A very high count can make the server slow even before a hard error appears." },
    { question: "Why does a prepared statement disappear?", answer: "Transaction pooling can send the next request to another backend connection. That connection never created the statement." },
    { question: "Do I still need an app pool?", answer: "Yes. The app pool cuts repeated handshakes. A fleet pooler reduces the number of real database connections." },
    { question: "What is RDS Proxy pinning?", answer: "The proxy keeps a client on one backend connection when session state requires it. The app keeps working, but sharing drops." },
    { question: "Which PgBouncer mode is best?", answer: "Transaction mode is often the useful choice, but it changes session behavior. Check the application before switching." },
  ],
  sources: [
    { title: "PostgreSQL: Connections and Authentication", publisher: "PostgreSQL", url: "https://www.postgresql.org/docs/current/runtime-config-connection.html" },
    { title: "PgBouncer configuration: pooling modes", publisher: "PgBouncer", url: "https://www.pgbouncer.org/config.html" },
    { title: "PgBouncer FAQ: prepared statements and transaction pooling", publisher: "PgBouncer", url: "https://www.pgbouncer.org/faq.html" },
    { title: "Using Amazon RDS Proxy", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html" },
    { title: "Avoiding pinning with RDS Proxy", publisher: "Amazon Web Services", url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy-managing.html" },
  ],
};
