import type { Article } from "../../types";

export const article: Article = {
  slug: "intune-advanced-analytics-operations",
  category: "microsoft-intune",
  contentType: "explainer",
  subcategory: "Endpoint Analytics",
  title: "Microsoft Intune Advanced Analytics: turn device data into action",
  seoTitle: "Intune Advanced Analytics: Turn Device Data Into Action",
  metaDescription: "How Intune Advanced Analytics uses device query, timelines, anomalies, battery, and resource data for endpoint operations.",
  standfirst: "Good endpoint data should lead to action. Advanced Analytics adds views that help teams find the cause, not just the symptom.",
  excerpt: "Use device query for live facts, device timeline for events, and reports for fleet trends.",
  authorId: "rahul-velapure",
  publishedAt: "2026-09-25",
  readingMinutes: 6,
  primaryKeyword: "Intune Advanced Analytics",
  secondaryKeywords: ["device query", "device timeline", "endpoint analytics", "Intune anomalies"],
  tags: ["Intune", "Endpoint Management", "Windows", "Operations"],
  reviewStatus: "research-based",
  draft: true,
  methodology: "Written from current Microsoft Learn documentation for Intune Advanced Analytics and Device Timeline. The listed capabilities and operational flow are based on those sources.",
  body: [
    { type: "p", text: "Endpoint teams often have lots of data. The hard part is finding the one fact that explains a user problem." },
    { type: "p", text: "Intune Advanced Analytics adds tools for that work. Microsoft documents Device Query, Device Timeline, anomalies, battery health, resource performance, and more. " },
    { type: "h2", id: "four-use-cases", text: "Four useful questions" },
    { type: "ul", items: ["What is true on this device now?", "What happened on this device?", "Is the problem part of a wider trend?", "Which devices need action first?"] },
    { type: "h2", id: "device-query", text: "Use Device Query for live facts" },
    { type: "p", text: "Device Query gives near real time data about Windows devices. It is useful when a support case needs a current fact." },
    { type: "p", text: "For example, a support engineer may need to check device state before asking a user to reboot. The query can give data that is newer than a normal report." },
    { type: "h2", id: "device-timeline", text: "Use Device Timeline for the story" },
    { type: "p", text: "A timeline shows events on one device. Microsoft lists events such as app crashes, boots, sign ins, and detected anomalies." },
    { type: "p", text: "This helps when a problem is not one event. A timeline can show what changed before the user saw the issue." },
    { type: "h2", id: "anomalies", text: "Use anomalies for change detection" },
    { type: "p", text: "The anomalies report tracks device health changes. This is useful after an OS update, driver change, or app rollout." },
    { type: "h2", id: "battery", text: "Use battery data for hardware planning" },
    { type: "p", text: "Battery health can show which devices need attention. It can also help teams plan refresh work." },
    { type: "h2", id: "resource-performance", text: "Use resource performance for slow devices" },
    { type: "p", text: "Resource performance data can show patterns by device, model, or manufacturer. This can help separate a user problem from a fleet problem." },
    { type: "h2", id: "support-process", text: "Put the data into support" },
    { type: "ol", items: ["Use Device Query for current facts.", "Use Device Timeline for event history.", "Use anomalies after major changes.", "Use battery and resource data for fleet trends.", "Record the finding in the support case."] },
    { type: "callout", variant: "tip", title: "Do not collect data without a question", text: "Start with the support question. Then choose the smallest report or query that can answer it." },
    { type: "h2", id: "common-mistakes", text: "Common mistakes" },
    { type: "ul", items: ["Using a fleet report for a one-device problem.", "Using Device Query without a clear question.", "Ignoring the time of an event.", "Treating an anomaly as proof of root cause.", "Collecting data but not recording the action taken."] },
    { type: "h2", id: "conclusion", text: "Conclusion" },
    { type: "p", text: "Advanced Analytics is most useful when it becomes part of daily support. Query for facts. Use timelines for context. Use reports for trends. Then act on the result." },
  ],
  faq: [
    { question: "What is Intune Device Query?", answer: "It provides near real time data about the state and configuration of Windows devices in Intune." },
    { question: "What is Device Timeline?", answer: "It shows a history of events on a device, including events such as app crashes, boots, sign ins, and anomalies." },
    { question: "Can Advanced Analytics help after an update?", answer: "Yes. Microsoft documents anomalies and resource reports that can help teams spot changes after device or app updates." },
  ],
  sources: [
    { title: "Advanced Analytics overview", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/intune/advanced-analytics/" },
    { title: "Device Timeline report", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/intune/advanced-analytics/device-timeline" },
  ],
};
