/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CategoryIndexRouteImport } from './routes/$category.index'
import { Route as CategorySlugRouteImport } from './routes/$category.$slug'
import { Route as AuthorAuthorIdRouteImport } from './routes/author.$authorId'
import { Route as NewsletterIndexRouteImport } from './routes/newsletter.index'
import { Route as NewsletterConfirmedRouteImport } from './routes/newsletter.confirmed'
import { Route as TagTagRouteImport } from './routes/tag.$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorAuthorIdRoute = AuthorAuthorIdRouteImport.update({
  id: '/author/$authorId',
  path: '/author/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterIndexRoute = NewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmedRoute = NewsletterConfirmedRouteImport.update({
  id: '/newsletter/confirmed',
  path: '/newsletter/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/tag/$tag': typeof TagTagRoute
  '/$category/': typeof CategoryIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/tag/$tag': typeof TagTagRoute
  '/$category': typeof CategoryIndexRoute
  '/newsletter': typeof NewsletterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/tag/$tag': typeof TagTagRoute
  '/$category/': typeof CategoryIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$category/$slug'
    | '/author/$authorId'
    | '/newsletter/confirmed'
    | '/tag/$tag'
    | '/$category/'
    | '/newsletter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$category/$slug'
    | '/author/$authorId'
    | '/newsletter/confirmed'
    | '/tag/$tag'
    | '/$category'
    | '/newsletter'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$category/$slug'
    | '/author/$authorId'
    | '/newsletter/confirmed'
    | '/tag/$tag'
    | '/$category/'
    | '/newsletter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  AuthorAuthorIdRoute: typeof AuthorAuthorIdRoute
  NewsletterConfirmedRoute: typeof NewsletterConfirmedRoute
  TagTagRoute: typeof TagTagRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  NewsletterIndexRoute: typeof NewsletterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/$category'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$slug': {
      id: '/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/$category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$authorId': {
      id: '/author/$authorId'
      path: '/author/$authorId'
      fullPath: '/author/$authorId'
      preLoaderRoute: typeof AuthorAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/': {
      id: '/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof NewsletterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirmed': {
      id: '/newsletter/confirmed'
      path: '/newsletter/confirmed'
      fullPath: '/newsletter/confirmed'
      preLoaderRoute: typeof NewsletterConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  AuthorAuthorIdRoute: AuthorAuthorIdRoute,
  NewsletterConfirmedRoute: NewsletterConfirmedRoute,
  TagTagRoute: TagTagRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  NewsletterIndexRoute: NewsletterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
